import type { LessonConfig } from '@/components/kids/LessonEngine'

export const arabicLessonsPart1: Record<string, LessonConfig> = {
    'arabic-alif': {
        id: 'arabic-alif', letter: 'ا', word: 'أسد', wordEn: 'Lion', emoji: '🦁',
        color: 'from-emerald-400 to-teal-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আলিফ (ا) শিখি!', voiceText: 'এটি হলো আলিফ। আলিফ দিয়ে হয় আসাদুন - মানে সিংহ!', content: 'ا' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'আসাদুন - সিংহ', content: 'أسد' },
            { id: 'e3', type: 'pronounce', title: 'এবার তুমি বলো!', voiceText: 'আলিফ — আসাদুন', content: 'ا' },
            { id: 'e4', type: 'tap-correct', title: 'আলিফ (ا) কোথায়?', voiceText: 'আলিফ হরফটি খুঁজে বের করো!', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'আলিফ হরফের বুদবুদগুলো ফাটাও!', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'আলিফ হরফটি চিনতে পেরেছ?', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে সঠিক শব্দটি মিলিয়ে দাও', content: 'ا', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ا' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'আলিফ লেখা প্র্যাকটিস করো', content: 'ا' },
            { id: 'e9', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'সিংহ বা আসাদুন কোন হরফ দিয়ে শুরু হয়?', content: 'ا', options: ['ب', 'ا', 'ت', 'ث'], correctAnswer: 'ا' },
        ],
    },
    'arabic-ba': {
        id: 'arabic-ba', letter: 'ب', word: 'بطة', wordEn: 'Duck', emoji: '🦆',
        color: 'from-blue-400 to-cyan-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো বা (ب) শিখি!', voiceText: 'এটি বা! বা দিয়ে হয় বত্বাতুন - মানে হাঁস!', content: 'ب' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'বত্বাতুন - হাঁস', content: 'بطة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'বা — বত্বাতুন', content: 'ب' },
            { id: 'e4', type: 'tap-correct', title: 'বা (ب) কোথায়?', voiceText: 'বা হরফটি খুঁজে বের করো!', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'বা হরফের বুদবুদগুলো ফাটাও!', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ب', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ب' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'বা লেখা প্র্যাকটিস করো', content: 'ب' },
            { id: 'e9', type: 'quiz', title: 'চমৎকার! শেষ প্রশ্ন', voiceText: 'হাঁস বা বত্বাতুন কোন হরফ দিয়ে শুরু হয়?', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
        ],
    },
    'arabic-ta': {
        id: 'arabic-ta', letter: 'ت', word: 'تفاح', wordEn: 'Apple', emoji: '🍎',
        color: 'from-rose-400 to-pink-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো তা (ت) শিখি!', voiceText: 'এটি তা! তা দিয়ে হয় তুফফাহুন - মানে আপেল!', content: 'ت' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'তুফফাহুন - আপেল', content: 'تفاح' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'তা — তুফফাহুন', content: 'ت' },
            { id: 'e4', type: 'tap-correct', title: 'তা (ت) কোথায়?', voiceText: 'তা হরফটি খুঁজে বের করো!', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'তা হরফের বুদবুদগুলো ফাটাও!', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ت', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ت' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'তা লেখা প্র্যাকটিস করো', content: 'ت' },
            { id: 'e9', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'আপেল বা তুফফাহুন কোন হরফ দিয়ে শুরু হয়?', content: 'ت', options: ['ب', 'ث', 'ت', 'ن'], correctAnswer: 'ت' },
        ],
    },
    'arabic-tha': {
        id: 'arabic-tha', letter: 'ث', word: 'ثلج', wordEn: 'Snow', emoji: '❄️',
        color: 'from-sky-400 to-blue-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো ছা (ث) শিখি!', voiceText: 'এটি ছা। ছা দিয়ে হয় থালজ - মানে বরফ!', content: 'ث' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'থালজ - বরফ', content: 'ثلج' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ছা', content: 'ث' },
            { id: 'e4', type: 'tap-correct', title: 'ث কোথায়?', voiceText: 'ث খুঁজে বের করো', content: 'ث', options: ['ت', 'ث', 'ج', 'ح'], correctAnswer: 'ث' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ث বুদবুদ ফাটাও', content: 'ث', options: ['ت', 'ث', 'ج', 'ح'], correctAnswer: 'ث' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ث', options: ['ت', 'ث', 'ج', 'ح'], correctAnswer: 'ث' },
            { id: 'e7', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ث', options: ['ت-তা', 'ث-ছা', 'ج-জিম', 'ح-হা'], correctAnswer: 'ث' },
            { id: 'e8', type: 'trace', title: 'লিখি — ث', voiceText: 'ث লেখো', content: 'ث' },
            { id: 'e9', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ث এর নাম কী?', content: 'ث', options: ['তা', 'ছা', 'জিম', 'হা'], correctAnswer: 'ছা' },
        ],
    },
    'arabic-jeem': {
        id: 'arabic-jeem', letter: 'ج', word: 'جمل', wordEn: 'Camel', emoji: '🐪',
        color: 'from-violet-400 to-purple-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো জীম (ج) শিখি!', voiceText: 'এটি জীম! জীম দিয়ে হয় জামাালুন - মানে উট!', content: 'ج' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'জামাালুন - উট', content: 'جمل' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'জীম — জামাালুন', content: 'ج' },
            { id: 'e4', type: 'tap-correct', title: 'জীম (ج) কোথায়?', voiceText: 'জীম হরফটি খুঁজে বের করো!', content: 'ج', options: ['ح', 'ج', 'خ', 'ع'], correctAnswer: 'ج' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'জীম হরফের বুদবুদগুলো ফাটাও!', content: 'ج', options: ['ح', 'ج', 'خ', 'ع'], correctAnswer: 'ج' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ج', options: ['ح', 'ج', 'خ', 'ع'], correctAnswer: 'ج' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ج', options: ['ج-جمل', 'ح-حصان', 'خ-خروف', 'د-دب'], correctAnswer: 'ج' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'জীম লেখা প্র্যাকটিস করো', content: 'ج' },
            { id: 'e9', type: 'quiz', title: 'অনেক ভালো! শেষ প্রশ্ন', voiceText: 'উট বা জামাালুন কোন হরফ দিয়ে শুরু?', content: 'ج', options: ['ح', 'خ', 'ج', 'ع'], correctAnswer: 'ج' },
        ],
    },
    'arabic-ha': {
        id: 'arabic-ha', letter: 'ح', word: 'حصان', wordEn: 'Horse', emoji: '🐴',
        color: 'from-teal-400 to-cyan-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো হা (ح) শিখি!', voiceText: 'এটি হা! হা দিয়ে হয় হিসানুন - মানে ঘোড়া!', content: 'ح' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'হিসানুন - ঘোড়া', content: 'حصان' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'হা — হিসানুন', content: 'ح' },
            { id: 'e4', type: 'tap-correct', title: 'হা (ح) কোথায়?', voiceText: 'হা হরফটি খুঁজে বের করো!', content: 'ح', options: ['ج', 'ح', 'خ', 'ع'], correctAnswer: 'ح' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'হা হরফের বুদবুদগুলো ফাটাও!', content: 'ح', options: ['ج', 'ح', 'خ', 'ع'], correctAnswer: 'ح' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ح', options: ['ج', 'ح', 'خ', 'ع'], correctAnswer: 'ح' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ح', options: ['ج-جمل', 'ح-حصان', 'خ-خروف', 'د-دب'], correctAnswer: 'ح' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'হা লেখা প্র্যাকটিস করো', content: 'ح' },
            { id: 'e9', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'ঘোড়া বা হিসানুন কোন হরফ দিয়ে শুরু?', content: 'ح', options: ['ج', 'خ', 'ح', 'ع'], correctAnswer: 'ح' },
        ],
    },
    'arabic-kha': {
        id: 'arabic-kha', letter: 'خ', word: 'خبز', wordEn: 'Bread', emoji: '🍞',
        color: 'from-amber-400 to-orange-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো খা (خ) শিখি!', voiceText: 'এটি খা। খা দিয়ে হয় খুবজ - মানে রুটি!', content: 'خ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'খুবজ - রুটি', content: 'خبز' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'খা', content: 'خ' },
            { id: 'e4', type: 'tap-correct', title: 'خ কোথায়?', voiceText: 'خ খুঁজে বের করো', content: 'خ', options: ['ح', 'خ', 'د', 'ذ'], correctAnswer: 'خ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'خ বুদবুদ ফাটাও', content: 'خ', options: ['ح', 'خ', 'د', 'ذ'], correctAnswer: 'خ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'خ', options: ['ح', 'خ', 'د', 'ذ'], correctAnswer: 'خ' },
            { id: 'e7', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'خ', options: ['ح-হা', 'خ-খা', 'د-দাল', 'ذ-যাল'], correctAnswer: 'خ' },
            { id: 'e8', type: 'trace', title: 'লিখি — خ', voiceText: 'خ লেখো', content: 'خ' },
            { id: 'e9', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'خ এর নাম কী?', content: 'خ', options: ['হা', 'খা', 'দাল', 'যাল'], correctAnswer: 'খা' },
        ],
    },
    'arabic-dal': {
        id: 'arabic-dal', letter: 'د', word: 'دب', wordEn: 'Bear', emoji: '🐻',
        color: 'from-red-400 to-rose-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো দাল (د) শিখি!', voiceText: 'এটি দাল! দাল দিয়ে হয় দুব্বুন - মানে ভালুক!', content: 'د' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'দুব্বুন - ভালুক', content: 'دب' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'দাল — দুব্বুন', content: 'د' },
            { id: 'e4', type: 'tap-correct', title: 'দাল (د) কোথায়?', voiceText: 'দাল হরফটি খুঁজে বের করো!', content: 'د', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'د' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'দাল হরফের বুদবুদগুলো ফাটাও!', content: 'د', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'د' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'د', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'د' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'د', options: ['ج-جمل', 'ح-حصان', 'خ-خروف', 'د-دب'], correctAnswer: 'د' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'দাল লেখা প্র্যাকটিস করো', content: 'د' },
            { id: 'e9', type: 'quiz', title: 'চমৎকার! শেষ প্রশ্ন', voiceText: 'ভালুক বা দুব্বুন কোন হরফ দিয়ে শুরু?', content: 'د', options: ['ذ', 'د', 'ر', 'ز'], correctAnswer: 'د' },
        ],
    },
    'arabic-dhal': {
        id: 'arabic-dhal', letter: 'ذ', word: 'ذرة', wordEn: 'Corn', emoji: '🌽',
        color: 'from-orange-400 to-amber-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো যাল (ذ) শিখি!', voiceText: 'এটি যাল! যাল দিয়ে হয় যুররাহ - মানে ভুট্টা!', content: 'ذ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'যুররাহ - ভুট্টা', content: 'ذرة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'যাল — যুররাহ', content: 'ذ' },
            { id: 'e4', type: 'tap-correct', title: 'যাল (ذ) কোথায়?', voiceText: 'যাল হরফটি খুঁজে বের করো!', content: 'ذ', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'ذ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'যাল হরফের বুদবুদগুলো ফাটাও!', content: 'ذ', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'ذ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ذ', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'ذ' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ذ', options: ['د-دب', 'ذ-ذرة', 'ر-رمان', 'ز-زرافة'], correctAnswer: 'ذ' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'যাল লেখা প্র্যাকটিস করো', content: 'ذ' },
            { id: 'e9', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'ভুট্টা বা যুররাহ কোন হরফ দিয়ে শুরু?', content: 'ذ', options: ['د', 'ر', 'ذ', 'ز'], correctAnswer: 'ذ' },
        ],
    },
    'arabic-ra': {
        id: 'arabic-ra', letter: 'ر', word: 'رمان', wordEn: 'Pomegranate', emoji: '🍎',
        color: 'from-pink-400 to-rose-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো রা (ر) শিখি!', voiceText: 'এটি রা! রা দিয়ে হয় রুম্মান - মানে ডালিম!', content: 'ر' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'রুম্মান - ডালিম', content: 'رمان' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'রা — রুম্মান', content: 'ر' },
            { id: 'e4', type: 'tap-correct', title: 'রা (ر) কোথায়?', voiceText: 'রা হরফটি খুঁজে বের করো!', content: 'ر', options: ['ز', 'ر', 'س', 'ش'], correctAnswer: 'ر' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'রা হরফের বুদবুদ ফাটাও!', content: 'ر', options: ['ز', 'ر', 'س', 'ش'], correctAnswer: 'ر' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ر', options: ['ز', 'ر', 'س', 'ش'], correctAnswer: 'ر' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ر', options: ['ر-رمان', 'ز-زرافة', 'س-سمكة', 'ش-شمس'], correctAnswer: 'ر' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'রা লেখো', content: 'ر' },
            { id: 'e9', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ডালিম কোন হরফ দিয়ে শুরু?', content: 'ر', options: ['ز', 'س', 'ر', 'ش'], correctAnswer: 'ر' },
        ],
    },
    'arabic-za': {
        id: 'arabic-za', letter: 'ز', word: 'زرافة', wordEn: 'Giraffe', emoji: '🦒',
        color: 'from-lime-400 to-green-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো যা (ز) শিখি!', voiceText: 'এটি যা! যা দিয়ে হয় যিরাফাহ - মানে জিরাফ!', content: 'ز' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'যিরাফাহ - জিরাফ', content: 'زرافة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'যা — যিরাফাহ', content: 'ز' },
            { id: 'e4', type: 'tap-correct', title: 'যা (ز) কোথায়?', voiceText: 'যা হরফটি খুঁজে বের করো!', content: 'ز', options: ['ر', 'ز', 'س', 'ش'], correctAnswer: 'ز' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'যা হরফের বুদবুদ ফাটাও!', content: 'ز', options: ['ر', 'ز', 'س', 'ش'], correctAnswer: 'ز' },
            { id: 'e6', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ز', options: ['ر-رمان', 'ز-زرافة', 'س-سمكة', 'ش-شمس'], correctAnswer: 'ز' },
            { id: 'e7', type: 'trace', title: 'চলো লিখি!', voiceText: 'যা লেখো', content: 'ز' },
            { id: 'e8', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'জিরাফ কোন হরফ দিয়ে শুরু?', content: 'ز', options: ['ر', 'س', 'ز', 'ش'], correctAnswer: 'ز' },
        ],
    },
    'arabic-sin': {
        id: 'arabic-sin', letter: 'س', word: 'سمكة', wordEn: 'Fish', emoji: '🐟',
        color: 'from-cyan-400 to-blue-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো সিন (س) শিখি!', voiceText: 'এটি সিন! সিন দিয়ে হয় সামাকাহ - মানে মাছ!', content: 'س' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'সামাকাহ - মাছ', content: 'سمكة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'সিন — সামাকাহ', content: 'س' },
            { id: 'e4', type: 'tap-correct', title: 'সিন (س) কোথায়?', voiceText: 'সিন হরফটি খুঁজে বের করো!', content: 'س', options: ['ش', 'س', 'ص', 'ض'], correctAnswer: 'س' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'সিন হরফের বুদবুদ ফাটাও!', content: 'س', options: ['ش', 'س', 'ص', 'ض'], correctAnswer: 'س' },
            { id: 'e6', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'س', options: ['س-سمكة', 'ش-شمس', 'ص-صبر', 'ض-ضوء'], correctAnswer: 'س' },
            { id: 'e7', type: 'trace', title: 'চলো লিখি!', voiceText: 'সিন লেখো', content: 'س' },
            { id: 'e8', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'মাছ কোন হরফ দিয়ে শুরু?', content: 'س', options: ['ش', 'ص', 'س', 'ض'], correctAnswer: 'س' },
        ],
    },
    'arabic-shin': {
        id: 'arabic-shin', letter: 'ش', word: 'شمس', wordEn: 'Sun', emoji: '☀️',
        color: 'from-yellow-400 to-orange-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো শিন (ش) শিখি!', voiceText: 'এটি শিন! শিন দিয়ে হয় শামস - মানে সূর্য!', content: 'ش' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'শামস - সূর্য', content: 'شمس' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'শিন — শামস', content: 'ش' },
            { id: 'e4', type: 'tap-correct', title: 'শিন (ش) কোথায়?', voiceText: 'শিন হরফটি খুঁজে বের করো!', content: 'ش', options: ['س', 'ش', 'ص', 'ض'], correctAnswer: 'ش' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'শিন হরফের বুদবুদ ফাটাও!', content: 'ش', options: ['س', 'ش', 'ص', 'ض'], correctAnswer: 'ش' },
            { id: 'e6', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ش', options: ['س-سمكة', 'ش-شمس', 'ص-صبر', 'ض-ضوء'], correctAnswer: 'ش' },
            { id: 'e7', type: 'trace', title: 'চলো লিখি!', voiceText: 'শিন লেখো', content: 'ش' },
            { id: 'e8', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'সূর্য কোন হরফ দিয়ে শুরু?', content: 'ش', options: ['س', 'ص', 'ش', 'ض'], correctAnswer: 'ش' },
        ],
    },
    'arabic-sad': {
        id: 'arabic-sad', letter: 'ص', word: 'صبر', wordEn: 'Patience', emoji: '🤲',
        color: 'from-indigo-400 to-violet-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো সোয়াদ (ص) শিখি!', voiceText: 'এটি সোয়াদ। সোয়াদ দিয়ে হয় সব্র - মানে ধৈর্য!', content: 'ص' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'সব্র - ধৈর্য', content: 'صبر' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'সোয়াদ', content: 'ص' },
            { id: 'e4', type: 'tap-correct', title: 'ص কোথায়?', voiceText: 'ص খুঁজে বের করো', content: 'ص', options: ['س', 'ش', 'ص', 'ض'], correctAnswer: 'ص' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ص বুদবুদ ফাটাও', content: 'ص', options: ['س', 'ش', 'ص', 'ض'], correctAnswer: 'ص' },
            { id: 'e6', type: 'trace', title: 'লিখি — ص', voiceText: 'ص লেখো', content: 'ص' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ص এর নাম কী?', content: 'ص', options: ['সিন', 'শিন', 'সোয়াদ', 'দোয়াদ'], correctAnswer: 'সোয়াদ' },
        ],
    },
    'arabic-dad': {
        id: 'arabic-dad', letter: 'ض', word: 'ضوء', wordEn: 'Light', emoji: '💡',
        color: 'from-amber-300 to-yellow-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো দোয়াদ (ض) শিখি!', voiceText: 'এটি দোয়াদ। দোয়াদ দিয়ে হয় দাউ - মানে আলো!', content: 'ض' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'দাউ - আলো', content: 'ضوء' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'দোয়াদ', content: 'ض' },
            { id: 'e4', type: 'tap-correct', title: 'ض কোথায়?', voiceText: 'ض খুঁজে বের করো', content: 'ض', options: ['ص', 'ض', 'ط', 'ظ'], correctAnswer: 'ض' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ض বুদবুদ ফাটাও', content: 'ض', options: ['ص', 'ض', 'ط', 'ظ'], correctAnswer: 'ض' },
            { id: 'e6', type: 'trace', title: 'লিখি — ض', voiceText: 'ض লেখো', content: 'ض' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ض এর নাম কী?', content: 'ض', options: ['সোয়াদ', 'দোয়াদ', 'তোয়া', 'যোয়া'], correctAnswer: 'দোয়াদ' },
        ],
    },
    'arabic-ta2': {
        id: 'arabic-ta2', letter: 'ط', word: 'طبيب', wordEn: 'Doctor', emoji: '🩺',
        color: 'from-sky-400 to-indigo-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো তোয়া (ط) শিখি!', voiceText: 'এটি তোয়া। তোয়া দিয়ে হয় তবীব - মানে ডাক্তার!', content: 'ط' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'তবীব - ডাক্তার', content: 'طبيب' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'তোয়া', content: 'ط' },
            { id: 'e4', type: 'tap-correct', title: 'ط কোথায়?', voiceText: 'ط খুঁজে বের করো', content: 'ط', options: ['ض', 'ط', 'ظ', 'ع'], correctAnswer: 'ط' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ط বুদবুদ ফাটাও', content: 'ط', options: ['ض', 'ط', 'ظ', 'ع'], correctAnswer: 'ط' },
            { id: 'e6', type: 'trace', title: 'লিখি — ط', voiceText: 'ط লেখো', content: 'ط' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ط এর নাম কী?', content: 'ط', options: ['দোয়াদ', 'তোয়া', 'যোয়া', 'আইন'], correctAnswer: 'তোয়া' },
        ],
    },
}
