import type { LessonConfig } from '@/components/kids/LessonEngine'

export const arabicLessonsPart1: Record<string, LessonConfig> = {
    'arabic-alif': {
        id: 'arabic-alif', letter: 'ا', word: 'أسد', wordEn: 'Lion', emoji: '🦁',
        color: 'from-emerald-400 to-teal-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আলিফ (ا) শিখি!', voiceText: 'এটি হলো আলিফ। আলিফ দিয়ে হয় আসাদুন - মানে সিংহ!', content: 'ا' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'আসাদুন - সিংহ', content: 'أسد' },
            { id: 'e3', type: 'pronounce', title: 'এবার তুমি বলো!', voiceText: 'আলিফ — আসাদুন', content: 'ا' },
            { id: 'e4', type: 'tap-correct', title: 'আলিফ (ا) কোথায়?', voiceText: 'আলিফ হরফটি খুঁজে বের করো!', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'আলিফ হরফের বুদবুদগুলো ফাটাও!', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'আলিফ হরফটি চিনতে পেরেছ?', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে সঠিক শব্দটি মিলিয়ে দাও', content: 'ا', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ا' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'আলিফ লেখা প্র্যাকটিস করো', content: 'ا' },
            { id: 'e9', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'সিংহ বা আসাদুন কোন হরফ দিয়ে শুরু হয়?', content: 'ا', options: ['ب', 'ا', 'ت', 'ث'], correctAnswer: 'ا' },
        ],
    },
    'arabic-ba': {
        id: 'arabic-ba', letter: 'ب', word: 'بطة', wordEn: 'Duck', emoji: '🦆',
        color: 'from-blue-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো বা (ب) শিখি!', voiceText: 'এটি বা! বা দিয়ে হয় বত্বাতুন - মানে হাঁস!', content: 'ب' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'বত্বাতুন - হাঁস', content: 'بطة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'বা — বত্বাতুন', content: 'ب' },
            { id: 'e4', type: 'tap-correct', title: 'বা (ب) কোথায়?', voiceText: 'বা হরফটি খুঁজে বের করো!', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'বা হরফের বুদবুদগুলো ফাটাও!', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ب', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ب' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'বা লেখা প্র্যাকটিস করো', content: 'ب' },
            { id: 'e9', type: 'quiz', title: 'চমৎকার! শেষ প্রশ্ন', voiceText: 'হাঁস বা বত্বাতুন কোন হরফ দিয়ে শুরু হয়?', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
        ],
    },
    'arabic-ta': {
        id: 'arabic-ta', letter: 'ت', word: 'تفاح', wordEn: 'Apple', emoji: '🍎',
        color: 'from-rose-400 to-pink-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো তা (ت) শিখি!', voiceText: 'এটি তা! তা দিয়ে হয় তুফফাহুন - মানে আপেল!', content: 'ت' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'তুফফাহুন - আপেল', content: 'تفاح' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'তা — তুফফাহুন', content: 'ت' },
            { id: 'e4', type: 'tap-correct', title: 'তা (ت) কোথায়?', voiceText: 'তা হরফটি খুঁজে বের করো!', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'তা হরফের বুদবুদগুলো ফাটাও!', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e7', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ت', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ت' },
            { id: 'e8', type: 'trace', title: 'চলো লিখি!', voiceText: 'তা লেখা প্র্যাকটিস করো', content: 'ت' },
            { id: 'e9', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'আপেল বা তুফফাহুন কোন হরফ দিয়ে শুরু হয়?', content: 'ت', options: ['ب', 'ث', 'ت', 'ن'], correctAnswer: 'ت' },
        ],
    },
    'arabic-tha': {
        id: 'arabic-tha', letter: 'ث', word: 'ثلج', wordEn: 'Snow', emoji: '❄️',
        color: 'from-sky-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো ছা (ث) শিখি!', voiceText: 'এটি ছা। ছা দিয়ে হয় থালজ - মানে বরফ!', content: 'ث' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'থালজ - বরফ', content: 'ثلج' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ছা', content: 'ث' },
            { id: 'e4', type: 'tap-correct', title: 'ث কোথায়?', voiceText: 'ث খুঁজে বের করো', content: 'ث', options: ['ت', 'ث', 'ج', 'ح'], correctAnswer: 'ث' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ث বুদবুদ ফাটাও', content: 'ث', options: ['ت', 'ث', 'ج', 'ح'], correctAnswer: 'ث' },
            { id: 'e6', type: 'trace', title: 'লিখি — ث', voiceText: 'ث লেখো', content: 'ث' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ث এর নাম কী?', content: 'ث', options: ['তা', 'ছা', 'জিম', 'হা'], correctAnswer: 'ছা' },
        ],
    },
    'arabic-jeem': {
        id: 'arabic-jeem', letter: 'ج', word: 'جمل', wordEn: 'Camel', emoji: '🐪',
        color: 'from-violet-400 to-purple-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো জীম (ج) শিখি!', voiceText: 'এটি জীম! জীম দিয়ে হয় জামাালুন - মানে উট!', content: 'ج' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'জামাালুন - উট', content: 'جمل' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'জীম — জামাালুন', content: 'ج' },
            { id: 'e4', type: 'tap-correct', title: 'জীম (ج) কোথায়?', voiceText: 'জীম হরফটি খুঁজে বের করো!', content: 'ج', options: ['ح', 'ج', 'خ', 'ع'], correctAnswer: 'ج' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'জীম হরফের বুদবুদগুলো ফাটাও!', content: 'ج', options: ['ح', 'ج', 'خ', 'ع'], correctAnswer: 'ج' },
            { id: 'e6', type: 'trace', title: 'চলো লিখি!', voiceText: 'জীম লেখা প্র্যাকটিস করো', content: 'ج' },
            { id: 'e7', type: 'quiz', title: 'অনেক ভালো! শেষ প্রশ্ন', voiceText: 'উট বা জামাালুন কোন হরফ দিয়ে শুরু?', content: 'ج', options: ['ح', 'خ', 'ج', 'ع'], correctAnswer: 'ج' },
        ],
    },
    'arabic-ha': {
        id: 'arabic-ha', letter: 'ح', word: 'حصان', wordEn: 'Horse', emoji: '🐴',
        color: 'from-teal-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো হা (ح) শিখি!', voiceText: 'এটি হা! হা দিয়ে হয় হিসানুন - মানে ঘোড়া!', content: 'ح' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'হিসানুন - ঘোড়া', content: 'حصان' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'হা — হিসানুন', content: 'ح' },
            { id: 'e4', type: 'tap-correct', title: 'হা (ح) কোথায়?', voiceText: 'হা হরফটি খুঁজে বের করো!', content: 'ح', options: ['ج', 'ح', 'خ', 'ع'], correctAnswer: 'ح' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'হা হরফের বুদবুদগুলো ফাটাও!', content: 'ح', options: ['ج', 'ح', 'خ', 'ع'], correctAnswer: 'ح' },
            { id: 'e6', type: 'trace', title: 'চলো লিখি!', voiceText: 'হা লেখা প্র্যাকটিস করো', content: 'ح' },
            { id: 'e7', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'ঘোড়া বা হিসানুন কোন হরফ দিয়ে শুরু?', content: 'ح', options: ['ج', 'خ', 'ح', 'ع'], correctAnswer: 'ح' },
        ],
    },
    'arabic-kha': {
        id: 'arabic-kha', letter: 'خ', word: 'خبز', wordEn: 'Bread', emoji: '🍞',
        color: 'from-amber-400 to-orange-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো খা (خ) শিখি!', voiceText: 'এটি খা। খা দিয়ে হয় খুবজ - মানে রুটি!', content: 'خ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'খুবজ - রুটি', content: 'خبز' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'খা', content: 'خ' },
            { id: 'e4', type: 'tap-correct', title: 'خ কোথায়?', voiceText: 'خ খুঁজে বের করো', content: 'خ', options: ['ح', 'خ', 'د', 'ذ'], correctAnswer: 'خ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'خ বুদবুদ ফাটাও', content: 'خ', options: ['ح', 'خ', 'د', 'ذ'], correctAnswer: 'خ' },
            { id: 'e6', type: 'trace', title: 'লিখি — خ', voiceText: 'خ লেখো', content: 'خ' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'خ এর নাম কী?', content: 'خ', options: ['হা', 'খা', 'দাল', 'যাল'], correctAnswer: 'খা' },
        ],
    },
    'arabic-dal': {
        id: 'arabic-dal', letter: 'د', word: 'دب', wordEn: 'Bear', emoji: '🐻',
        color: 'from-red-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো দাল (د) শিখি!', voiceText: 'এটি দাল! দাল দিয়ে হয় দুব্বুন - মানে ভালুক!', content: 'د' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'দুব্বুন - ভালুক', content: 'دب' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'দাল — দুব্বুন', content: 'د' },
            { id: 'e4', type: 'tap-correct', title: 'দাল (د) কোথায়?', voiceText: 'দাল হরফটি খুঁজে বের করো!', content: 'د', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'د' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'দাল হরফের বুদবুদগুলো ফাটাও!', content: 'د', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'د' },
            { id: 'e6', type: 'trace', title: 'চলো লিখি!', voiceText: 'দাল লেখা প্র্যাকটিস করো', content: 'د' },
            { id: 'e7', type: 'quiz', title: 'চমৎকার! শেষ প্রশ্ন', voiceText: 'ভালুক বা দুব্বুন কোন হরফ দিয়ে শুরু?', content: 'د', options: ['ذ', 'د', 'ر', 'ز'], correctAnswer: 'د' },
        ],
    },
}
