import type { LessonConfig } from '@/components/kids/LessonEngine'

export const arabicLessonsPart2: Record<string, LessonConfig> = {
    'arabic-zha': {
        id: 'arabic-zha', letter: 'ظ', word: 'ظهر', wordEn: 'Back', emoji: '🔙',
        color: 'from-indigo-400 to-violet-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো যোয়া (ظ) শিখি!', voiceText: 'এটি যোয়া।', content: 'ظ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'যোয়া', content: 'ظ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'যোয়া', content: 'ظ' },
            { id: 'e4', type: 'tap-correct', title: 'ظ কোথায়?', voiceText: 'ظ খুঁজে বের করো', content: 'ظ', options: ['ط', 'ظ', 'ع', 'غ'], correctAnswer: 'ظ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ظ বুদবুদ ফাটাও', content: 'ظ', options: ['ط', 'ظ', 'ع', 'غ'], correctAnswer: 'ظ' },
            { id: 'e6', type: 'trace', title: 'লিখি — ظ', voiceText: 'ظ লেখো', content: 'ظ' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ظ এর নাম কী?', content: 'ظ', options: ['তোয়া', 'যোয়া', 'আইন', 'গাইন'], correctAnswer: 'যোয়া' },
        ],
    },
    'arabic-ain': {
        id: 'arabic-ain', letter: 'ع', word: 'عين', wordEn: 'Eye', emoji: '👁️',
        color: 'from-emerald-400 to-green-600', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আইন (ع) শিখি!', voiceText: 'এটি আইন। আইন দিয়ে হয় আইন - মানে চোখ!', content: 'ع' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'আইন - চোখ', content: 'عين' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'আইন', content: 'ع' },
            { id: 'e4', type: 'tap-correct', title: 'ع কোথায়?', voiceText: 'ع খুঁজে বের করো', content: 'ع', options: ['غ', 'ع', 'ف', 'ق'], correctAnswer: 'ع' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ع বুদবুদ ফাটাও', content: 'ع', options: ['غ', 'ع', 'ف', 'ق'], correctAnswer: 'ع' },
            { id: 'e6', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ع', options: ['ع-عين', 'غ-غيم', 'ف-فيل', 'ق-قلم'], correctAnswer: 'ع' },
            { id: 'e7', type: 'trace', title: 'লিখি — ع', voiceText: 'ع লেখো', content: 'ع' },
            { id: 'e8', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'চোখ কোন হরফ দিয়ে শুরু?', content: 'ع', options: ['غ', 'ف', 'ع', 'ق'], correctAnswer: 'ع' },
        ],
    },
    'arabic-ghain': {
        id: 'arabic-ghain', letter: 'غ', word: 'غيم', wordEn: 'Cloud', emoji: '☁️',
        color: 'from-slate-400 to-gray-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো গাইন (غ) শিখি!', voiceText: 'এটি গাইন। গাইন দিয়ে হয় গাইম - মানে মেঘ!', content: 'غ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'গাইম - মেঘ', content: 'غيم' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'গাইন', content: 'غ' },
            { id: 'e4', type: 'tap-correct', title: 'غ কোথায়?', voiceText: 'غ খুঁজে বের করো', content: 'غ', options: ['ع', 'غ', 'ف', 'ق'], correctAnswer: 'غ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'غ বুদবুদ ফাটাও', content: 'غ', options: ['ع', 'غ', 'ف', 'ق'], correctAnswer: 'غ' },
            { id: 'e6', type: 'trace', title: 'লিখি — غ', voiceText: 'غ লেখো', content: 'غ' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'غ এর নাম কী?', content: 'غ', options: ['আইন', 'গাইন', 'ফা', 'কাফ'], correctAnswer: 'গাইন' },
        ],
    },
    'arabic-fa': {
        id: 'arabic-fa', letter: 'ف', word: 'فيل', wordEn: 'Elephant', emoji: '🐘',
        color: 'from-violet-400 to-purple-600', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো ফা (ف) শিখি!', voiceText: 'এটি ফা। ফা দিয়ে হয় ফীল - মানে হাতি!', content: 'ف' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'ফীল - হাতি', content: 'فيل' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ফা — ফীল', content: 'ف' },
            { id: 'e4', type: 'tap-correct', title: 'ف কোথায়?', voiceText: 'ف খুঁজে বের করো', content: 'ف', options: ['ق', 'ف', 'ك', 'ل'], correctAnswer: 'ف' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ف বুদবুদ ফাটাও', content: 'ف', options: ['ق', 'ف', 'ك', 'ل'], correctAnswer: 'ف' },
            { id: 'e6', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ف', options: ['ف-فيل', 'ق-قلم', 'ك-كتاب', 'ل-لبن'], correctAnswer: 'ف' },
            { id: 'e7', type: 'trace', title: 'লিখি — ف', voiceText: 'ف লেখো', content: 'ف' },
            { id: 'e8', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'হাতি কোন হরফ দিয়ে শুরু?', content: 'ف', options: ['ق', 'ك', 'ف', 'ل'], correctAnswer: 'ف' },
        ],
    },
    'arabic-qaf': {
        id: 'arabic-qaf', letter: 'ق', word: 'قلم', wordEn: 'Pen', emoji: '🖊️',
        color: 'from-blue-400 to-indigo-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো কাফ (ق) শিখি!', voiceText: 'এটি কাফ। কাফ দিয়ে হয় কলম - মানে কলম!', content: 'ق' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'কলম - কলম', content: 'قلم' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'কাফ', content: 'ق' },
            { id: 'e4', type: 'tap-correct', title: 'ق কোথায়?', voiceText: 'ق খুঁজে বের করো', content: 'ق', options: ['ف', 'ق', 'ك', 'ل'], correctAnswer: 'ق' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ق বুদবুদ ফাটাও', content: 'ق', options: ['ف', 'ق', 'ك', 'ل'], correctAnswer: 'ق' },
            { id: 'e6', type: 'trace', title: 'লিখি — ق', voiceText: 'ق লেখো', content: 'ق' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ق এর নাম কী?', content: 'ق', options: ['ফা', 'কাফ', 'কাফ (ك)', 'লাম'], correctAnswer: 'কাফ' },
        ],
    },
    'arabic-kaf': {
        id: 'arabic-kaf', letter: 'ك', word: 'كتاب', wordEn: 'Book', emoji: '📖',
        color: 'from-amber-400 to-orange-600', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো কাফ (ك) শিখি!', voiceText: 'এটি কাফ। কাফ দিয়ে হয় কিতাব - মানে বই!', content: 'ك' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'কিতাব - বই', content: 'كتاب' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'কাফ — কিতাব', content: 'ك' },
            { id: 'e4', type: 'tap-correct', title: 'ك কোথায়?', voiceText: 'ك খুঁজে বের করো', content: 'ك', options: ['ق', 'ك', 'ل', 'م'], correctAnswer: 'ك' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ك বুদবুদ ফাটাও', content: 'ك', options: ['ق', 'ك', 'ل', 'م'], correctAnswer: 'ك' },
            { id: 'e6', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ك', options: ['ك-كتاب', 'ل-لبن', 'م-ماء', 'ن-نار'], correctAnswer: 'ك' },
            { id: 'e7', type: 'trace', title: 'লিখি — ك', voiceText: 'ك লেখো', content: 'ك' },
            { id: 'e8', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'বই কোন হরফ দিয়ে শুরু?', content: 'ك', options: ['ق', 'ل', 'ك', 'م'], correctAnswer: 'ك' },
        ],
    },
    'arabic-lam': {
        id: 'arabic-lam', letter: 'ل', word: 'لبن', wordEn: 'Milk', emoji: '🥛',
        color: 'from-cyan-300 to-sky-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো লাম (ل) শিখি!', voiceText: 'এটি লাম। লাম দিয়ে হয় লাবান - মানে দুধ!', content: 'ل' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'লাবান - দুধ', content: 'لبن' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'লাম', content: 'ل' },
            { id: 'e4', type: 'tap-correct', title: 'ل কোথায়?', voiceText: 'ل খুঁজে বের করো', content: 'ل', options: ['ك', 'ل', 'م', 'ن'], correctAnswer: 'ل' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ل বুদবুদ ফাটাও', content: 'ل', options: ['ك', 'ل', 'م', 'ن'], correctAnswer: 'ل' },
            { id: 'e6', type: 'trace', title: 'লিখি — ل', voiceText: 'ل লেখো', content: 'ل' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ل এর নাম কী?', content: 'ل', options: ['কাফ', 'লাম', 'মিম', 'নুন'], correctAnswer: 'লাম' },
        ],
    },
    'arabic-mim': {
        id: 'arabic-mim', letter: 'م', word: 'ماء', wordEn: 'Water', emoji: '💧',
        color: 'from-blue-300 to-cyan-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো মিম (م) শিখি!', voiceText: 'এটি মিম। মিম দিয়ে হয় মা - মানে পানি!', content: 'م' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'মা - পানি', content: 'ماء' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'মিম', content: 'م' },
            { id: 'e4', type: 'tap-correct', title: 'م কোথায়?', voiceText: 'م খুঁজে বের করো', content: 'م', options: ['ل', 'م', 'ن', 'ه'], correctAnswer: 'م' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'م বুদবুদ ফাটাও', content: 'م', options: ['ل', 'م', 'ن', 'ه'], correctAnswer: 'م' },
            { id: 'e6', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'م', options: ['م-ماء', 'ن-نار', 'ه-هلال', 'و-ورد'], correctAnswer: 'م' },
            { id: 'e7', type: 'trace', title: 'লিখি — م', voiceText: 'م লেখো', content: 'م' },
            { id: 'e8', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'পানি কোন হরফ দিয়ে শুরু?', content: 'م', options: ['ن', 'ه', 'م', 'و'], correctAnswer: 'م' },
        ],
    },
    'arabic-nun': {
        id: 'arabic-nun', letter: 'ن', word: 'نار', wordEn: 'Fire', emoji: '🔥',
        color: 'from-orange-400 to-red-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো নুন (ن) শিখি!', voiceText: 'এটি নুন। নুন দিয়ে হয় নার - মানে আগুন!', content: 'ن' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'নার - আগুন', content: 'نار' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'নুন', content: 'ن' },
            { id: 'e4', type: 'tap-correct', title: 'ن কোথায়?', voiceText: 'ن খুঁজে বের করো', content: 'ن', options: ['م', 'ن', 'ه', 'و'], correctAnswer: 'ن' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ن বুদবুদ ফাটাও', content: 'ن', options: ['م', 'ن', 'ه', 'و'], correctAnswer: 'ن' },
            { id: 'e6', type: 'trace', title: 'লিখি — ن', voiceText: 'ن লেখো', content: 'ن' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ن এর নাম কী?', content: 'ن', options: ['মিম', 'নুন', 'হা', 'ওয়াও'], correctAnswer: 'নুন' },
        ],
    },
    'arabic-ha2': {
        id: 'arabic-ha2', letter: 'ه', word: 'هلال', wordEn: 'Crescent', emoji: '🌙',
        color: 'from-indigo-400 to-blue-600', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো হা (ه) শিখি!', voiceText: 'এটি হা। হা দিয়ে হয় হিলাল - মানে চাঁদ!', content: 'ه' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'হিলাল - চাঁদ', content: 'هلال' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'হা', content: 'ه' },
            { id: 'e4', type: 'tap-correct', title: 'ه কোথায়?', voiceText: 'ه খুঁজে বের করো', content: 'ه', options: ['ن', 'ه', 'و', 'ي'], correctAnswer: 'ه' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ه বুদবুদ ফাটাও', content: 'ه', options: ['ن', 'ه', 'و', 'ي'], correctAnswer: 'ه' },
            { id: 'e6', type: 'trace', title: 'লিখি — ه', voiceText: 'ه লেখো', content: 'ه' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ه এর নাম কী?', content: 'ه', options: ['নুন', 'হা', 'ওয়াও', 'ইয়া'], correctAnswer: 'হা' },
        ],
    },
    'arabic-waw': {
        id: 'arabic-waw', letter: 'و', word: 'ورد', wordEn: 'Rose', emoji: '🌹',
        color: 'from-rose-400 to-red-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো ওয়াও (و) শিখি!', voiceText: 'এটি ওয়াও। ওয়াও দিয়ে হয় ওয়ার্দ - মানে গোলাপ!', content: 'و' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'ওয়ার্দ - গোলাপ', content: 'ورد' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ওয়াও', content: 'و' },
            { id: 'e4', type: 'tap-correct', title: 'و কোথায়?', voiceText: 'و খুঁজে বের করো', content: 'و', options: ['ه', 'و', 'ي', 'ا'], correctAnswer: 'و' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'و বুদবুদ ফাটাও', content: 'و', options: ['ه', 'و', 'ي', 'ا'], correctAnswer: 'و' },
            { id: 'e6', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'و', options: ['و-ورد', 'ي-يد', 'ه-هلال', 'ن-نار'], correctAnswer: 'و' },
            { id: 'e7', type: 'trace', title: 'লিখি — و', voiceText: 'و লেখো', content: 'و' },
            { id: 'e8', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'গোলাপ কোন হরফ দিয়ে শুরু?', content: 'و', options: ['ه', 'ي', 'و', 'ا'], correctAnswer: 'و' },
        ],
    },
    'arabic-ya': {
        id: 'arabic-ya', letter: 'ي', word: 'يد', wordEn: 'Hand', emoji: '✋',
        color: 'from-yellow-400 to-amber-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো ইয়া (ي) শিখি!', voiceText: 'এটি ইয়া। ইয়া দিয়ে হয় ইয়াদ - মানে হাত!', content: 'ي' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'ইয়াদ - হাত', content: 'يد' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ইয়া', content: 'ي' },
            { id: 'e4', type: 'tap-correct', title: 'ي কোথায়?', voiceText: 'ي খুঁজে বের করো', content: 'ي', options: ['و', 'ي', 'ا', 'ب'], correctAnswer: 'ي' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ي বুদবুদ ফাটাও', content: 'ي', options: ['و', 'ي', 'ا', 'ب'], correctAnswer: 'ي' },
            { id: 'e6', type: 'trace', title: 'লিখি — ي', voiceText: 'ي লেখো', content: 'ي' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ي এর নাম কী?', content: 'ي', options: ['ওয়াও', 'ইয়া', 'আলিফ', 'বা'], correctAnswer: 'ইয়া' },
        ],
    },
    'arabic-fatha': {
        id: 'arabic-fatha', letter: 'فَ', word: 'ফাতহা', wordEn: 'Fatha', emoji: '✨',
        color: 'from-rose-400 to-pink-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো যবর (فَ) শিখি!', voiceText: 'এটি যবর বা ফাতহা।', content: 'فَ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'ফাতহা', content: 'فَ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'যবর', content: 'فَ' },
            { id: 'e4', type: 'tap-correct', title: 'যবর কোথায়?', voiceText: 'যবর খুঁজে বের করো', content: 'فَ', options: ['فَ', 'فِ', 'فُ', 'ا'], correctAnswer: 'فَ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'যবর ফাটাও', content: 'فَ', options: ['فَ', 'فِ', 'فُ', 'ب'], correctAnswer: 'فَ' },
            { id: 'e6', type: 'trace', title: 'লিখি — فَ', voiceText: 'فَ লেখো', content: 'فَ' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'যবর কোনটি?', content: 'فَ', options: ['فَ', 'فِ', 'فُ', 'م'], correctAnswer: 'فَ' },
        ],
    },
    'arabic-kasra': {
        id: 'arabic-kasra', letter: 'فِ', word: 'কাসরা', wordEn: 'Kasra', emoji: '✨',
        color: 'from-blue-400 to-cyan-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো যের (فِ) শিখি!', voiceText: 'এটি যের বা কাসরা।', content: 'فِ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'কাসরা', content: 'فِ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'যের', content: 'فِ' },
            { id: 'e4', type: 'tap-correct', title: 'যের কোথায়?', voiceText: 'যের খুঁজে বের করো', content: 'فِ', options: ['فَ', 'فِ', 'فُ', 'ا'], correctAnswer: 'فِ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'যের ফাটাও', content: 'فِ', options: ['فَ', 'فِ', 'فُ', 'ب'], correctAnswer: 'فِ' },
            { id: 'e6', type: 'trace', title: 'লিখি — فِ', voiceText: 'فِ লেখো', content: 'فِ' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'যের কোনটি?', content: 'فِ', options: ['فَ', 'فِ', 'فُ', 'م'], correctAnswer: 'فِ' },
        ],
    },
    'arabic-damma': {
        id: 'arabic-damma', letter: 'فُ', word: 'দাম্মা', wordEn: 'Damma', emoji: '✨',
        color: 'from-violet-400 to-purple-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো পেশ (فُ) শিখি!', voiceText: 'এটি পেশ বা দাম্মা।', content: 'فُ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'দাম্মা', content: 'فُ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'পেশ', content: 'فُ' },
            { id: 'e4', type: 'tap-correct', title: 'পেশ কোথায়?', voiceText: 'পেশ খুঁজে বের করো', content: 'فُ', options: ['فَ', 'فِ', 'فُ', 'ا'], correctAnswer: 'فُ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'পেশ ফাটাও', content: 'فُ', options: ['فَ', 'فِ', 'فُ', 'ب'], correctAnswer: 'فُ' },
            { id: 'e6', type: 'trace', title: 'লিখি — فُ', voiceText: 'فُ লেখো', content: 'فُ' },
            { id: 'e7', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'পেশ কোনটি?', content: 'فُ', options: ['فَ', 'فِ', 'فُ', 'م'], correctAnswer: 'فُ' },
        ],
    },
}
