'use client'

import { useParams } from 'next/navigation'
import LessonEngine, { LessonConfig } from '@/components/kids/LessonEngine'

const lessons: Record<string, LessonConfig> = {
    'arabic-alif': {
        id: 'arabic-alif', letter: ' এটি হলো আলিফ ا', word: 'أسد - আলিফ দিয়ে হয় আসাদুন - মানে সিংহ!', wordEn: 'Lion', emoji: '🦁',
        color: 'from-emerald-400 to-teal-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আলিফ (ا) শিখি!', voiceText: 'এটি হলো আলিফ। আলিফ দিয়ে হয় আসাদুন - মানে সিংহ!', content: 'ا' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'আসাদুন - সিংহ', content: 'أسد' },
            { id: 'e3', type: 'pronounce', title: 'এবার তুমি বলো!', voiceText: 'আলিফ — আসাদুন', content: 'ا' },
            { id: 'e4', type: 'tap-correct', title: 'আলিফ (ا) কোথায়?', voiceText: 'আলিফ হরফটি খুঁজে বের করো !', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'আলিফ হরফের বুদবুদগুলো ফাটাও!', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'আলিফ হরফটি চিনতে পেরেছ?', content: 'ا', options: ['ا', 'ب', 'ت', 'ث'], correctAnswer: 'ا' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে সঠিক শব্দটি মিলিয়ে দাও', content: 'ا', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ا' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'আলিফ লেখা প্র্যাকটিস করো', content: 'ا' },
            { id: 'e10', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'সিংহ বা আসাদুন কোন হরফ দিয়ে শুরু হয়?', content: 'ا', options: ['ب', 'ا', 'ت', 'ث'], correctAnswer: 'ا' },
        ],
    },
    'arabic-ba': {
        id: 'arabic-ba', letter: ' -এটি বা ب', word: 'بطة - বা দিয়ে হয় বত্বাতুন - মানে হাঁস!', wordEn: 'Duck', emoji: '🦆',
        color: 'from-blue-400 to-cyan-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো বা (ب) শিখি!', voiceText: 'এটি বা! বা দিয়ে হয় বত্বাতুন - মানে হাঁস!', content: 'ب' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'বত্বাতুন - হাঁস', content: 'بطة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'বা — বত্বাতুন', content: 'ب' },
            { id: 'e4', type: 'tap-correct', title: 'বা (ب) কোথায়?', voiceText: 'বা হরফটি খুঁজে বের করো তো!', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'বা হরফের বুদবুদগুলো ফাটাও!', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ب', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ب' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'বা লেখা প্র্যাকটিস করো', content: 'ب' },
            { id: 'e10', type: 'quiz', title: 'চমৎকার! শেষ প্রশ্ন', voiceText: 'হাঁস বা বত্বাতুন কোন হরফ দিয়ে শুরু হয়?', content: 'ب', options: ['ا', 'ب', 'ن', 'ي'], correctAnswer: 'ب' },
        ],
    },
    'arabic-ta': {
        id: 'arabic-ta', letter: ' -এটি তা!ت', word: 'تفاح - তা দিয়ে হয় তুফফাহুন - মানে আপেল!', wordEn: 'Apple', emoji: '🍎',
        color: 'from-rose-400 to-pink-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো তা (ت) শিখি!', voiceText: 'এটি তা! তা দিয়ে হয় তুফফাহুন - মানে আপেল!', content: 'ت' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'তুফফাহুন - আপেল', content: 'تفاح' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'তা — তুফফাহুন', content: 'ت' },
            { id: 'e4', type: 'tap-correct', title: 'তা (ت) কোথায়?', voiceText: 'তা হরফটি খুঁজে বের করো তো!', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'তা হরফের বুদবুদগুলো ফাটাও!', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ت', options: ['ب', 'ت', 'ث', 'ن'], correctAnswer: 'ت' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ت', options: ['ا-أسد', 'ب-بطة', 'ت-تفاح', 'ث-ثعلب'], correctAnswer: 'ت' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'তা লেখা প্র্যাকটিস করো', content: 'ت' },
            { id: 'e10', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'আপেল বা তুফফাহুন কোন হরফ দিয়ে শুরু হয়?', content: 'ت', options: ['ب', 'ث', 'ت', 'ن'], correctAnswer: 'ت' },
        ],
    },
    'arabic-tha': {
        id: 'arabic-tha', letter: 'ث', word: 'ثَلْج', wordEn: 'Snow', emoji: '❄️',
        color: 'from-sky-400 to-blue-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ث — ছা', content: 'ث' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ثَلْج', voiceText: 'ثَلْج', content: 'ثَلْج' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ث', content: 'ث' },
            { id: 'e4', type: 'tap-correct', title: 'ث কোথায়?', voiceText: 'ث খুঁজে বের করো', content: 'ث', options: ['ت', 'ث', 'ج', 'ح'], correctAnswer: 'ث' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ث বুদবুদ ফাটাও', content: 'ث', options: ['ت', 'ث', 'ج', 'ح'], correctAnswer: 'ث' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ث', options: ['ت', 'ث', 'ج', 'ح'], correctAnswer: 'ث' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ث', options: ['ت-তা', 'ث-ছা', 'ج-জিম', 'ح-হা'], correctAnswer: 'ث' },
            { id: 'e10', type: 'trace', title: 'লিখি — ث', voiceText: 'ث লেখো', content: 'ث' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ث এর নাম কী?', content: 'ث', options: ['তা', 'ছা', 'জিম', 'হা'], correctAnswer: 'ছা' },
        ],
    },
    'arabic-jeem': {
        id: 'arabic-jeem', letter: ' ج - এটি জীম!', word: 'جمل - জীম দিয়ে হয় জামাালুন - মানে উট!', wordEn: 'Camel', emoji: '🐪',
        color: 'from-violet-400 to-purple-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো জীম (ج) শিখি!', voiceText: 'এটি জীম! জীম দিয়ে হয় জামাালুন - মানে উট!', content: 'ج' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'জামাালুন - উট', content: 'جمل' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'জীম — জামাালুন', content: 'ج' },
            { id: 'e4', type: 'tap-correct', title: 'জীম (ج) কোথায়?', voiceText: 'জীম হরফটি খুঁজে বের করো!', content: 'ج', options: ['ح', 'ج', 'خ', 'ع'], correctAnswer: 'ج' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'জীম হরফের বুদবুদগুলো ফাটাও!', content: 'ج', options: ['ح', 'ج', 'خ', 'ع'], correctAnswer: 'ج' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ج', options: ['ح', 'ج', 'خ', 'ع'], correctAnswer: 'ج' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ج', options: ['ج-جمل', 'ح-حصان', 'خ-خروف', 'د-دب'], correctAnswer: 'ج' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'জীম লেখা প্র্যাকটিস করো', content: 'ج' },
            { id: 'e10', type: 'quiz', title: 'অনেক ভালো! শেষ প্রশ্ন', voiceText: 'উট বা জামাালুন কোন হরফ দিয়ে শুরু?', content: 'ج', options: ['ح', 'خ', 'ج', 'ع'], correctAnswer: 'ج' },
        ],
    },
    'arabic-ha': {
        id: 'arabic-ha', letter: ' ح - এটি হা!', word: 'حصان - হা দিয়ে হয় হিসানুন - মানে ঘোড়া!', wordEn: 'Horse', emoji: '🐴',
        color: 'from-teal-400 to-cyan-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো হা (ح) শিখি!', voiceText: 'এটি হা! হা দিয়ে হয় হিসানুন - মানে ঘোড়া!', content: 'ح' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'হিসানুন - ঘোড়া', content: 'حصان' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'হা — হিসানুন', content: 'ح' },
            { id: 'e4', type: 'tap-correct', title: 'হা (ح) কোথায়?', voiceText: 'হা হরফটি খুঁজে বের করো!', content: 'ح', options: ['ج', 'ح', 'خ', 'ع'], correctAnswer: 'ح' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'হা হরফের বুদবুদগুলো ফাটাও!', content: 'ح', options: ['ج', 'ح', 'خ', 'ع'], correctAnswer: 'ح' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ح', options: ['ج', 'ح', 'خ', 'ع'], correctAnswer: 'ح' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ح', options: ['ج-جمل', 'ح-حصان', 'خ-خروف', 'د-دب'], correctAnswer: 'ح' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'হা লেখা প্র্যাকটিস করো', content: 'ح' },
            { id: 'e10', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'ঘোড়া বা হিসানুন কোন হরফ দিয়ে শুরু?', content: 'ح', options: ['ج', 'خ', 'ح', 'ع'], correctAnswer: 'ح' },
        ],
    },
    'arabic-kha': {
        id: 'arabic-kha', letter: 'خ', word: 'خُبْز', wordEn: 'Bread', emoji: '🍞',
        color: 'from-amber-400 to-orange-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'خ — খা', content: 'خ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — خُبْز', voiceText: 'خُبْز', content: 'خُبْز' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'خ', content: 'خ' },
            { id: 'e4', type: 'tap-correct', title: 'خ কোথায়?', voiceText: 'خ খুঁজে বের করো', content: 'خ', options: ['ح', 'خ', 'د', 'ذ'], correctAnswer: 'خ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'خ বুদবুদ ফাটাও', content: 'خ', options: ['ح', 'خ', 'د', 'ذ'], correctAnswer: 'خ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'خ', options: ['ح', 'خ', 'د', 'ذ'], correctAnswer: 'خ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'خ', options: ['ح-হা', 'خ-খা', 'د-দাল', 'ذ-যাল'], correctAnswer: 'خ' },
            { id: 'e10', type: 'trace', title: 'লিখি — خ', voiceText: 'خ লেখো', content: 'خ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'خ এর নাম কী?', content: 'خ', options: ['হা', 'খা', 'দাল', 'যাল'], correctAnswer: 'খা' },
        ],
    },
    'arabic-dal': {
        id: 'arabic-dal', letter: ' د - এটি দাল!', word: 'دب - দাল দিয়ে হয় দুব্বুন - মানে ভালুক!', wordEn: 'Bear', emoji: '🐻',
        color: 'from-red-400 to-rose-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো দাল (د) শিখি!', voiceText: 'এটি দাল! দাল দিয়ে হয় দুব্বুন - মানে ভালুক!', content: 'د' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'দুব্বুন - ভালুক', content: 'دب' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'দাল — দুব্বুন', content: 'د' },
            { id: 'e4', type: 'tap-correct', title: 'দাল (د) কোথায়?', voiceText: 'দাল হরফটি খুঁজে বের করো!', content: 'د', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'د' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'দাল হরফের বুদবুদগুলো ফাটাও!', content: 'د', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'د' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'د', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'د' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'د', options: ['ج-جمل', 'ح-حصان', 'خ-خروف', 'د-دب'], correctAnswer: 'د' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'দাল লেখা প্র্যাকটিস করো', content: 'د' },
            { id: 'e10', type: 'quiz', title: 'চমৎকার! শেষ প্রশ্ন', voiceText: 'ভালুক বা দুব্বুন কোন হরফ দিয়ে শুরু?', content: 'د', options: ['ذ', 'د', 'ر', 'ز'], correctAnswer: 'د' },
        ],
    },
    'arabic-dhal': {
        id: 'arabic-dhal', letter: ' ذ - এটি যাল!', word: 'ذرة - যাল দিয়ে হয় যুররাহ - মানে ভুট্টা!', wordEn: 'Corn', emoji: '🌽',
        color: 'from-orange-400 to-amber-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো যাল (ذ) শিখি!', voiceText: 'এটি যাল! যাল দিয়ে হয় যুররাহ - মানে ভুট্টা!', content: 'ذ' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'যুররাহ - ভুট্টা', content: 'ذرة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'যাল — যুররাহ', content: 'ذ' },
            { id: 'e4', type: 'tap-correct', title: 'যাল (ذ) কোথায়?', voiceText: 'যাল হরফটি খুঁজে বের করো!', content: 'ذ', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'ذ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'যাল হরফের বুদবুদগুলো ফাটাও!', content: 'ذ', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'ذ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ذ', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'ذ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ذ', options: ['ذ-ذرة', 'ر-رمان', 'ز-زرافة', 'س-سمكة'], correctAnswer: 'ذ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'যাল লেখা প্র্যাকটিস করো', content: 'ذ' },
            { id: 'e10', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'ভুট্টা বা যুররাহ কোন হরফ দিয়ে শুরু?', content: 'ذ', options: ['د', 'ذ', 'ر', 'ز'], correctAnswer: 'ذ' },
        ],
    },
    'arabic-ra': {
        id: 'arabic-ra', letter: ' ر - এটি রা!', word: 'رمان - রা দিয়ে হয় রুম্মান - মানে ডালিম!', wordEn: 'Pomegranate', emoji: '🍎',
        color: 'from-red-500 to-rose-600', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো রা (ر) শিখি!', voiceText: 'এটি রা! রা দিয়ে হয় রুম্মান - মানে ডালিম!', content: 'ر' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'রুম্মান - ডালিম', content: 'رمان' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'রা — রুম্মান', content: 'ر' },
            { id: 'e4', type: 'tap-correct', title: 'রা (ر) কোথায়?', voiceText: 'রা হরফটি খুঁজে বের করো!', content: 'ر', options: ['ذ', 'ر', 'ز', 'س'], correctAnswer: 'ر' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'রা হরফের বুদবুদগুলো ফাটাও!', content: 'ر', options: ['ذ', 'ر', 'ز', 'س'], correctAnswer: 'ر' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ر', options: ['ذ', 'ر', 'ز', 'س'], correctAnswer: 'ر' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ر', options: ['ذ-ذرة', 'ر-رمان', 'ز-زرافة', 'س-سمكة'], correctAnswer: 'ر' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'রা লেখা প্র্যাকটিস করো', content: 'ر' },
            { id: 'e10', type: 'quiz', title: 'দারুণ! শেষ প্রশ্ন', voiceText: 'ডালিম বা রুম্মান কোন হরফ দিয়ে শুরু?', content: 'ر', options: ['ذ', 'ر', 'ز', 'س'], correctAnswer: 'ر' },
        ],
    },
    'arabic-za': {
        id: 'arabic-za', letter: ' ز - এটি যা!', word: 'زرافة - যা দিয়ে হয় যি’রাফাহ - মানে জিরাফ!', wordEn: 'Giraffe', emoji: '🦒',
        color: 'from-yellow-400 to-amber-600', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো যা (ز) শিখি!', voiceText: 'এটি যা! যা দিয়ে হয় যি’রাফাহ - মানে জিরাফ!', content: 'ز' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'যি’রাফাহ - জিরাফ', content: 'زرافة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'যা — যি’রাফাহ', content: 'ز' },
            { id: 'e4', type: 'tap-correct', title: 'যা (ز) কোথায়?', voiceText: 'যা হরফটি খুঁজে বের করো!', content: 'ز', options: ['ر', 'ز', 'س', 'ش'], correctAnswer: 'ز' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'যা হরফের বুদবুদগুলো ফাটাও!', content: 'ز', options: ['ر', 'ز', 'س', 'ش'], correctAnswer: 'ز' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ز', options: ['ر', 'ز', 'س', 'ش'], correctAnswer: 'ز' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ز', options: ['ذ-ذرة', 'ر-رمان', 'ز-زرافة', 'س-سمكة'], correctAnswer: 'ز' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'যা লেখা প্র্যাকটিস করো', content: 'ز' },
            { id: 'e10', type: 'quiz', title: 'চমৎকার! শেষ প্রশ্ন', voiceText: 'জিরাফ বা যি’রাফাহ কোন হরফ দিয়ে শুরু?', content: 'ز', options: ['ر', 'ز', 'س', 'ش'], correctAnswer: 'ز' },
        ],
    },
    'arabic-sin': {
        id: 'arabic-sin', letter: ' س - এটি সিন!', word: 'سمكة - সিন দিয়ে হয় সামাকাহ - মানে মাছ!', wordEn: 'Fish', emoji: '🐟',
        color: 'from-indigo-400 to-blue-600', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো সিন (س) শিখি!', voiceText: 'এটি সিন! সিন দিয়ে হয় সামাকাহ - মানে মাছ!', content: 'س' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'সামাকাহ - মাছ', content: 'سمكة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'সিন — সামাকাহ', content: 'س' },
            { id: 'e4', type: 'tap-correct', title: 'সিন (س) কোথায়?', voiceText: 'সিন হরফটি খুঁজে বের করো!', content: 'س', options: ['ز', 'س', 'ش', 'ص'], correctAnswer: 'س' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'সিন হরফের বুদবুদগুলো ফাটাও!', content: 'س', options: ['ز', 'س', 'ش', 'ص'], correctAnswer: 'س' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'س', options: ['ز', 'س', 'ش', 'ص'], correctAnswer: 'س' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'س', options: ['ذ-ذرة', 'ر-رمان', 'ز-زرافة', 'س-سمكة'], correctAnswer: 'س' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'সিন লেখা প্র্যাকটিস করো', content: 'س' },
            { id: 'e10', type: 'quiz', title: 'অনেক ভালো! শেষ প্রশ্ন', voiceText: 'মাছ বা সামাকাহ কোন হরফ দিয়ে শুরু?', content: 'س', options: ['ز', 'س', 'ش', 'ص'], correctAnswer: 'س' },
        ],
    },
    'arabic-shin': {
        id: 'arabic-shin', letter: ' ش - এটি শিন!', word: 'شمس - শিন দিয়ে হয় শামস - মানে সূর্য!', wordEn: 'Sun', emoji: '☀️',
        color: 'from-purple-400 to-indigo-600', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো শিন (ش) শিখি!', voiceText: 'এটি শিন! শিন দিয়ে হয় শামস - মানে সূর্য!', content: 'ش' },
            { id: 'e2', type: 'listen-repeat', title: 'মন দিয়ে শোনো', voiceText: 'শামস - সূর্য', content: 'شمس' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'শিন — শামস', content: 'ش' },
            { id: 'e4', type: 'tap-correct', title: 'শিন (ش) কোথায়?', voiceText: 'শিন হরফটি খুঁজে বের করো!', content: 'ش', options: ['س', 'ش', 'ص', 'ض'], correctAnswer: 'ش' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটানো!', voiceText: 'শিন হরফের বুদবুদগুলো ফাটাও!', content: 'ش', options: ['س', 'ش', 'ص', 'ض'], correctAnswer: 'ش' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফটি বেছে নাও', content: 'ش', options: ['س', 'ش', 'ص', 'ض'], correctAnswer: 'ش' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'হরফের সাথে শব্দ মেলাও', content: 'ش', options: ['س-سمكة', 'ش-شمس', 'ص-صقر', 'ض-ضفدع'], correctAnswer: 'ش' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি!', voiceText: 'শিন লেখা প্র্যাকটিস করো', content: 'ش' },
            { id: 'e10', type: 'quiz', title: 'সাবাশ! শেষ প্রশ্ন', voiceText: 'সূর্য বা শামস কোন হরফ দিয়ে শুরু?', content: 'ش', options: ['س', 'ش', 'ص', 'ض'], correctAnswer: 'ش' },
        ],
    },
    'arabic-sad': {
        id: 'arabic-sad', letter: 'ص', word: 'صَبْر', wordEn: 'Patience', emoji: '🤲',
        color: 'from-emerald-400 to-teal-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ص — সোয়াদ', content: 'ص' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — صَبْر', voiceText: 'صَبْر', content: 'صَبْر' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ص', content: 'ص' },
            { id: 'e4', type: 'tap-correct', title: 'ص কোথায়?', voiceText: 'ص খুঁজে বের করো', content: 'ص', options: ['ش', 'ص', 'ض', 'ط'], correctAnswer: 'ص' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ص বুদবুদ ফাটাও', content: 'ص', options: ['ش', 'ص', 'ض', 'ط'], correctAnswer: 'ص' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ص', options: ['ش', 'ص', 'ض', 'ط'], correctAnswer: 'ص' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ص', options: ['ش-শিন', 'ص-সোয়াদ', 'ض-দোয়াদ', 'ط-তোয়া'], correctAnswer: 'ص' },
            { id: 'e10', type: 'trace', title: 'লিখি — ص', voiceText: 'ص লেখো', content: 'ص' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ص এর নাম কী?', content: 'ص', options: ['শিন', 'সোয়াদ', 'দোয়াদ', 'তোয়া'], correctAnswer: 'সোয়াদ' },
        ],
    },
    'arabic-dad': {
        id: 'arabic-dad', letter: 'ض', word: 'ضَوْء', wordEn: 'Light', emoji: '💡',
        color: 'from-amber-400 to-yellow-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ض — দোয়াদ', content: 'ض' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ضَوْء', voiceText: 'ضَوْء', content: 'ضَوْء' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ض', content: 'ض' },
            { id: 'e4', type: 'tap-correct', title: 'ض কোথায়?', voiceText: 'ض খুঁজে বের করো', content: 'ض', options: ['ص', 'ض', 'ط', 'ظ'], correctAnswer: 'ض' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ض বুদবুদ ফাটাও', content: 'ض', options: ['ص', 'ض', 'ط', 'ظ'], correctAnswer: 'ض' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ض', options: ['ص', 'ض', 'ط', 'ظ'], correctAnswer: 'ض' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ض', options: ['ص-সোয়াদ', 'ض-দোয়াদ', 'ط-তোয়া', 'ظ-যোয়া'], correctAnswer: 'ض' },
            { id: 'e10', type: 'trace', title: 'লিখি — ض', voiceText: 'ض লেখো', content: 'ض' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ض এর নাম কী?', content: 'ض', options: ['সোয়াদ', 'দোয়াদ', 'তোয়া', 'যোয়া'], correctAnswer: 'দোয়াদ' },
        ],
    },
    'arabic-ta2': {
        id: 'arabic-ta2', letter: 'ط', word: 'طَائِر', wordEn: 'Bird', emoji: '🐦',
        color: 'from-sky-400 to-blue-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ط — তোয়া', content: 'ط' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — طَائِر', voiceText: 'طَائِر', content: 'طَائِر' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ط', content: 'ط' },
            { id: 'e4', type: 'tap-correct', title: 'ط কোথায়?', voiceText: 'ط খুঁজে বের করো', content: 'ط', options: ['ض', 'ط', 'ظ', 'ع'], correctAnswer: 'ط' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ط বুদবুদ ফাটাও', content: 'ط', options: ['ض', 'ط', 'ظ', 'ع'], correctAnswer: 'ط' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ط', options: ['ض', 'ط', 'ظ', 'ع'], correctAnswer: 'ط' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ط', options: ['ض-দোয়াদ', 'ط-তোয়া', 'ظ-যোয়া', 'ع-আইন'], correctAnswer: 'ط' },
            { id: 'e10', type: 'trace', title: 'লিখি — ط', voiceText: 'ط লেখো', content: 'ط' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ط এর নাম কী?', content: 'ط', options: ['দোয়াদ', 'তোয়া', 'যোয়া', 'আইন'], correctAnswer: 'তোয়া' },
        ],
    },
    'arabic-zha': {
        id: 'arabic-zha', letter: 'ظ', word: 'ظَهْر', wordEn: 'Noon', emoji: '🕛',
        color: 'from-indigo-400 to-violet-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ظ — যোয়া', content: 'ظ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ظَهْر', voiceText: 'ظَهْر', content: 'ظَهْر' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ظ', content: 'ظ' },
            { id: 'e4', type: 'tap-correct', title: 'ظ কোথায়?', voiceText: 'ظ খুঁজে বের করো', content: 'ظ', options: ['ط', 'ظ', 'ع', 'غ'], correctAnswer: 'ظ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ظ বুদবুদ ফাটাও', content: 'ظ', options: ['ط', 'ظ', 'ع', 'غ'], correctAnswer: 'ظ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ظ', options: ['ط', 'ظ', 'ع', 'غ'], correctAnswer: 'ظ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ظ', options: ['ط-তোয়া', 'ظ-যোয়া', 'ع-আইন', 'غ-গাইন'], correctAnswer: 'ظ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ظ', voiceText: 'ظ লেখো', content: 'ظ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ظ এর নাম কী?', content: 'ظ', options: ['তোয়া', 'যোয়া', 'আইন', 'গাইন'], correctAnswer: 'যোয়া' },
        ],
    },
    'arabic-ain': {
        id: 'arabic-ain', letter: 'ع', word: 'عِلْم', wordEn: 'Knowledge', emoji: '📖',
        color: 'from-emerald-400 to-green-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ع — আইন', content: 'ع' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — عِلْم', voiceText: 'عِلْم', content: 'عِلْم' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ع', content: 'ع' },
            { id: 'e4', type: 'tap-correct', title: 'ع কোথায়?', voiceText: 'ع খুঁজে বের করো', content: 'ع', options: ['ظ', 'ع', 'غ', 'ف'], correctAnswer: 'ع' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ع বুদবুদ ফাটাও', content: 'ع', options: ['ظ', 'ع', 'غ', 'ف'], correctAnswer: 'ع' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ع', options: ['ظ', 'ع', 'غ', 'ف'], correctAnswer: 'ع' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ع', options: ['ظ-যোয়া', 'ع-আইন', 'غ-গাইন', 'ف-ফা'], correctAnswer: 'ع' },
            { id: 'e10', type: 'trace', title: 'লিখি — ع', voiceText: 'ع লেখো', content: 'ع' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ع এর নাম কী?', content: 'ع', options: ['যোয়া', 'আইন', 'গাইন', 'ফা'], correctAnswer: 'আইন' },
        ],
    },
    'arabic-ghain': {
        id: 'arabic-ghain', letter: 'غ', word: 'غُرْفَة', wordEn: 'Room', emoji: '🏠',
        color: 'from-violet-400 to-purple-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'غ — গাইন', content: 'غ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — غُرْفَة', voiceText: 'غُرْفَة', content: 'غُرْفَة' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'غ', content: 'غ' },
            { id: 'e4', type: 'tap-correct', title: 'غ কোথায়?', voiceText: 'غ খুঁজে বের করো', content: 'غ', options: ['ع', 'غ', 'ف', 'ق'], correctAnswer: 'غ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'غ বুদবুদ ফাটাও', content: 'غ', options: ['ع', 'غ', 'ف', 'ق'], correctAnswer: 'غ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'غ', options: ['ع', 'غ', 'ف', 'ق'], correctAnswer: 'غ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'غ', options: ['ع-আইন', 'غ-গাইন', 'ف-ফা', 'ق-কাফ'], correctAnswer: 'غ' },
            { id: 'e10', type: 'trace', title: 'লিখি — غ', voiceText: 'غ লেখো', content: 'غ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'غ এর নাম কী?', content: 'غ', options: ['আইন', 'গাইন', 'ফা', 'কাফ'], correctAnswer: 'গাইন' },
        ],
    },
    'arabic-fa': {
        id: 'arabic-fa', letter: 'ف', word: 'فِيل', wordEn: 'Elephant', emoji: '🐘',
        color: 'from-gray-400 to-slate-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ف — ফা', content: 'ف' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — فِيل', voiceText: 'فِيل', content: 'فِيل' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ف', content: 'ف' },
            { id: 'e4', type: 'tap-correct', title: 'ف কোথায়?', voiceText: 'ف খুঁজে বের করো', content: 'ف', options: ['غ', 'ف', 'ق', 'ك'], correctAnswer: 'ف' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ف বুদবুদ ফাটাও', content: 'ف', options: ['غ', 'ف', 'ق', 'ك'], correctAnswer: 'ف' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ف', options: ['غ', 'ف', 'ق', 'ك'], correctAnswer: 'ف' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ف', options: ['غ-গাইন', 'ف-ফা', 'ق-কাফ', 'ك-কাফ'], correctAnswer: 'ف' },
            { id: 'e10', type: 'trace', title: 'লিখি — ف', voiceText: 'ف লেখো', content: 'ف' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ف এর নাম কী?', content: 'ف', options: ['গাইন', 'ফা', 'কাফ', 'লাম'], correctAnswer: 'ফা' },
        ],
    },
    'arabic-qaf': {
        id: 'arabic-qaf', letter: 'ق', word: 'قَلَم', wordEn: 'Pen', emoji: '✏️',
        color: 'from-red-400 to-rose-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ق — কাফ', content: 'ق' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — قَلَم', voiceText: 'قَلَم', content: 'قَلَم' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ق', content: 'ق' },
            { id: 'e4', type: 'tap-correct', title: 'ق কোথায়?', voiceText: 'ق খুঁজে বের করো', content: 'ق', options: ['ف', 'ق', 'ك', 'ل'], correctAnswer: 'ق' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ق বুদবুদ ফাটাও', content: 'ق', options: ['ف', 'ق', 'ك', 'ل'], correctAnswer: 'ق' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ق', options: ['ف', 'ق', 'ك', 'ل'], correctAnswer: 'ق' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ق', options: ['ف-ফা', 'ق-কাফ', 'ك-কাফ', 'ل-লাম'], correctAnswer: 'ق' },
            { id: 'e10', type: 'trace', title: 'লিখি — ق', voiceText: 'ق লেখো', content: 'ق' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ق এর নাম কী?', content: 'ق', options: ['ফা', 'কাফ (ق)', 'কাফ (ك)', 'লাম'], correctAnswer: 'কাফ (ق)' },
        ],
    },
    'arabic-kaf': {
        id: 'arabic-kaf', letter: 'ك', word: 'كِتَاب', wordEn: 'Book', emoji: '📚',
        color: 'from-blue-400 to-indigo-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ك — কাফ', content: 'ك' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — كِتَاب', voiceText: 'كِتَاب', content: 'كِتَاب' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ك', content: 'ك' },
            { id: 'e4', type: 'tap-correct', title: 'ك কোথায়?', voiceText: 'ك খুঁজে বের করো', content: 'ك', options: ['ق', 'ك', 'ل', 'م'], correctAnswer: 'ك' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ك বুদবুদ ফাটাও', content: 'ك', options: ['ق', 'ك', 'ل', 'م'], correctAnswer: 'ك' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ك', options: ['ق', 'ك', 'ل', 'م'], correctAnswer: 'ك' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ك', options: ['ق-কাফ', 'ك-কাফ', 'ل-লাম', 'م-মিম'], correctAnswer: 'ك' },
            { id: 'e10', type: 'trace', title: 'লিখি — ك', voiceText: 'ك লেখো', content: 'ك' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ك এর নাম কী?', content: 'ك', options: ['কাফ (ق)', 'কাফ (ك)', 'লাম', 'মিম'], correctAnswer: 'কাফ (ك)' },
        ],
    },
    'arabic-lam': {
        id: 'arabic-lam', letter: 'ل', word: 'لَيْل', wordEn: 'Night', emoji: '🌙',
        color: 'from-indigo-400 to-blue-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ل — লাম', content: 'ل' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — لَيْل', voiceText: 'لَيْل', content: 'لَيْل' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ل', content: 'ل' },
            { id: 'e4', type: 'tap-correct', title: 'ل কোথায়?', voiceText: 'ل খুঁজে বের করো', content: 'ل', options: ['ك', 'ل', 'م', 'ن'], correctAnswer: 'ل' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ل বুদবুদ ফাটাও', content: 'ل', options: ['ك', 'ل', 'م', 'ن'], correctAnswer: 'ل' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ل', options: ['ك', 'ل', 'م', 'ن'], correctAnswer: 'ل' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ل', options: ['ك-কাফ', 'ل-লাম', 'م-মিম', 'ن-নুন'], correctAnswer: 'ل' },
            { id: 'e10', type: 'trace', title: 'লিখি — ل', voiceText: 'ل লেখো', content: 'ل' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ل এর নাম কী?', content: 'ل', options: ['কাফ', 'লাম', 'মিম', 'নুন'], correctAnswer: 'লাম' },
        ],
    },
    'arabic-mim': {
        id: 'arabic-mim', letter: 'م', word: 'مَاء', wordEn: 'Water', emoji: '💧',
        color: 'from-cyan-400 to-blue-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'م — মিম', content: 'م' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — مَاء', voiceText: 'مَاء', content: 'مَاء' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'م', content: 'م' },
            { id: 'e4', type: 'tap-correct', title: 'م কোথায়?', voiceText: 'م খুঁজে বের করো', content: 'م', options: ['ل', 'م', 'ن', 'ه'], correctAnswer: 'م' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'م বুদবুদ ফাটাও', content: 'م', options: ['ل', 'م', 'ن', 'ه'], correctAnswer: 'م' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'م', options: ['ل', 'م', 'ن', 'ه'], correctAnswer: 'م' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'م', options: ['ل-লাম', 'م-মিম', 'ن-নুন', 'ه-হা'], correctAnswer: 'م' },
            { id: 'e10', type: 'trace', title: 'লিখি — م', voiceText: 'م লেখো', content: 'م' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'م এর নাম কী?', content: 'م', options: ['লাম', 'মিম', 'নুন', 'হা'], correctAnswer: 'মিম' },
        ],
    },
    'arabic-nun': {
        id: 'arabic-nun', letter: 'ن', word: 'نَجْم', wordEn: 'Star', emoji: '⭐',
        color: 'from-yellow-400 to-amber-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ن — নুন', content: 'ن' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — نَجْم', voiceText: 'نَجْم', content: 'نَجْم' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ن', content: 'ن' },
            { id: 'e4', type: 'tap-correct', title: 'ن কোথায়?', voiceText: 'ن খুঁজে বের করো', content: 'ن', options: ['م', 'ن', 'ه', 'و'], correctAnswer: 'ن' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ن বুদবুদ ফাটাও', content: 'ن', options: ['م', 'ن', 'ه', 'و'], correctAnswer: 'ن' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ن', options: ['م', 'ن', 'ه', 'و'], correctAnswer: 'ن' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ن', options: ['م-মিম', 'ن-নুন', 'ه-হা', 'و-ওয়াও'], correctAnswer: 'ن' },
            { id: 'e10', type: 'trace', title: 'লিখি — ن', voiceText: 'ن লেখো', content: 'ن' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ن এর নাম কী?', content: 'ن', options: ['মিম', 'নুন', 'হা', 'ওয়াও'], correctAnswer: 'নুন' },
        ],
    },
    'arabic-waw': {
        id: 'arabic-waw', letter: 'و', word: 'وَرْد', wordEn: 'Rose', emoji: '🌹',
        color: 'from-rose-400 to-pink-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'و — ওয়াও', content: 'و' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — وَرْد', voiceText: 'وَرْد', content: 'وَرْد' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'و', content: 'و' },
            { id: 'e4', type: 'tap-correct', title: 'و কোথায়?', voiceText: 'و খুঁজে বের করো', content: 'و', options: ['ه', 'و', 'ي', 'ا'], correctAnswer: 'و' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'و বুদবুদ ফাটাও', content: 'و', options: ['ه', 'و', 'ي', 'ا'], correctAnswer: 'و' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'و', options: ['ه', 'و', 'ي', 'ا'], correctAnswer: 'و' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'و', options: ['ه-হা', 'و-ওয়াও', 'ي-ইয়া', 'ا-আলিফ'], correctAnswer: 'و' },
            { id: 'e10', type: 'trace', title: 'লিখি — و', voiceText: 'و লেখো', content: 'و' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'و এর নাম কী?', content: 'و', options: ['হা', 'ওয়াও', 'ইয়া', 'আলিফ'], correctAnswer: 'ওয়াও' },
        ],
    },
    'arabic-ha2': {
        id: 'arabic-ha2', letter: 'ه', word: 'هِلَال', wordEn: 'Crescent', emoji: '🌙',
        color: 'from-emerald-400 to-teal-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ه — হা', content: 'ه' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — هِلَال', voiceText: 'هِلَال', content: 'هِلَال' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ه', content: 'ه' },
            { id: 'e4', type: 'tap-correct', title: 'ه কোথায়?', voiceText: 'ه খুঁজে বের করো', content: 'ه', options: ['ن', 'ه', 'و', 'ي'], correctAnswer: 'ه' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ه বুদবুদ ফাটাও', content: 'ه', options: ['ن', 'ه', 'و', 'ي'], correctAnswer: 'ه' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ه', options: ['ن', 'ه', 'و', 'ي'], correctAnswer: 'ه' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ه', options: ['ن-নুন', 'ه-হা', 'و-ওয়াও', 'ي-ইয়া'], correctAnswer: 'ه' },
            { id: 'e10', type: 'trace', title: 'লিখি — ه', voiceText: 'ه লেখো', content: 'ه' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ه এর নাম কী?', content: 'ه', options: ['নুন', 'হা', 'ওয়াও', 'ইয়া'], correctAnswer: 'হা' },
        ],
    },
    'arabic-ya': {
        id: 'arabic-ya', letter: 'ي', word: 'يَد', wordEn: 'Hand', emoji: '🤚',
        color: 'from-violet-400 to-purple-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ي — ইয়া', content: 'ي' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — يَد', voiceText: 'يَد', content: 'يَد' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ي', content: 'ي' },
            { id: 'e4', type: 'tap-correct', title: 'ي কোথায়?', voiceText: 'ي খুঁজে বের করো', content: 'ي', options: ['و', 'ي', 'ا', 'ب'], correctAnswer: 'ي' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ي বুদবুদ ফাটাও', content: 'ي', options: ['و', 'ي', 'ا', 'ب'], correctAnswer: 'ي' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক হরফ বেছে নাও', content: 'ي', options: ['و', 'ي', 'ا', 'ب'], correctAnswer: 'ي' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরফ মেলাও', content: 'ي', options: ['و-ওয়াও', 'ي-ইয়া', 'ا-আলিফ', 'ب-বা'], correctAnswer: 'ي' },
            { id: 'e10', type: 'trace', title: 'লিখি — ي', voiceText: 'ي লেখো', content: 'ي' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ي এর নাম কী?', content: 'ي', options: ['ওয়াও', 'ইয়া', 'আলিফ', 'বা'], correctAnswer: 'ইয়া' },
        ],
    },
    // ─── হরকত ────────────────────────────────────────────────────
    'arabic-fatha': {
        id: 'arabic-fatha', letter: 'فَ', word: 'فَتْحَة', wordEn: 'Fatha (আ)', emoji: '📖',
        color: 'from-amber-400 to-yellow-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'যবর — আ উচ্চারণ', voiceText: 'যবর দিলে আ উচ্চারণ হয়', content: 'فَ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — بَ', voiceText: 'বা', content: 'بَ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'বা', content: 'فَ' },
            { id: 'e4', type: 'tap-correct', title: 'যবর কোথায়?', voiceText: 'যবর খুঁজে বের করো', content: 'فَ', options: ['فَ', 'فِ', 'فُ', 'فْ'], correctAnswer: 'فَ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'যবর বুদবুদ ফাটাও', content: 'فَ', options: ['فَ', 'فِ', 'فُ', 'فْ'], correctAnswer: 'فَ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরকত মেলাও', content: 'فَ', options: ['فَ-যবর', 'فِ-যের', 'فُ-পেশ', 'فْ-সাকিন'], correctAnswer: 'فَ' },
            { id: 'e10', type: 'trace', title: 'লিখি — فَ', voiceText: 'যবর লেখো', content: 'فَ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'যবর দিলে কোন উচ্চারণ হয়?', content: 'فَ', options: ['আ', 'ই', 'উ', 'ও'], correctAnswer: 'আ' },
        ],
    },
    'arabic-kasra': {
        id: 'arabic-kasra', letter: 'فِ', word: 'كِسْرَة', wordEn: 'Kasra (ই)', emoji: '📖',
        color: 'from-blue-400 to-cyan-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'যের — ই উচ্চারণ', voiceText: 'যের দিলে ই উচ্চারণ হয়', content: 'فِ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — بِ', voiceText: 'বি', content: 'بِ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'বি', content: 'فِ' },
            { id: 'e4', type: 'tap-correct', title: 'যের কোথায়?', voiceText: 'যের খুঁজে বের করো', content: 'فِ', options: ['فَ', 'فِ', 'فُ', 'فْ'], correctAnswer: 'فِ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'যের বুদবুদ ফাটাও', content: 'فِ', options: ['فَ', 'فِ', 'فُ', 'فْ'], correctAnswer: 'فِ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরকত মেলাও', content: 'فِ', options: ['فَ-যবর', 'فِ-যের', 'فُ-পেশ', 'فْ-সাকিন'], correctAnswer: 'فِ' },
            { id: 'e10', type: 'trace', title: 'লিখি — فِ', voiceText: 'যের লেখো', content: 'فِ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'যের দিলে কোন উচ্চারণ হয়?', content: 'فِ', options: ['আ', 'ই', 'উ', 'ও'], correctAnswer: 'ই' },
        ],
    },
    'arabic-damma': {
        id: 'arabic-damma', letter: 'فُ', word: 'ضَمَّة', wordEn: 'Damma (উ)', emoji: '📖',
        color: 'from-emerald-400 to-green-500', lang: 'ar-SA',
        backHref: '/dashboard/student/kids-zone/nursery/arabic',
        exercises: [
            { id: 'e1', type: 'intro', title: 'পেশ — উ উচ্চারণ', voiceText: 'পেশ দিলে উ উচ্চারণ হয়', content: 'فُ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — بُ', voiceText: 'বু', content: 'بُ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'বু', content: 'فُ' },
            { id: 'e4', type: 'tap-correct', title: 'পেশ কোথায়?', voiceText: 'পেশ খুঁজে বের করো', content: 'فُ', options: ['فَ', 'فِ', 'فُ', 'فْ'], correctAnswer: 'فُ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'পেশ বুদবুদ ফাটাও', content: 'فُ', options: ['فَ', 'فِ', 'فُ', 'فْ'], correctAnswer: 'فُ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'হরকত মেলাও', content: 'فُ', options: ['فَ-যবর', 'فِ-যের', 'فُ-পেশ', 'فْ-সাকিন'], correctAnswer: 'فُ' },
            { id: 'e10', type: 'trace', title: 'লিখি — فُ', voiceText: 'পেশ লেখো', content: 'فُ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'পেশ দিলে কোন উচ্চারণ হয়?', content: 'فُ', options: ['আ', 'ই', 'উ', 'ও'], correctAnswer: 'উ' },
        ],
    },
}

export default function ArabicLessonPage() {
    const params = useParams()
    const lessonId = params.lessonId as string
    const lesson = lessons[lessonId]

    if (!lesson) return (
        <div className="min-h-screen bg-linear-to-br from-indigo-900 to-purple-900 flex items-center justify-center text-white p-6">
            <div className="text-center bg-white/10 p-10 rounded-3xl backdrop-blur-md shadow-2xl">
                <div className="text-8xl mb-6">🐣</div>
                <h2 className="text-3xl font-bold mb-4">আসছে!</h2>
                <p className="text-lg">এই লেসনটি খুব শীঘ্রই আসছে। সাথে থাকো!</p>
            </div>
        </div>
    )

    return <LessonEngine lesson={lesson} />
}