'use client'

import { useMemo, useState } from 'react'
import { BookOpen, ChevronRight, CirclePlus, Eye, Filter, FolderOpen, GraduationCap, Pencil, Search, Trash2, Users } from 'lucide-react'
import AddClassModal from './AddClassModal'
import EditClassModal from './EditClassModal'
import DeleteClassModal from './DeleteClassModal'

type CurriculumClass = { id: string; version_id: string; name: string; slug: string; class_number: number; description?: string | null; is_active: boolean; curriculum_versions?: { name: string } | null }
type Props = { classes: CurriculumClass[] }

function ActionButton({ label, children, danger, onClick }: { label: string; children: React.ReactNode; danger?: boolean; onClick?: () => void }) {
  return <button type="button" aria-label={label} title={label} onClick={onClick} className={`grid size-8 place-items-center rounded-full border transition ${danger ? 'border-rose-500/35 bg-rose-500/10 text-rose-400 hover:bg-rose-500/20' : 'border-slate-600 bg-slate-800/70 text-slate-200 hover:border-violet-400 hover:text-white'}`}>{children}</button>
}
function Status({ active }: { active: boolean }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${active ? 'bg-emerald-400/10 text-emerald-300' : 'bg-slate-500/15 text-slate-400'}`}>{active ? 'Active' : 'Inactive'}</span> }

export default function ClassesClient({ classes }: Props) {
  const [openModal, setOpenModal] = useState(false)
  const [editOpen, setEditOpen] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)
  const [selectedClass, setSelectedClass] = useState<CurriculumClass | null>(null)
  const [search, setSearch] = useState('')
  const filteredClasses = useMemo(() => { const keyword = search.trim().toLowerCase(); return !keyword ? classes : classes.filter((item) => [item.name, item.slug, item.curriculum_versions?.name ?? ''].some((value) => value.toLowerCase().includes(keyword))) }, [classes, search])
  const activeClasses = classes.filter((item) => item.is_active).length
  const openEdit = (item: CurriculumClass) => { setSelectedClass(item); setEditOpen(true) }
  const openDelete = (item: CurriculumClass) => { setSelectedClass(item); setDeleteOpen(true) }

  return <main className="min-h-screen bg-[#030711] px-3 py-5 text-slate-100 sm:px-6 lg:px-8"><div className="mx-auto max-w-375 space-y-5">
    <header className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="grid size-12 place-items-center rounded-xl border border-emerald-400/55 bg-emerald-400/10 shadow-[0_0_26px_rgba(52,211,153,.18)]"><GraduationCap className="size-6 text-emerald-300" /></div><div><h1 className="text-[clamp(1.65rem,3vw,2.55rem)] font-extrabold tracking-tight">Class <span className="bg-linear-to-r from-emerald-300 to-cyan-300 bg-clip-text text-transparent">Management</span></h1><p className="mt-0.5 text-sm text-slate-400">Manage NCTB curriculum classes and organize learning levels.</p></div></div><button onClick={() => setOpenModal(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-linear-to-r from-emerald-500 to-teal-500 px-4 py-2.5 text-sm font-bold shadow-lg shadow-emerald-900/30 transition hover:brightness-110"><CirclePlus className="size-4" /> Add Class</button></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><StatCard label="Total Classes" value={classes.length} text="All NCTB class levels" color="blue" icon={<GraduationCap className="size-6" />} /><StatCard label="Active Classes" value={activeClasses} text="Visible to learners" color="green" icon={<Users className="size-6" />} /><StatCard label="Search Results" value={filteredClasses.length} text={search ? `Matching “${search}”` : 'All classes shown'} color="purple" icon={<BookOpen className="size-6" />} /></section>
    <section className="overflow-hidden rounded-xl border border-slate-700/80 bg-linear-to-br from-[#0b1223] to-[#070b15] shadow-[0_15px_50px_rgba(0,0,0,.25)]"><div className="flex flex-col gap-4 border-b border-slate-700/70 p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="flex items-center gap-2 text-lg font-bold"><FolderOpen className="size-5 text-emerald-300" /> Curriculum Classes</h2><p className="mt-1 text-xs text-slate-400">Browse, edit and manage all available classes.</p></div><div className="flex gap-3"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search class..." className="h-10 w-52 rounded-lg border border-slate-600 bg-[#0a1020] pl-9 pr-3 text-sm outline-none placeholder:text-slate-500 focus:border-emerald-400" /></label><button aria-label="Filter classes" className="grid size-10 place-items-center rounded-lg border border-slate-600 bg-[#0a1020] text-slate-300"><Filter className="size-4" /></button></div></div>
      <div className="hidden grid-cols-[90px_minmax(220px,1fr)_180px_160px_110px_140px] gap-4 border-b border-slate-700/80 bg-slate-800/60 px-5 py-3 text-xs font-semibold text-slate-300 md:grid"><span>Class</span><span>Name</span><span>Slug</span><span>Version</span><span>Status</span><span>Actions</span></div>
      <div className="divide-y divide-slate-800/90">{filteredClasses.length === 0 ? <div className="py-16 text-center"><FolderOpen className="mx-auto size-10 text-slate-600" /><p className="mt-3 font-bold">No classes found</p><p className="mt-1 text-sm text-slate-500">Try another search keyword.</p></div> : filteredClasses.map((item) => <article key={item.id} className="grid items-center gap-4 px-5 py-3 transition hover:bg-white/[.025] md:grid-cols-[90px_minmax(220px,1fr)_180px_160px_110px_140px]"><div className="grid size-11 place-items-center rounded-xl border border-emerald-400/45 bg-emerald-400/10 text-lg font-black text-emerald-300 shadow-[0_0_18px_rgba(52,211,153,.15)]">{item.class_number}</div><div><p className="font-bold text-white">{item.name}</p><p className="mt-0.5 truncate text-xs text-slate-500">{item.description || 'No description added yet'}</p></div><code className="w-fit rounded-md bg-slate-800/80 px-2 py-1 text-xs text-sky-300">{item.slug}</code><p className="text-sm text-slate-400">{item.curriculum_versions?.name ?? 'NCTB 2026'}</p><Status active={item.is_active} /><div className="flex gap-2"><ActionButton label="View class"><Eye className="size-3.5" /></ActionButton><ActionButton label="Edit class" onClick={() => openEdit(item)}><Pencil className="size-3.5" /></ActionButton><ActionButton label="Delete class" danger onClick={() => openDelete(item)}><Trash2 className="size-3.5" /></ActionButton></div><div className="mt-1 flex items-center gap-1 text-xs text-slate-500 md:hidden"><ChevronRight className="size-3" /> {item.curriculum_versions?.name ?? 'NCTB 2026'}</div></article>)}</div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Class order", "Keep a unique class number per version", "01"], ["Visibility", "Active classes are available for content mapping", "✓"], ["Content", "Use Content Manager to add subjects and lessons", "▣"], ["Need help?", "Start by creating your first class", "+"]].map(([title, text, symbol]) => <div key={title} className="rounded-xl border border-slate-700/80 bg-linear-to-br from-[#10192b] to-[#080c16] p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg border border-violet-400/40 bg-violet-400/10 text-sm font-bold text-violet-300">{symbol}</span><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-slate-400">{text}</p></div></div></div>)}</section>
    <AddClassModal open={openModal} onClose={() => setOpenModal(false)} onSuccess={() => window.location.reload()} />
    <EditClassModal open={editOpen} classItem={selectedClass ? { ...selectedClass, description: selectedClass.description ?? null } : null} onClose={() => setEditOpen(false)} onSuccess={() => window.location.reload()} />
    <DeleteClassModal open={deleteOpen} classItem={selectedClass} onClose={() => setDeleteOpen(false)} onSuccess={() => window.location.reload()} />
  </div></main>
}
function StatCard({ label, value, text, color, icon }: { label: string; value: number; text: string; color: 'blue' | 'green' | 'purple'; icon: React.ReactNode }) { const theme = { blue: 'border-sky-400/50 text-sky-300', green: 'border-emerald-400/50 text-emerald-300', purple: 'border-violet-400/50 text-violet-300' }[color]; return <article className={`rounded-xl border bg-linear-to-br from-[#0d1425] to-[#070b16] p-5 shadow-2xl ${theme}`}><div className={`grid size-12 place-items-center rounded-xl border bg-white/4 ${theme}`}>{icon}</div><p className="mt-5 text-xs text-slate-300">{label}</p><p className="mt-1 text-4xl font-extrabold text-white">{value}</p><p className="mt-4 text-xs text-slate-400">{text}</p><div className="mt-3 h-px bg-current opacity-30" /></article> }
