"use client";
import { FormEvent, useEffect, useState } from "react";
type Version = { id:string; name:string; slug:string; year:number; description:string|null; status:"draft"|"published"|"archived"; is_active:boolean };
const initial = { name:"", slug:"", year:2026, description:"", status:"draft", isActive:false };
export default function VersionsClient() {
 const [items,setItems]=useState<Version[]>([]),[form,setForm]=useState(initial),[editing,setEditing]=useState<Version|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const load=async()=>{const r=await fetch("/api/admin/curriculum/versions");const d=await r.json();if(r.ok)setItems(d);else setError(d.error??"লোড করা যায়নি")};
 useEffect(()=>{let cancelled=false;fetch("/api/admin/curriculum/versions").then(async(r)=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>{if(cancelled)return;if(ok)setItems(data);else setError(data.error??"লোড করা যায়নি")});return()=>{cancelled=true}},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);const r=await fetch(editing?`/api/admin/curriculum/versions?id=${editing.id}`:"/api/admin/curriculum/versions",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)setError(d.error??"সংরক্ষণ করা যায়নি");else{setForm(initial);setEditing(null);await load()}setSaving(false)};
 const remove=async(version:Version)=>{if(!window.confirm(`Delete ${version.name}?`))return;const r=await fetch(`/api/admin/curriculum/versions?id=${version.id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)setError(d.error??"মুছে ফেলা যায়নি");else await load()};
 return <main className="min-h-screen bg-[#030711] p-6 text-slate-100"><div className="mx-auto grid max-w-6xl gap-6 lg:grid-cols-[1fr_360px]"><section><p className="text-violet-300">Curriculum setup</p><h1 className="text-3xl font-black">Curriculum Versions</h1>{error&&<p className="mt-4 rounded-lg bg-rose-500/10 p-3 text-rose-200">{error}</p>}<div className="mt-6 space-y-3">{items.map(v=><article key={v.id} className="flex justify-between rounded-xl border border-slate-700 bg-slate-900/70 p-4"><div><b>{v.name}</b>{v.is_active&&<span className="ml-2 text-xs text-emerald-300">● Active</span>}<p className="text-xs text-slate-400">{v.year} · {v.slug} · {v.status}</p></div><div className="flex gap-3"><button onClick={()=>{setEditing(v);setForm({name:v.name,slug:v.slug,year:v.year,description:v.description??"",status:v.status,isActive:v.is_active})}} className="text-sm text-violet-300">Edit</button><button onClick={()=>void remove(v)} disabled={v.is_active} className="text-sm text-rose-300 disabled:cursor-not-allowed disabled:opacity-40">Delete</button></div></article>)}</div></section><form onSubmit={submit} className="h-fit rounded-xl border border-violet-400/30 bg-slate-900/70 p-5"><h2 className="font-bold">{editing?"Edit Version":"New Version"}</h2>{([['Name','name'],['Slug','slug']] as const).map(([label,key])=><label key={key} className="mt-3 block text-sm">{label}<input required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-600 bg-slate-950 p-2" /></label>)}<label className="mt-3 block text-sm">Year<input type="number" value={form.year} onChange={e=>setForm({...form,year:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-slate-600 bg-slate-950 p-2" /></label><label className="mt-3 flex gap-2"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>Make active</label><button disabled={saving} className="mt-5 rounded-lg bg-violet-600 px-4 py-2 font-bold">{saving?"Saving...":"Save"}</button></form></div></main>
}
