import type { LessonConfig } from '@/components/kids/LessonEngine'

export const banglaLessonsP2b: Record<string, LessonConfig> = {

    'banjanbarna-ta': {
        id: 'banjanbarna-ta', letter: 'ট', word: 'টমেটো', wordEn: 'Tomato', emoji: '🍅',
        color: 'from-red-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ট শিখি!', voiceText: 'টমেটো লাল রঙের সবজি। টমেটো শব্দটি ট দিয়ে শুরু হয়। আজ আমরা ট শিখব।', content: 'ট' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ট... টমেটো', content: 'টমেটো' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ট', content: 'ট' },
            { id: 'e4', type: 'tap-correct', title: 'ট কোথায়?', voiceText: 'ট বর্ণটি খুঁজে বের করো।', content: 'ট', options: ['ঞ', 'ট', 'ঠ', 'ড'], correctAnswer: 'ট' },
            { id: 'e5', type: 'bubble-pop', title: 'ট ধরো!', voiceText: 'ট লেখা বুদবুদটি ফাটাও।', content: 'ট', options: ['ঞ', 'ট', 'ঠ', 'ড'], correctAnswer: 'ট' },
            { id: 'e6', type: 'letter-puzzle', title: 'টমেটো কোন বর্ণ?', voiceText: 'টমেটো এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ট', options: ['ঞ', 'ট', 'ঠ', 'ড'], correctAnswer: 'ট' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'টমেটো শব্দটি সাজাও।', content: 'টমেটো', options: ['ট', 'ম', 'ে', 'ট', 'ো'], correctAnswer: 'টমেটো' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ট', options: ['ঞ-মিঞা', 'ট-টমেটো', 'ঠ-ঠোঁট', 'ড-ডাব'], correctAnswer: 'ট' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ট লেখো।', content: 'ট' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'টমেটো কোন বর্ণের সাথে জড়িত?', content: 'ট', options: ['ঞ', 'ট', 'ঠ', 'ড'], correctAnswer: 'ট' },
        ],
    },
    'banjanbarna-tha': {
        id: 'banjanbarna-tha', letter: 'ঠ', word: 'ঠোঁট', wordEn: 'Lips', emoji: '👄',
        color: 'from-pink-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঠ শিখি!', voiceText: 'হাসলে ঠোঁট দেখা যায়। ঠোঁট শব্দটি ঠ দিয়ে শুরু হয়। আজ আমরা ঠ শিখব।', content: 'ঠ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঠ... ঠোঁট', content: 'ঠোঁট' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঠ', content: 'ঠ' },
            { id: 'e4', type: 'tap-correct', title: 'ঠ কোথায়?', voiceText: 'ঠ বর্ণটি খুঁজে বের করো।', content: 'ঠ', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ঠ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঠ ধরো!', voiceText: 'ঠ লেখা বুদবুদটি ফাটাও।', content: 'ঠ', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ঠ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঠোঁট কোন বর্ণ?', voiceText: 'ঠোঁট এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঠ', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ঠ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঠোঁট শব্দটি সাজাও।', content: 'ঠোঁট', options: ['ঠ', 'ো', 'ঁ', 'ট'], correctAnswer: 'ঠোঁট' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঠ', options: ['ট-টমেটো', 'ঠ-ঠোঁট', 'ড-ডাব', 'ঢ-ঢোল'], correctAnswer: 'ঠ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঠ লেখো।', content: 'ঠ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঠোঁট কোন বর্ণের সাথে জড়িত?', content: 'ঠ', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ঠ' },
        ],
    },
    'banjanbarna-da': {
        id: 'banjanbarna-da', letter: 'ড', word: 'ডাব', wordEn: 'Green coconut', emoji: '🥥',
        color: 'from-green-400 to-teal-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ড শিখি!', voiceText: 'গরমে ঠান্ডা ডাবের পানি। ডাব শব্দটি ড দিয়ে শুরু হয়। আজ আমরা ড শিখব।', content: 'ড' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ড... ডাব', content: 'ডাব' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ড', content: 'ড' },
            { id: 'e4', type: 'tap-correct', title: 'ড কোথায়?', voiceText: 'ড বর্ণটি খুঁজে বের করো।', content: 'ড', options: ['ঠ', 'ড', 'ঢ', 'ণ'], correctAnswer: 'ড' },
            { id: 'e5', type: 'bubble-pop', title: 'ড ধরো!', voiceText: 'ড লেখা বুদবুদটি ফাটাও।', content: 'ড', options: ['ঠ', 'ড', 'ঢ', 'ণ'], correctAnswer: 'ড' },
            { id: 'e6', type: 'letter-puzzle', title: 'ডাব কোন বর্ণ?', voiceText: 'ডাব এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ড', options: ['ঠ', 'ড', 'ঢ', 'ণ'], correctAnswer: 'ড' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ডাব শব্দটি সাজাও।', content: 'ডাব', options: ['ড', 'া', 'ব'], correctAnswer: 'ডাব' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ড', options: ['ঠ-ঠোঁট', 'ড-ডাব', 'ঢ-ঢোল', 'ণ-মণি'], correctAnswer: 'ড' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ড লেখো।', content: 'ড' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ডাব কোন বর্ণের সাথে জড়িত?', content: 'ড', options: ['ঠ', 'ড', 'ঢ', 'ণ'], correctAnswer: 'ড' },
        ],
    },
    'banjanbarna-dha': {
        id: 'banjanbarna-dha', letter: 'ঢ', word: 'ঢোল', wordEn: 'Drum', emoji: '🥁',
        color: 'from-amber-400 to-orange-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঢ শিখি!', voiceText: 'পূজোয় ঢোল বাজে জোরে। ঢোল শব্দটি ঢ দিয়ে শুরু হয়। আজ আমরা ঢ শিখব।', content: 'ঢ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঢ... ঢোল', content: 'ঢোল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঢ', content: 'ঢ' },
            { id: 'e4', type: 'tap-correct', title: 'ঢ কোথায়?', voiceText: 'ঢ বর্ণটি খুঁজে বের করো।', content: 'ঢ', options: ['ড', 'ঢ', 'ণ', 'ত'], correctAnswer: 'ঢ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঢ ধরো!', voiceText: 'ঢ লেখা বুদবুদটি ফাটাও।', content: 'ঢ', options: ['ড', 'ঢ', 'ণ', 'ত'], correctAnswer: 'ঢ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঢোল কোন বর্ণ?', voiceText: 'ঢোল এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঢ', options: ['ড', 'ঢ', 'ণ', 'ত'], correctAnswer: 'ঢ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঢোল শব্দটি সাজাও।', content: 'ঢোল', options: ['ঢ', 'ো', 'ল'], correctAnswer: 'ঢোল' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঢ', options: ['ড-ডাব', 'ঢ-ঢোল', 'ণ-মণি', 'ত-তরমুজ'], correctAnswer: 'ঢ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঢ লেখো।', content: 'ঢ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঢোল কোন বর্ণের সাথে জড়িত?', content: 'ঢ', options: ['ড', 'ঢ', 'ণ', 'ত'], correctAnswer: 'ঢ' },
        ],
    },
    'banjanbarna-na': {
        id: 'banjanbarna-na', letter: 'ণ', word: 'মণি', wordEn: 'Gem', emoji: '💎',
        color: 'from-cyan-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ণ শিখি!', voiceText: 'মণি জ্বলে উজ্জ্বল আলোয়। মণি শব্দে ণ আছে। আজ আমরা ণ শিখব।', content: 'ণ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ণ... মণি', content: 'মণি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ণ', content: 'ণ' },
            { id: 'e4', type: 'tap-correct', title: 'ণ কোথায়?', voiceText: 'ণ বর্ণটি খুঁজে বের করো।', content: 'ণ', options: ['ঢ', 'ণ', 'ত', 'থ'], correctAnswer: 'ণ' },
            { id: 'e5', type: 'bubble-pop', title: 'ণ ধরো!', voiceText: 'ণ লেখা বুদবুদটি ফাটাও।', content: 'ণ', options: ['ঢ', 'ণ', 'ত', 'থ'], correctAnswer: 'ণ' },
            { id: 'e6', type: 'letter-puzzle', title: 'মণি কোন বর্ণ?', voiceText: 'মণি এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ণ', options: ['ঢ', 'ণ', 'ত', 'থ'], correctAnswer: 'ণ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'মণি শব্দটি সাজাও।', content: 'মণি', options: ['ম', 'ণ', 'ি'], correctAnswer: 'মণি' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ণ', options: ['ঢ-ঢোল', 'ণ-মণি', 'ত-তরমুজ', 'থ-থালা'], correctAnswer: 'ণ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ণ লেখো।', content: 'ণ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'মণি কোন বর্ণের সাথে জড়িত?', content: 'ণ', options: ['ঢ', 'ণ', 'ত', 'থ'], correctAnswer: 'ণ' },
        ],
    },
    'boss-banjanbarna-1': {
        id: 'boss-banjanbarna-1', letter: '★', word: 'ব্যঞ্জন Part 1 Boss', wordEn: 'Boss Quiz', emoji: '🌿',
        color: 'from-violet-400 to-purple-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'ব্যঞ্জন Part 1 Boss!', voiceText: 'প্রস্তুত? ক থেকে ণ সব মনে করে খেলি!', content: '★' },
            { id: 'e2', type: 'tap-correct', title: 'কাক কোন বর্ণ?', voiceText: 'কাক কোন বর্ণ?', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
            { id: 'e3', type: 'tap-correct', title: 'চাঁদ কোন বর্ণ?', voiceText: 'চাঁদ কোন বর্ণ?', content: 'চ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'চ' },
            { id: 'e4', type: 'tap-correct', title: 'টমেটো কোন বর্ণ?', voiceText: 'টমেটো কোন বর্ণ?', content: 'ট', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ট' },
            { id: 'e5', type: 'matching', title: 'সব মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও।', content: '★', options: ['ক-কাক', 'গ-গরু', 'চ-চাঁদ', 'ট-টমেটো'], correctAnswer: 'ক' },
            { id: 'e6', type: 'quiz', title: 'চূড়ান্ত!', voiceText: 'মণি কোন বর্ণ?', content: 'ণ', options: ['ণ', 'ন', 'ম', 'ল'], correctAnswer: 'ণ' },
        ],
    },
    'banjanbarna2-ta': {
        id: 'banjanbarna2-ta', letter: 'ত', word: 'তরমুজ', wordEn: 'Watermelon', emoji: '🍉',
        color: 'from-green-400 to-lime-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ত শিখি!', voiceText: 'গরমে মিষ্টি তরমুজ। তরমুজ শব্দটি ত দিয়ে শুরু হয়। আজ আমরা ত শিখব।', content: 'ত' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ত... তরমুজ', content: 'তরমুজ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ত', content: 'ত' },
            { id: 'e4', type: 'tap-correct', title: 'ত কোথায়?', voiceText: 'ত বর্ণটি খুঁজে বের করো।', content: 'ত', options: ['ণ', 'ত', 'থ', 'দ'], correctAnswer: 'ত' },
            { id: 'e5', type: 'bubble-pop', title: 'ত ধরো!', voiceText: 'ত লেখা বুদবুদটি ফাটাও।', content: 'ত', options: ['ণ', 'ত', 'থ', 'দ'], correctAnswer: 'ত' },
            { id: 'e6', type: 'letter-puzzle', title: 'তরমুজ কোন বর্ণ?', voiceText: 'তরমুজ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ত', options: ['ণ', 'ত', 'থ', 'দ'], correctAnswer: 'ত' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'তরমুজ শব্দটি সাজাও।', content: 'তরমুজ', options: ['ত', 'র', 'ম', 'ু', 'জ'], correctAnswer: 'তরমুজ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ত', options: ['ণ-মণি', 'ত-তরমুজ', 'থ-থালা', 'দ-দরজা'], correctAnswer: 'ত' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ত লেখো।', content: 'ত' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'তরমুজ কোন বর্ণের সাথে জড়িত?', content: 'ত', options: ['ণ', 'ত', 'থ', 'দ'], correctAnswer: 'ত' },
        ],
    },
    'banjanbarna2-da': {
        id: 'banjanbarna2-da', letter: 'থ', word: 'থালা', wordEn: 'Plate', emoji: '🍽️',
        color: 'from-yellow-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ থ শিখি!', voiceText: 'ভাত রাখি থালায়। থালা শব্দটি থ দিয়ে শুরু হয়। আজ আমরা থ শিখব।', content: 'থ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'থ... থালা', content: 'থালা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'থ', content: 'থ' },
            { id: 'e4', type: 'tap-correct', title: 'থ কোথায়?', voiceText: 'থ বর্ণটি খুঁজে বের করো।', content: 'থ', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'থ' },
            { id: 'e5', type: 'bubble-pop', title: 'থ ধরো!', voiceText: 'থ লেখা বুদবুদটি ফাটাও।', content: 'থ', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'থ' },
            { id: 'e6', type: 'letter-puzzle', title: 'থালা কোন বর্ণ?', voiceText: 'থালা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'থ', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'থ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'থালা শব্দটি সাজাও।', content: 'থালা', options: ['থ', 'া', 'ল', 'া'], correctAnswer: 'থালা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'থ', options: ['ত-তরমুজ', 'থ-থালা', 'দ-দরজা', 'ধ-ধান'], correctAnswer: 'থ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে থ লেখো।', content: 'থ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'থালা কোন বর্ণের সাথে জড়িত?', content: 'থ', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'থ' },
        ],
    },
}
