import type { LessonConfig } from '@/components/kids/LessonEngine'

export const banglaLessonsP4b: Record<string, LessonConfig> = {

    'bishesh-visarga': {
        id: 'bishesh-visarga', letter: 'ঃ', word: 'দুঃখ', wordEn: 'Sadness', emoji: '😢',
        color: 'from-slate-400 to-gray-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঃ শিখি!', voiceText: 'ঃ কে বলে বিসর্গ। দুঃখ শব্দে ঃ আছে। আজ আমরা ঃ শিখব।', content: 'ঃ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঃ... দুঃখ', content: 'দুঃখ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঃ', content: 'ঃ' },
            { id: 'e4', type: 'tap-correct', title: 'ঃ কোথায়?', voiceText: 'ঃ বর্ণটি খুঁজে বের করো।', content: 'ঃ', options: ['ং', 'ঃ', 'ঁ', 'ক্ষ'], correctAnswer: 'ঃ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঃ ধরো!', voiceText: 'ঃ লেখা বুদবুদটি ফাটাও।', content: 'ঃ', options: ['ং', 'ঃ', 'ঁ', 'ক্ষ'], correctAnswer: 'ঃ' },
            { id: 'e6', type: 'letter-puzzle', title: 'দুঃখ কোন বর্ণ?', voiceText: 'দুঃখ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঃ', options: ['ং', 'ঃ', 'ঁ', 'ক্ষ'], correctAnswer: 'ঃ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'দুঃখ শব্দটি সাজাও।', content: 'দুঃখ', options: ['দ', 'ু', 'ঃ', 'খ'], correctAnswer: 'দুঃখ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঃ', options: ['ং-বাংলা', 'ঃ-দুঃখ', 'ঁ-চাঁদ', 'ক্ষ-ক্ষমা'], correctAnswer: 'ঃ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঃ লেখো।', content: 'ঃ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'দুঃখ কোন বর্ণের সাথে জড়িত?', content: 'ঃ', options: ['ং', 'ঃ', 'ঁ', 'ক্ষ'], correctAnswer: 'ঃ' },
        ],
    },
    'bishesh-chandrabindu': {
        id: 'bishesh-chandrabindu', letter: 'ঁ', word: 'চাঁদ', wordEn: 'Moon', emoji: '🌙',
        color: 'from-indigo-400 to-violet-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঁ শিখি!', voiceText: 'ঁ কে বলে চন্দ্রবিন্দু। চাঁদ শব্দে ঁ আছে। আজ আমরা ঁ শিখব।', content: 'ঁ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঁ... চাঁদ', content: 'চাঁদ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঁ', content: 'ঁ' },
            { id: 'e4', type: 'tap-correct', title: 'ঁ কোথায়?', voiceText: 'ঁ বর্ণটি খুঁজে বের করো।', content: 'ঁ', options: ['ঃ', 'ঁ', 'ক্ষ', 'জ্ঞ'], correctAnswer: 'ঁ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঁ ধরো!', voiceText: 'ঁ লেখা বুদবুদটি ফাটাও।', content: 'ঁ', options: ['ঃ', 'ঁ', 'ক্ষ', 'জ্ঞ'], correctAnswer: 'ঁ' },
            { id: 'e6', type: 'letter-puzzle', title: 'চাঁদ কোন বর্ণ?', voiceText: 'চাঁদ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঁ', options: ['ঃ', 'ঁ', 'ক্ষ', 'জ্ঞ'], correctAnswer: 'ঁ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'চাঁদ শব্দটি সাজাও।', content: 'চাঁদ', options: ['চ', 'া', 'ঁ', 'দ'], correctAnswer: 'চাঁদ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঁ', options: ['ঃ-দুঃখ', 'ঁ-চাঁদ', 'ক্ষ-ক্ষমা', 'জ্ঞ-জ্ঞান'], correctAnswer: 'ঁ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঁ লেখো।', content: 'ঁ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'চাঁদ কোন বর্ণের সাথে জড়িত?', content: 'ঁ', options: ['ঃ', 'ঁ', 'ক্ষ', 'জ্ঞ'], correctAnswer: 'ঁ' },
        ],
    },
    'jukta-ksha': {
        id: 'jukta-ksha', letter: 'ক্ষ', word: 'ক্ষমা', wordEn: 'Forgiveness', emoji: '🙏',
        color: 'from-emerald-400 to-teal-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ক্ষ শিখি!', voiceText: 'ক্ষ একটি যুক্তবর্ণ। ক্ষমা শব্দটি ক্ষ দিয়ে শুরু হয়। আজ আমরা ক্ষ শিখব।', content: 'ক্ষ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ক্ষ... ক্ষমা', content: 'ক্ষমা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ক্ষ', content: 'ক্ষ' },
            { id: 'e4', type: 'tap-correct', title: 'ক্ষ কোথায়?', voiceText: 'ক্ষ খুঁজে বের করো।', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
            { id: 'e5', type: 'bubble-pop', title: 'ক্ষ ধরো!', voiceText: 'ক্ষ বুদবুদ ফাটাও।', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ক্ষমা কোন বর্ণ?', voiceText: 'ক্ষমা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ক্ষমা শব্দটি সাজাও।', content: 'ক্ষমা', options: ['ক', '্', 'ষ', 'ম', 'া'], correctAnswer: 'ক্ষমা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ক্ষ', options: ['ক্ষ-ক্ষমা', 'জ্ঞ-জ্ঞান', 'ত্র-ত্রিকোণ', 'শ্র-শ্রম'], correctAnswer: 'ক্ষ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ক্ষ লেখো।', content: 'ক্ষ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ক্ষমা কোন বর্ণ দিয়ে শুরু?', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
        ],
    },
    'jukta-gya': {
        id: 'jukta-gya', letter: 'জ্ঞ', word: 'জ্ঞান', wordEn: 'Knowledge', emoji: '📖',
        color: 'from-amber-400 to-yellow-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ জ্ঞ শিখি!', voiceText: 'জ্ঞ একটি যুক্তবর্ণ। জ্ঞান শব্দটি জ্ঞ দিয়ে শুরু হয়। আজ আমরা জ্ঞ শিখব।', content: 'জ্ঞ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'জ্ঞ... জ্ঞান', content: 'জ্ঞান' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'জ্ঞ', content: 'জ্ঞ' },
            { id: 'e4', type: 'tap-correct', title: 'জ্ঞ কোথায়?', voiceText: 'জ্ঞ খুঁজে বের করো।', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
            { id: 'e5', type: 'bubble-pop', title: 'জ্ঞ ধরো!', voiceText: 'জ্ঞ বুদবুদ ফাটাও।', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
            { id: 'e6', type: 'letter-puzzle', title: 'জ্ঞান কোন বর্ণ?', voiceText: 'জ্ঞান এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'জ্ঞান শব্দটি সাজাও।', content: 'জ্ঞান', options: ['জ', '্', 'ঞ', 'া', 'ন'], correctAnswer: 'জ্ঞান' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'জ্ঞ', options: ['ক্ষ-ক্ষমা', 'জ্ঞ-জ্ঞান', 'ত্র-ত্রিকোণ', 'শ্র-শ্রম'], correctAnswer: 'জ্ঞ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে জ্ঞ লেখো।', content: 'জ্ঞ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'জ্ঞান কোন বর্ণ দিয়ে শুরু?', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
        ],
    },
    'jukta-tra': {
        id: 'jukta-tra', letter: 'ত্র', word: 'ত্রিকোণ', wordEn: 'Triangle', emoji: '🔺',
        color: 'from-red-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ত্র শিখি!', voiceText: 'ত্র একটি যুক্তবর্ণ। ত্রিকোণ শব্দটি ত্র দিয়ে শুরু হয়। আজ আমরা ত্র শিখব।', content: 'ত্র' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ত্র... ত্রিকোণ', content: 'ত্রিকোণ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ত্র', content: 'ত্র' },
            { id: 'e4', type: 'tap-correct', title: 'ত্র কোথায়?', voiceText: 'ত্র খুঁজে বের করো।', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
            { id: 'e5', type: 'bubble-pop', title: 'ত্র ধরো!', voiceText: 'ত্র বুদবুদ ফাটাও।', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
            { id: 'e6', type: 'letter-puzzle', title: 'ত্রিকোণ কোন বর্ণ?', voiceText: 'ত্রিকোণ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ত্রিকোণ শব্দটি সাজাও।', content: 'ত্রিকোণ', options: ['ত', '্', 'র', 'ি', 'ক', 'ো', 'ণ'], correctAnswer: 'ত্রিকোণ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ত্র', options: ['ক্ষ-ক্ষমা', 'জ্ঞ-জ্ঞান', 'ত্র-ত্রিকোণ', 'শ্র-শ্রম'], correctAnswer: 'ত্র' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ত্র লেখো।', content: 'ত্র' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ত্রিকোণ কোন বর্ণ দিয়ে শুরু?', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
        ],
    },
    'jukta-shra': {
        id: 'jukta-shra', letter: 'শ্র', word: 'শ্রম', wordEn: 'Labor', emoji: '💪',
        color: 'from-orange-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ শ্র শিখি!', voiceText: 'শ্র একটি যুক্তবর্ণ। শ্রম শব্দটি শ্র দিয়ে শুরু হয়। আজ আমরা শ্র শিখব।', content: 'শ্র' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'শ্র... শ্রম', content: 'শ্রম' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'শ্র', content: 'শ্র' },
            { id: 'e4', type: 'tap-correct', title: 'শ্র কোথায়?', voiceText: 'শ্র খুঁজে বের করো।', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
            { id: 'e5', type: 'bubble-pop', title: 'শ্র ধরো!', voiceText: 'শ্র বুদবুদ ফাটাও।', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
            { id: 'e6', type: 'letter-puzzle', title: 'শ্রম কোন বর্ণ?', voiceText: 'শ্রম এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'শ্রম শব্দটি সাজাও।', content: 'শ্রম', options: ['শ', '্', 'র', 'ম'], correctAnswer: 'শ্রম' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'শ্র', options: ['ক্ষ-ক্ষমা', 'জ্ঞ-জ্ঞান', 'ত্র-ত্রিকোণ', 'শ্র-শ্রম'], correctAnswer: 'শ্র' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে শ্র লেখো।', content: 'শ্র' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'শ্রম কোন বর্ণ দিয়ে শুরু?', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
        ],
    },
    'jukta-review': {
        id: 'jukta-review', letter: '★', word: 'রিভিশন', wordEn: 'Review', emoji: '🌟',
        color: 'from-yellow-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'সব যুক্তবর্ণ রিভিশন!', voiceText: 'সব যুক্তবর্ণ একসাথে রিভিশন করি!', content: '★' },
            { id: 'e2', type: 'tap-correct', title: 'ক্ষমা কোন বর্ণ?', voiceText: 'ক্ষমা কোন বর্ণ দিয়ে শুরু?', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
            { id: 'e3', type: 'tap-correct', title: 'জ্ঞান কোন বর্ণ?', voiceText: 'জ্ঞান কোন বর্ণ দিয়ে শুরু?', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
            { id: 'e4', type: 'tap-correct', title: 'ত্রিকোণ কোন বর্ণ?', voiceText: 'ত্রিকোণ কোন বর্ণ দিয়ে শুরু?', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
            { id: 'e5', type: 'matching', title: 'সব মেলাও!', voiceText: 'যুক্তবর্ণ আর শব্দ মেলাও।', content: '★', options: ['ক্ষ-ক্ষমা', 'জ্ঞ-জ্ঞান', 'ত্র-ত্রিকোণ', 'শ্র-শ্রম'], correctAnswer: 'ক্ষ' },
            { id: 'e6', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'শ্রম কোন বর্ণ দিয়ে শুরু?', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
        ],
    },
    'boss-jukta': {
        id: 'boss-jukta', letter: '★', word: 'চূড়ান্ত Boss Quiz', wordEn: 'Final Boss', emoji: '👑',
        color: 'from-yellow-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চূড়ান্ত Boss Quiz!', voiceText: 'সব বর্ণ শেষ! এবার চূড়ান্ত পরীক্ষা!', content: '★' },
            { id: 'e2', type: 'tap-correct', title: 'অজগর কোন বর্ণ?', voiceText: 'অজগর কোন বর্ণ?', content: 'অ', options: ['অ', 'আ', 'ক', 'খ'], correctAnswer: 'অ' },
            { id: 'e3', type: 'tap-correct', title: 'কাক কোন বর্ণ?', voiceText: 'কাক কোন বর্ণ?', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
            { id: 'e4', type: 'tap-correct', title: 'ক্ষমা কোন বর্ণ?', voiceText: 'ক্ষমা কোন বর্ণ?', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
            { id: 'e5', type: 'matching', title: 'সব মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও।', content: '★', options: ['অ-অজগর', 'ক-কাক', 'ক্ষ-ক্ষমা', 'জ্ঞ-জ্ঞান'], correctAnswer: 'অ' },
            { id: 'e6', type: 'quiz', title: 'চূড়ান্ত প্রশ্ন!', voiceText: 'জ্ঞান কোন বর্ণ?', content: 'জ্ঞ', options: ['জ্ঞ', 'অ', 'ক', 'ত'], correctAnswer: 'জ্ঞ' },
        ],
    },
}
