import type { LessonConfig } from '@/components/kids/LessonEngine'

export const banglaLessonsP3b: Record<string, LessonConfig> = {

    'banjanbarna2-ma': {
        id: 'banjanbarna2-ma', letter: 'ম', word: 'মাছ', wordEn: 'Fish', emoji: '🐟',
        color: 'from-cyan-400 to-teal-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ম শিখি!', voiceText: 'পুকুরে মাছ সাঁতার কাটে। মাছ শব্দটি ম দিয়ে শুরু হয়। আজ আমরা ম শিখব।', content: 'ম' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ম... মাছ', content: 'মাছ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ম', content: 'ম' },
            { id: 'e4', type: 'tap-correct', title: 'ম কোথায়?', voiceText: 'ম বর্ণটি খুঁজে বের করো।', content: 'ম', options: ['ভ', 'ম', 'য', 'র'], correctAnswer: 'ম' },
            { id: 'e5', type: 'bubble-pop', title: 'ম ধরো!', voiceText: 'ম লেখা বুদবুদটি ফাটাও।', content: 'ম', options: ['ভ', 'ম', 'য', 'র'], correctAnswer: 'ম' },
            { id: 'e6', type: 'letter-puzzle', title: 'মাছ কোন বর্ণ?', voiceText: 'মাছ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ম', options: ['ভ', 'ম', 'য', 'র'], correctAnswer: 'ম' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'মাছ শব্দটি সাজাও।', content: 'মাছ', options: ['ম', 'া', 'ছ'], correctAnswer: 'মাছ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ম', options: ['ভ-ভালুক', 'ম-মাছ', 'য-যাত্রী', 'র-রকেট'], correctAnswer: 'ম' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ম লেখো।', content: 'ম' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'মাছ কোন বর্ণের সাথে জড়িত?', content: 'ম', options: ['ভ', 'ম', 'য', 'র'], correctAnswer: 'ম' },
        ],
    },
    'boss-banjanbarna-2': {
        id: 'boss-banjanbarna-2', letter: '★', word: 'ব্যঞ্জন Part 2 Boss', wordEn: 'Boss Quiz', emoji: '🌳',
        color: 'from-amber-400 to-orange-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'ব্যঞ্জন Part 2 Boss!', voiceText: 'প্রস্তুত? ত থেকে ম সব মনে করে খেলি!', content: '★' },
            { id: 'e2', type: 'tap-correct', title: 'তরমুজ কোন বর্ণ?', voiceText: 'তরমুজ কোন বর্ণ?', content: 'ত', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'ত' },
            { id: 'e3', type: 'tap-correct', title: 'পাখি কোন বর্ণ?', voiceText: 'পাখি কোন বর্ণ?', content: 'প', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'প' },
            { id: 'e4', type: 'tap-correct', title: 'মাছ কোন বর্ণ?', voiceText: 'মাছ কোন বর্ণ?', content: 'ম', options: ['ম', 'ব', 'ভ', 'ন'], correctAnswer: 'ম' },
            { id: 'e5', type: 'matching', title: 'সব মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও।', content: '★', options: ['ত-তরমুজ', 'প-পাখি', 'ব-বাঘ', 'ম-মাছ'], correctAnswer: 'ত' },
            { id: 'e6', type: 'quiz', title: 'চূড়ান্ত!', voiceText: 'ধান কোন বর্ণ?', content: 'ধ', options: ['ধ', 'দ', 'ন', 'ম'], correctAnswer: 'ধ' },
        ],
    },
    'banjanbarna3-ya': {
        id: 'banjanbarna3-ya', letter: 'য', word: 'যাত্রী', wordEn: 'Passenger', emoji: '🧳',
        color: 'from-violet-400 to-purple-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ য শিখি!', voiceText: 'ট্রেনে যাত্রী চড়ে। যাত্রী শব্দটি য দিয়ে শুরু হয়। আজ আমরা য শিখব।', content: 'য' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'য... যাত্রী', content: 'যাত্রী' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'য', content: 'য' },
            { id: 'e4', type: 'tap-correct', title: 'য কোথায়?', voiceText: 'য বর্ণটি খুঁজে বের করো।', content: 'য', options: ['ম', 'য', 'র', 'ল'], correctAnswer: 'য' },
            { id: 'e5', type: 'bubble-pop', title: 'য ধরো!', voiceText: 'য লেখা বুদবুদটি ফাটাও।', content: 'য', options: ['ম', 'য', 'র', 'ল'], correctAnswer: 'য' },
            { id: 'e6', type: 'letter-puzzle', title: 'যাত্রী কোন বর্ণ?', voiceText: 'যাত্রী এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'য', options: ['ম', 'য', 'র', 'ল'], correctAnswer: 'য' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'যাত্রী শব্দটি সাজাও।', content: 'যাত্রী', options: ['য', 'া', 'ত', '্', 'র', 'ী'], correctAnswer: 'যাত্রী' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'য', options: ['ম-মাছ', 'য-যাত্রী', 'র-রকেট', 'ল-লাল'], correctAnswer: 'য' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে য লেখো।', content: 'য' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'যাত্রী কোন বর্ণের সাথে জড়িত?', content: 'য', options: ['ম', 'য', 'র', 'ল'], correctAnswer: 'য' },
        ],
    },
    'banjanbarna3-ra': {
        id: 'banjanbarna3-ra', letter: 'র', word: 'রকেট', wordEn: 'Rocket', emoji: '🚀',
        color: 'from-red-400 to-orange-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ র শিখি!', voiceText: 'রকেট মহাকাশে উড়ে যায়। রকেট শব্দটি র দিয়ে শুরু হয়। আজ আমরা র শিখব।', content: 'র' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'র... রকেট', content: 'রকেট' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'র', content: 'র' },
            { id: 'e4', type: 'tap-correct', title: 'র কোথায়?', voiceText: 'র বর্ণটি খুঁজে বের করো।', content: 'র', options: ['য', 'র', 'ল', 'ষ'], correctAnswer: 'র' },
            { id: 'e5', type: 'bubble-pop', title: 'র ধরো!', voiceText: 'র লেখা বুদবুদটি ফাটাও।', content: 'র', options: ['য', 'র', 'ল', 'ষ'], correctAnswer: 'র' },
            { id: 'e6', type: 'letter-puzzle', title: 'রকেট কোন বর্ণ?', voiceText: 'রকেট এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'র', options: ['য', 'র', 'ল', 'ষ'], correctAnswer: 'র' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'রকেট শব্দটি সাজাও।', content: 'রকেট', options: ['র', 'ক', 'ে', 'ট'], correctAnswer: 'রকেট' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'র', options: ['য-যাত্রী', 'র-রকেট', 'ল-লাল', 'ষ-ষাঁড়'], correctAnswer: 'র' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে র লেখো।', content: 'র' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'রকেট কোন বর্ণের সাথে জড়িত?', content: 'র', options: ['য', 'র', 'ল', 'ষ'], correctAnswer: 'র' },
        ],
    },
    'banjanbarna3-la': {
        id: 'banjanbarna3-la', letter: 'ল', word: 'লাল', wordEn: 'Red', emoji: '🔴',
        color: 'from-red-500 to-rose-600', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ল শিখি!', voiceText: 'লাল রঙের ফুল সুন্দর। লাল শব্দটি ল দিয়ে শুরু হয়। আজ আমরা ল শিখব।', content: 'ল' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ল... লাল', content: 'লাল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ল', content: 'ল' },
            { id: 'e4', type: 'tap-correct', title: 'ল কোথায়?', voiceText: 'ল বর্ণটি খুঁজে বের করো।', content: 'ল', options: ['র', 'ল', 'ষ', 'শ'], correctAnswer: 'ল' },
            { id: 'e5', type: 'bubble-pop', title: 'ল ধরো!', voiceText: 'ল লেখা বুদবুদটি ফাটাও।', content: 'ল', options: ['র', 'ল', 'ষ', 'শ'], correctAnswer: 'ল' },
            { id: 'e6', type: 'letter-puzzle', title: 'লাল কোন বর্ণ?', voiceText: 'লাল এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ল', options: ['র', 'ল', 'ষ', 'শ'], correctAnswer: 'ল' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'লাল শব্দটি সাজাও।', content: 'লাল', options: ['ল', 'া', 'ল'], correctAnswer: 'লাল' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ল', options: ['র-রকেট', 'ল-লাল', 'ষ-ষাঁড়', 'শ-শাপলা'], correctAnswer: 'ল' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ল লেখো।', content: 'ল' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'লাল কোন বর্ণের সাথে জড়িত?', content: 'ল', options: ['র', 'ল', 'ষ', 'শ'], correctAnswer: 'ল' },
        ],
    },
    'banjanbarna3-sha2': {
        id: 'banjanbarna3-sha2', letter: 'ষ', word: 'ষাঁড়', wordEn: 'Bull', emoji: '🐂',
        color: 'from-amber-500 to-yellow-600', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ষ শিখি!', voiceText: 'ষাঁড় শক্তিশালী পশু। ষাঁড় শব্দটি ষ দিয়ে শুরু হয়। আজ আমরা ষ শিখব।', content: 'ষ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ষ... ষাঁড়', content: 'ষাঁড়' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ষ', content: 'ষ' },
            { id: 'e4', type: 'tap-correct', title: 'ষ কোথায়?', voiceText: 'ষ বর্ণটি খুঁজে বের করো।', content: 'ষ', options: ['ল', 'ষ', 'শ', 'স'], correctAnswer: 'ষ' },
            { id: 'e5', type: 'bubble-pop', title: 'ষ ধরো!', voiceText: 'ষ লেখা বুদবুদটি ফাটাও।', content: 'ষ', options: ['ল', 'ষ', 'শ', 'স'], correctAnswer: 'ষ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ষাঁড় কোন বর্ণ?', voiceText: 'ষাঁড় এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ষ', options: ['ল', 'ষ', 'শ', 'স'], correctAnswer: 'ষ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ষাঁড় শব্দটি সাজাও।', content: 'ষাঁড়', options: ['ষ', 'া', 'ঁ', 'ড', '়'], correctAnswer: 'ষাঁড়' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ষ', options: ['ল-লাল', 'ষ-ষাঁড়', 'শ-শাপলা', 'স-সাপ'], correctAnswer: 'ষ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ষ লেখো।', content: 'ষ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ষাঁড় কোন বর্ণের সাথে জড়িত?', content: 'ষ', options: ['ল', 'ষ', 'শ', 'স'], correctAnswer: 'ষ' },
        ],
    },
    'banjanbarna3-sha': {
        id: 'banjanbarna3-sha', letter: 'শ', word: 'শাপলা', wordEn: 'Water lily', emoji: '🪷',
        color: 'from-pink-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ শ শিখি!', voiceText: 'পুকুরে শাপলা ফোটে। শাপলা শব্দটি শ দিয়ে শুরু হয়। আজ আমরা শ শিখব।', content: 'শ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'শ... শাপলা', content: 'শাপলা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'শ', content: 'শ' },
            { id: 'e4', type: 'tap-correct', title: 'শ কোথায়?', voiceText: 'শ বর্ণটি খুঁজে বের করো।', content: 'শ', options: ['ষ', 'শ', 'স', 'হ'], correctAnswer: 'শ' },
            { id: 'e5', type: 'bubble-pop', title: 'শ ধরো!', voiceText: 'শ লেখা বুদবুদটি ফাটাও।', content: 'শ', options: ['ষ', 'শ', 'স', 'হ'], correctAnswer: 'শ' },
            { id: 'e6', type: 'letter-puzzle', title: 'শাপলা কোন বর্ণ?', voiceText: 'শাপলা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'শ', options: ['ষ', 'শ', 'স', 'হ'], correctAnswer: 'শ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'শাপলা শব্দটি সাজাও।', content: 'শাপলা', options: ['শ', 'া', 'প', 'ল', 'া'], correctAnswer: 'শাপলা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'শ', options: ['ষ-ষাঁড়', 'শ-শাপলা', 'স-সাপ', 'হ-হাতি'], correctAnswer: 'শ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে শ লেখো।', content: 'শ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'শাপলা কোন বর্ণের সাথে জড়িত?', content: 'শ', options: ['ষ', 'শ', 'স', 'হ'], correctAnswer: 'শ' },
        ],
    },
    'banjanbarna3-sa': {
        id: 'banjanbarna3-sa', letter: 'স', word: 'সাপ', wordEn: 'Snake', emoji: '🐍',
        color: 'from-green-500 to-emerald-600', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ স শিখি!', voiceText: 'সাপ লম্বা করে হামাগুড়ি দেয়। সাপ শব্দটি স দিয়ে শুরু হয়। আজ আমরা স শিখব।', content: 'স' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'স... সাপ', content: 'সাপ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'স', content: 'স' },
            { id: 'e4', type: 'tap-correct', title: 'স কোথায়?', voiceText: 'স বর্ণটি খুঁজে বের করো।', content: 'স', options: ['শ', 'স', 'হ', 'ড়'], correctAnswer: 'স' },
            { id: 'e5', type: 'bubble-pop', title: 'স ধরো!', voiceText: 'স লেখা বুদবুদটি ফাটাও।', content: 'স', options: ['শ', 'স', 'হ', 'ড়'], correctAnswer: 'স' },
            { id: 'e6', type: 'letter-puzzle', title: 'সাপ কোন বর্ণ?', voiceText: 'সাপ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'স', options: ['শ', 'স', 'হ', 'ড়'], correctAnswer: 'স' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'সাপ শব্দটি সাজাও।', content: 'সাপ', options: ['স', 'া', 'প'], correctAnswer: 'সাপ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'স', options: ['শ-শাপলা', 'স-সাপ', 'হ-হাতি', 'ড়-গাড়ি'], correctAnswer: 'স' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে স লেখো।', content: 'স' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'সাপ কোন বর্ণের সাথে জড়িত?', content: 'স', options: ['শ', 'স', 'হ', 'ড়'], correctAnswer: 'স' },
        ],
    },
}
