import type { LessonConfig } from '@/components/kids/LessonEngine'

export const banglaLessonsP1c: Record<string, LessonConfig> = {

    'swarabarna-o': {
        id: 'swarabarna-o', letter: 'ও', word: 'ওল', wordEn: 'Yam', emoji: '🥔',
        color: 'from-lime-400 to-green-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ও শিখি!', voiceText: 'ওল একটি সবজি। ওল শব্দটি ও দিয়ে শুরু হয়। আজ আমরা ও শিখব।', content: 'ও' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ও... ওল', content: 'ওল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ও', content: 'ও' },
            { id: 'e4', type: 'tap-correct', title: 'ও কোথায়?', voiceText: 'ও বর্ণটি খুঁজে বের করো।', content: 'ও', options: ['ঐ', 'ও', 'ঔ', 'অ'], correctAnswer: 'ও' },
            { id: 'e5', type: 'bubble-pop', title: 'ও ধরো!', voiceText: 'ও লেখা বুদবুদটি ফাটাও।', content: 'ও', options: ['ঐ', 'ও', 'ঔ', 'অ'], correctAnswer: 'ও' },
            { id: 'e6', type: 'letter-puzzle', title: 'ওল কোন বর্ণ?', voiceText: 'ওল এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ও', options: ['ঐ', 'ও', 'ঔ', 'অ'], correctAnswer: 'ও' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ওল শব্দটি সাজাও।', content: 'ওল', options: ['ও', 'ল'], correctAnswer: 'ওল' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ও', options: ['ঐ-ঐরাবত', 'ও-ওল', 'ঔ-ঔষধ', 'অ-অজগর'], correctAnswer: 'ও' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ও লেখো।', content: 'ও' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ওল কোন বর্ণের সাথে জড়িত?', content: 'ও', options: ['ঐ', 'ও', 'ঔ', 'অ'], correctAnswer: 'ও' },
        ],
    },
    'swarabarna-ou': {
        id: 'swarabarna-ou', letter: 'ঔ', word: 'ঔষধ', wordEn: 'Medicine', emoji: '💊',
        color: 'from-teal-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঔ শিখি!', voiceText: 'অসুস্থ হলে ঔষধ খাই। ঔষধ শব্দটি ঔ দিয়ে শুরু হয়। আজ আমরা ঔ শিখব।', content: 'ঔ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঔ... ঔষধ', content: 'ঔষধ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঔ', content: 'ঔ' },
            { id: 'e4', type: 'tap-correct', title: 'ঔ কোথায়?', voiceText: 'ঔ বর্ণটি খুঁজে বের করো।', content: 'ঔ', options: ['ও', 'ঔ', 'অ', 'আ'], correctAnswer: 'ঔ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঔ ধরো!', voiceText: 'ঔ লেখা বুদবুদটি ফাটাও।', content: 'ঔ', options: ['ও', 'ঔ', 'অ', 'আ'], correctAnswer: 'ঔ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঔষধ কোন বর্ণ?', voiceText: 'ঔষধ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঔ', options: ['ও', 'ঔ', 'অ', 'আ'], correctAnswer: 'ঔ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঔষধ শব্দটি সাজাও।', content: 'ঔষধ', options: ['ঔ', 'ষ', 'ধ'], correctAnswer: 'ঔষধ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঔ', options: ['ও-ওল', 'ঔ-ঔষধ', 'অ-অজগর', 'আ-আম'], correctAnswer: 'ঔ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঔ লেখো।', content: 'ঔ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঔষধ কোন বর্ণের সাথে জড়িত?', content: 'ঔ', options: ['ও', 'ঔ', 'অ', 'আ'], correctAnswer: 'ঔ' },
        ],
    },
    'boss-swarabarna': {
        id: 'boss-swarabarna', letter: '★', word: 'স্বরবর্ণ Boss Quiz', wordEn: 'Boss Quiz', emoji: '🌱',
        color: 'from-blue-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'স্বরবর্ণ Boss Quiz!', voiceText: 'প্রস্তুত? এবার সব স্বরবর্ণ মনে করে খেলি!', content: '★' },
            { id: 'e2', type: 'tap-correct', title: 'অজগর কোন বর্ণ?', voiceText: 'অজগর কোন বর্ণ?', content: 'অ', options: ['অ', 'আ', 'ই', 'ঈ'], correctAnswer: 'অ' },
            { id: 'e3', type: 'tap-correct', title: 'আম কোন বর্ণ?', voiceText: 'আম কোন বর্ণ?', content: 'আ', options: ['আ', 'ই', 'ঈ', 'উ'], correctAnswer: 'আ' },
            { id: 'e4', type: 'tap-correct', title: 'ইলিশ কোন বর্ণ?', voiceText: 'ইলিশ কোন বর্ণ?', content: 'ই', options: ['ই', 'ঈ', 'উ', 'ঊ'], correctAnswer: 'ই' },
            { id: 'e5', type: 'tap-correct', title: 'ঈগল কোন বর্ণ?', voiceText: 'ঈগল কোন বর্ণ?', content: 'ঈ', options: ['ঈ', 'উ', 'ঊ', 'ঋ'], correctAnswer: 'ঈ' },
            { id: 'e6', type: 'matching', title: 'সব মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও।', content: '★', options: ['অ-অজগর', 'আ-আম', 'ই-ইলিশ', 'ঈ-ঈগল'], correctAnswer: 'অ' },
            { id: 'e7', type: 'quiz', title: 'চূড়ান্ত!', voiceText: 'ঔষধ কোন বর্ণ?', content: 'ঔ', options: ['ঔ', 'অ', 'আ', 'ই'], correctAnswer: 'ঔ' },
        ],
    },
    'banjonborno-ka': {
        id: 'banjonborno-ka', letter: 'ক', word: 'কাক', wordEn: 'Crow', emoji: '🐦',
        color: 'from-slate-500 to-gray-700', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ক শিখি!', voiceText: 'সকালে কাক কা কা করে ডাকছে। কাক শব্দটি ক দিয়ে শুরু হয়।', content: 'ক' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ক... কাক', content: 'কাক' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ক', content: 'ক' },
            { id: 'e4', type: 'tap-correct', title: 'ক কোথায়?', voiceText: 'ক বর্ণটি খুঁজে বের করো।', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
            { id: 'e5', type: 'bubble-pop', title: 'ক ধরো!', voiceText: 'ক লেখা বুদবুদটি ফাটাও।', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
            { id: 'e6', type: 'letter-puzzle', title: 'কাক কোন বর্ণ?', voiceText: 'কাকের প্রথম বর্ণটি বেছে নাও।', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'কাক শব্দটি সাজাও।', content: 'কাক', options: ['ক', 'া', 'ক'], correctAnswer: 'কাক' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলাও।', content: 'ক', options: ['ক-কাক', 'খ-খরগোশ', 'গ-গরু', 'ঘ-ঘড়ি'], correctAnswer: 'ক' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'সুন্দর করে ক লেখো।', content: 'ক' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'কাক কোন বর্ণ?', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
        ],
    },
    'banjonborno-kha': {
        id: 'banjonborno-kha', letter: 'খ', word: 'খরগোশ', wordEn: 'Rabbit', emoji: '🐇',
        color: 'from-pink-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ খ শিখি!', voiceText: 'খরগোশ দৌড়াতে ভালোবাসে। খরগোশ শব্দটি খ দিয়ে শুরু হয়।', content: 'খ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'খ... খরগোশ', content: 'খরগোশ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'খ', content: 'খ' },
            { id: 'e4', type: 'tap-correct', title: 'খ কোথায়?', voiceText: 'খ বর্ণটি খুঁজে বের করো।', content: 'খ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'খ' },
            { id: 'e5', type: 'bubble-pop', title: 'খ ধরো!', voiceText: 'খ লেখা বুদবুদটি ফাটাও।', content: 'খ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'খ' },
            { id: 'e6', type: 'letter-puzzle', title: 'খরগোশ কোন বর্ণ?', voiceText: 'খরগোশের প্রথম বর্ণটি বেছে নাও।', content: 'খ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'খ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'খরগোশ শব্দটি সাজাও।', content: 'খরগোশ', options: ['খ', 'র', 'গ', 'ো', 'শ'], correctAnswer: 'খরগোশ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলাও।', content: 'খ', options: ['ক-কাক', 'খ-খরগোশ', 'গ-গরু', 'ঘ-ঘড়ি'], correctAnswer: 'খ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'সুন্দর করে খ লেখো।', content: 'খ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'খরগোশ কোন বর্ণ?', content: 'খ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'খ' },
        ],
    },
    'banjonborno-ga': {
        id: 'banjonborno-ga', letter: 'গ', word: 'গরু', wordEn: 'Cow', emoji: '🐄',
        color: 'from-amber-500 to-orange-600', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ গ শিখি!', voiceText: 'গরু আমাদের দুধ দেয়। গরু শব্দটি গ দিয়ে শুরু হয়।', content: 'গ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'গ... গরু', content: 'গরু' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'গ', content: 'গ' },
            { id: 'e4', type: 'tap-correct', title: 'গ কোথায়?', voiceText: 'গ বর্ণটি খুঁজে বের করো।', content: 'গ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'গ' },
            { id: 'e5', type: 'bubble-pop', title: 'গ ধরো!', voiceText: 'গ লেখা বুদবুদটি ফাটাও।', content: 'গ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'গ' },
            { id: 'e6', type: 'letter-puzzle', title: 'গরু কোন বর্ণ?', voiceText: 'গরুর প্রথম বর্ণটি বেছে নাও।', content: 'গ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'গ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'গরু শব্দটি সাজাও।', content: 'গরু', options: ['গ', 'র', 'ু'], correctAnswer: 'গরু' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলাও।', content: 'গ', options: ['ক-কাক', 'খ-খরগোশ', 'গ-গরু', 'ঘ-ঘড়ি'], correctAnswer: 'গ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'সুন্দর করে গ লেখো।', content: 'গ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'গরু কোন বর্ণ?', content: 'গ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'গ' },
        ],
    },
}
