import type { LessonConfig } from '@/components/kids/LessonEngine'

export const banglaLessonsP3a: Record<string, LessonConfig> = {

    'banjanbarna2-dha': {
        id: 'banjanbarna2-dha', letter: 'দ', word: 'দরজা', wordEn: 'Door', emoji: '🚪',
        color: 'from-brown-400 to-amber-600', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ দ শিখি!', voiceText: 'দরজা খুলে ঘরে ঢুকি। দরজা শব্দটি দ দিয়ে শুরু হয়। আজ আমরা দ শিখব।', content: 'দ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'দ... দরজা', content: 'দরজা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'দ', content: 'দ' },
            { id: 'e4', type: 'tap-correct', title: 'দ কোথায়?', voiceText: 'দ বর্ণটি খুঁজে বের করো।', content: 'দ', options: ['থ', 'দ', 'ধ', 'ন'], correctAnswer: 'দ' },
            { id: 'e5', type: 'bubble-pop', title: 'দ ধরো!', voiceText: 'দ লেখা বুদবুদটি ফাটাও।', content: 'দ', options: ['থ', 'দ', 'ধ', 'ন'], correctAnswer: 'দ' },
            { id: 'e6', type: 'letter-puzzle', title: 'দরজা কোন বর্ণ?', voiceText: 'দরজা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'দ', options: ['থ', 'দ', 'ধ', 'ন'], correctAnswer: 'দ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'দরজা শব্দটি সাজাও।', content: 'দরজা', options: ['দ', 'র', 'জ', 'া'], correctAnswer: 'দরজা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'দ', options: ['থ-থালা', 'দ-দরজা', 'ধ-ধান', 'ন-নৌকা'], correctAnswer: 'দ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে দ লেখো।', content: 'দ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'দরজা কোন বর্ণের সাথে জড়িত?', content: 'দ', options: ['থ', 'দ', 'ধ', 'ন'], correctAnswer: 'দ' },
        ],
    },
    'banjanbarna2-dhha': {
        id: 'banjanbarna2-dhha', letter: 'ধ', word: 'ধান', wordEn: 'Paddy', emoji: '🌾',
        color: 'from-yellow-400 to-lime-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ধ শিখি!', voiceText: 'ক্ষেতে সোনালি ধান দোলে। ধান শব্দটি ধ দিয়ে শুরু হয়। আজ আমরা ধ শিখব।', content: 'ধ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ধ... ধান', content: 'ধান' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ধ', content: 'ধ' },
            { id: 'e4', type: 'tap-correct', title: 'ধ কোথায়?', voiceText: 'ধ বর্ণটি খুঁজে বের করো।', content: 'ধ', options: ['দ', 'ধ', 'ন', 'প'], correctAnswer: 'ধ' },
            { id: 'e5', type: 'bubble-pop', title: 'ধ ধরো!', voiceText: 'ধ লেখা বুদবুদটি ফাটাও।', content: 'ধ', options: ['দ', 'ধ', 'ন', 'প'], correctAnswer: 'ধ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ধান কোন বর্ণ?', voiceText: 'ধান এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ধ', options: ['দ', 'ধ', 'ন', 'প'], correctAnswer: 'ধ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ধান শব্দটি সাজাও।', content: 'ধান', options: ['ধ', 'া', 'ন'], correctAnswer: 'ধান' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ধ', options: ['দ-দরজা', 'ধ-ধান', 'ন-নৌকা', 'প-পাখি'], correctAnswer: 'ধ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ধ লেখো।', content: 'ধ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ধান কোন বর্ণের সাথে জড়িত?', content: 'ধ', options: ['দ', 'ধ', 'ন', 'প'], correctAnswer: 'ধ' },
        ],
    },
    'banjanbarna2-na': {
        id: 'banjanbarna2-na', letter: 'ন', word: 'নৌকা', wordEn: 'Boat', emoji: '⛵',
        color: 'from-blue-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ন শিখি!', voiceText: 'নদীতে নৌকা ভাসে। নৌকা শব্দটি ন দিয়ে শুরু হয়। আজ আমরা ন শিখব।', content: 'ন' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ন... নৌকা', content: 'নৌকা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ন', content: 'ন' },
            { id: 'e4', type: 'tap-correct', title: 'ন কোথায়?', voiceText: 'ন বর্ণটি খুঁজে বের করো।', content: 'ন', options: ['ধ', 'ন', 'প', 'ফ'], correctAnswer: 'ন' },
            { id: 'e5', type: 'bubble-pop', title: 'ন ধরো!', voiceText: 'ন লেখা বুদবুদটি ফাটাও।', content: 'ন', options: ['ধ', 'ন', 'প', 'ফ'], correctAnswer: 'ন' },
            { id: 'e6', type: 'letter-puzzle', title: 'নৌকা কোন বর্ণ?', voiceText: 'নৌকা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ন', options: ['ধ', 'ন', 'প', 'ফ'], correctAnswer: 'ন' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'নৌকা শব্দটি সাজাও।', content: 'নৌকা', options: ['ন', 'ৌ', 'ক', 'া'], correctAnswer: 'নৌকা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ন', options: ['ধ-ধান', 'ন-নৌকা', 'প-পাখি', 'ফ-ফুল'], correctAnswer: 'ন' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ন লেখো।', content: 'ন' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'নৌকা কোন বর্ণের সাথে জড়িত?', content: 'ন', options: ['ধ', 'ন', 'প', 'ফ'], correctAnswer: 'ন' },
        ],
    },
    'banjanbarna2-pa': {
        id: 'banjanbarna2-pa', letter: 'প', word: 'পাখি', wordEn: 'Bird', emoji: '🐦',
        color: 'from-sky-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ প শিখি!', voiceText: 'আকাশে পাখি উড়ে বেড়ায়। পাখি শব্দটি প দিয়ে শুরু হয়। আজ আমরা প শিখব।', content: 'প' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'প... পাখি', content: 'পাখি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'প', content: 'প' },
            { id: 'e4', type: 'tap-correct', title: 'প কোথায়?', voiceText: 'প বর্ণটি খুঁজে বের করো।', content: 'প', options: ['ন', 'প', 'ফ', 'ব'], correctAnswer: 'প' },
            { id: 'e5', type: 'bubble-pop', title: 'প ধরো!', voiceText: 'প লেখা বুদবুদটি ফাটাও।', content: 'প', options: ['ন', 'প', 'ফ', 'ব'], correctAnswer: 'প' },
            { id: 'e6', type: 'letter-puzzle', title: 'পাখি কোন বর্ণ?', voiceText: 'পাখি এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'প', options: ['ন', 'প', 'ফ', 'ব'], correctAnswer: 'প' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'পাখি শব্দটি সাজাও।', content: 'পাখি', options: ['প', 'া', 'খ', 'ি'], correctAnswer: 'পাখি' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'প', options: ['ন-নৌকা', 'প-পাখি', 'ফ-ফুল', 'ব-বাঘ'], correctAnswer: 'প' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে প লেখো।', content: 'প' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'পাখি কোন বর্ণের সাথে জড়িত?', content: 'প', options: ['ন', 'প', 'ফ', 'ব'], correctAnswer: 'প' },
        ],
    },
    'banjanbarna2-pha': {
        id: 'banjanbarna2-pha', letter: 'ফ', word: 'ফুল', wordEn: 'Flower', emoji: '🌸',
        color: 'from-pink-400 to-rose-400', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ফ শিখি!', voiceText: 'বাগানে রঙিন ফুল ফোটে। ফুল শব্দটি ফ দিয়ে শুরু হয়। আজ আমরা ফ শিখব।', content: 'ফ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ফ... ফুল', content: 'ফুল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ফ', content: 'ফ' },
            { id: 'e4', type: 'tap-correct', title: 'ফ কোথায়?', voiceText: 'ফ বর্ণটি খুঁজে বের করো।', content: 'ফ', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'ফ' },
            { id: 'e5', type: 'bubble-pop', title: 'ফ ধরো!', voiceText: 'ফ লেখা বুদবুদটি ফাটাও।', content: 'ফ', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'ফ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ফুল কোন বর্ণ?', voiceText: 'ফুল এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ফ', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'ফ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ফুল শব্দটি সাজাও।', content: 'ফুল', options: ['ফ', 'ু', 'ল'], correctAnswer: 'ফুল' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ফ', options: ['প-পাখি', 'ফ-ফুল', 'ব-বাঘ', 'ভ-ভালুক'], correctAnswer: 'ফ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ফ লেখো।', content: 'ফ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ফুল কোন বর্ণের সাথে জড়িত?', content: 'ফ', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'ফ' },
        ],
    },
    'banjanbarna2-ba': {
        id: 'banjanbarna2-ba', letter: 'ব', word: 'বাঘ', wordEn: 'Tiger', emoji: '🐯',
        color: 'from-orange-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ব শিখি!', voiceText: 'জঙ্গলে বাঘ রাজার মতো ঘোরে। বাঘ শব্দটি ব দিয়ে শুরু হয়। আজ আমরা ব শিখব।', content: 'ব' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ব... বাঘ', content: 'বাঘ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ব', content: 'ব' },
            { id: 'e4', type: 'tap-correct', title: 'ব কোথায়?', voiceText: 'ব বর্ণটি খুঁজে বের করো।', content: 'ব', options: ['ফ', 'ব', 'ভ', 'ম'], correctAnswer: 'ব' },
            { id: 'e5', type: 'bubble-pop', title: 'ব ধরো!', voiceText: 'ব লেখা বুদবুদটি ফাটাও।', content: 'ব', options: ['ফ', 'ব', 'ভ', 'ম'], correctAnswer: 'ব' },
            { id: 'e6', type: 'letter-puzzle', title: 'বাঘ কোন বর্ণ?', voiceText: 'বাঘ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ব', options: ['ফ', 'ব', 'ভ', 'ম'], correctAnswer: 'ব' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'বাঘ শব্দটি সাজাও।', content: 'বাঘ', options: ['ব', 'া', 'ঘ'], correctAnswer: 'বাঘ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ব', options: ['ফ-ফুল', 'ব-বাঘ', 'ভ-ভালুক', 'ম-মাছ'], correctAnswer: 'ব' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ব লেখো।', content: 'ব' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'বাঘ কোন বর্ণের সাথে জড়িত?', content: 'ব', options: ['ফ', 'ব', 'ভ', 'ম'], correctAnswer: 'ব' },
        ],
    },
    'banjanbarna2-bha': {
        id: 'banjanbarna2-bha', letter: 'ভ', word: 'ভালুক', wordEn: 'Bear', emoji: '🐻',
        color: 'from-amber-500 to-orange-600', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ভ শিখি!', voiceText: 'ভালুক মধু খেতে ভালোবাসে। ভালুক শব্দটি ভ দিয়ে শুরু হয়। আজ আমরা ভ শিখব।', content: 'ভ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ভ... ভালুক', content: 'ভালুক' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ভ', content: 'ভ' },
            { id: 'e4', type: 'tap-correct', title: 'ভ কোথায়?', voiceText: 'ভ বর্ণটি খুঁজে বের করো।', content: 'ভ', options: ['ব', 'ভ', 'ম', 'য'], correctAnswer: 'ভ' },
            { id: 'e5', type: 'bubble-pop', title: 'ভ ধরো!', voiceText: 'ভ লেখা বুদবুদটি ফাটাও।', content: 'ভ', options: ['ব', 'ভ', 'ম', 'য'], correctAnswer: 'ভ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ভালুক কোন বর্ণ?', voiceText: 'ভালুক এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ভ', options: ['ব', 'ভ', 'ম', 'য'], correctAnswer: 'ভ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ভালুক শব্দটি সাজাও।', content: 'ভালুক', options: ['ভ', 'া', 'ল', 'ু', 'ক'], correctAnswer: 'ভালুক' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ভ', options: ['ব-বাঘ', 'ভ-ভালুক', 'ম-মাছ', 'য-যাত্রী'], correctAnswer: 'ভ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ভ লেখো।', content: 'ভ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ভালুক কোন বর্ণের সাথে জড়িত?', content: 'ভ', options: ['ব', 'ভ', 'ম', 'য'], correctAnswer: 'ভ' },
        ],
    },
}
