import type { LessonConfig } from '@/components/kids/LessonEngine'

export const banglaLessonsP1b: Record<string, LessonConfig> = {

    'swarabarna-u': {
        id: 'swarabarna-u', letter: 'উ', word: 'উট', wordEn: 'Camel', emoji: '🐪',
        color: 'from-orange-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ উ শিখি!', voiceText: 'মরুভূমিতে উট মানুষের বন্ধু। উট শব্দটি উ দিয়ে শুরু হয়। আজ আমরা উ শিখব।', content: 'উ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'উ... উট', content: 'উট' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'উ', content: 'উ' },
            { id: 'e4', type: 'tap-correct', title: 'উ কোথায়?', voiceText: 'উ বর্ণটি খুঁজে বের করো।', content: 'উ', options: ['ঈ', 'উ', 'ঊ', 'এ'], correctAnswer: 'উ' },
            { id: 'e5', type: 'bubble-pop', title: 'উ ধরো!', voiceText: 'উ লেখা বুদবুদটি ফাটাও।', content: 'উ', options: ['ঈ', 'উ', 'ঊ', 'এ'], correctAnswer: 'উ' },
            { id: 'e6', type: 'letter-puzzle', title: 'উট কোন বর্ণ?', voiceText: 'উট এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'উ', options: ['ঈ', 'উ', 'ঊ', 'এ'], correctAnswer: 'উ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'উট শব্দটি সাজাও।', content: 'উট', options: ['উ', 'ট'], correctAnswer: 'উট' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'উ', options: ['ঈ-ঈগল', 'উ-উট', 'ঊ-ঊষা', 'এ-একতারা'], correctAnswer: 'উ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে উ লেখো।', content: 'উ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'উট কোন বর্ণের সাথে জড়িত?', content: 'উ', options: ['ঈ', 'উ', 'ঊ', 'এ'], correctAnswer: 'উ' },
        ],
    },
    'swarabarna-uu': {
        id: 'swarabarna-uu', letter: 'ঊ', word: 'ঊষা', wordEn: 'Dawn', emoji: '🌅',
        color: 'from-rose-400 to-pink-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঊ শিখি!', voiceText: 'সকালের প্রথম আলো ঊষা। ঊষা শব্দটি ঊ দিয়ে শুরু হয়। আজ আমরা ঊ শিখব।', content: 'ঊ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঊ... ঊষা', content: 'ঊষা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঊ', content: 'ঊ' },
            { id: 'e4', type: 'tap-correct', title: 'ঊ কোথায়?', voiceText: 'ঊ বর্ণটি খুঁজে বের করো।', content: 'ঊ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঊ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঊ ধরো!', voiceText: 'ঊ লেখা বুদবুদটি ফাটাও।', content: 'ঊ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঊ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঊষা কোন বর্ণ?', voiceText: 'ঊষা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঊ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঊ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঊষা শব্দটি সাজাও।', content: 'ঊষা', options: ['ঊ', 'ষ', 'া'], correctAnswer: 'ঊষা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঊ', options: ['উ-উট', 'ঊ-ঊষা', 'ঋ-ঋষি', 'এ-একতারা'], correctAnswer: 'ঊ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঊ লেখো।', content: 'ঊ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঊষা কোন বর্ণের সাথে জড়িত?', content: 'ঊ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঊ' },
        ],
    },
    'swarabarna-ri': {
        id: 'swarabarna-ri', letter: 'ঋ', word: 'ঋষি', wordEn: 'Sage', emoji: '🧙',
        color: 'from-violet-400 to-purple-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঋ শিখি!', voiceText: 'জ্ঞানী ঋষি গভীর ধ্যানে বসেন। ঋষি শব্দটি ঋ দিয়ে শুরু হয়। আজ আমরা ঋ শিখব।', content: 'ঋ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঋ... ঋষি', content: 'ঋষি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঋ', content: 'ঋ' },
            { id: 'e4', type: 'tap-correct', title: 'ঋ কোথায়?', voiceText: 'ঋ বর্ণটি খুঁজে বের করো।', content: 'ঋ', options: ['ঊ', 'ঋ', 'এ', 'ঐ'], correctAnswer: 'ঋ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঋ ধরো!', voiceText: 'ঋ লেখা বুদবুদটি ফাটাও।', content: 'ঋ', options: ['ঊ', 'ঋ', 'এ', 'ঐ'], correctAnswer: 'ঋ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঋষি কোন বর্ণ?', voiceText: 'ঋষি এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঋ', options: ['ঊ', 'ঋ', 'এ', 'ঐ'], correctAnswer: 'ঋ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঋষি শব্দটি সাজাও।', content: 'ঋষি', options: ['ঋ', 'ষ', 'ি'], correctAnswer: 'ঋষি' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঋ', options: ['ঊ-ঊষা', 'ঋ-ঋষি', 'এ-একতারা', 'ঐ-ঐরাবত'], correctAnswer: 'ঋ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঋ লেখো।', content: 'ঋ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঋষি কোন বর্ণের সাথে জড়িত?', content: 'ঋ', options: ['ঊ', 'ঋ', 'এ', 'ঐ'], correctAnswer: 'ঋ' },
        ],
    },
    'swarabarna-e': {
        id: 'swarabarna-e', letter: 'এ', word: 'একতারা', wordEn: 'Ektara', emoji: '🎸',
        color: 'from-amber-400 to-yellow-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ এ শিখি!', voiceText: 'বাউলের একতারা বাজে মিষ্টি সুরে। একতারা শব্দটি এ দিয়ে শুরু হয়। আজ আমরা এ শিখব।', content: 'এ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'এ... একতারা', content: 'একতারা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'এ', content: 'এ' },
            { id: 'e4', type: 'tap-correct', title: 'এ কোথায়?', voiceText: 'এ বর্ণটি খুঁজে বের করো।', content: 'এ', options: ['ঋ', 'এ', 'ঐ', 'ও'], correctAnswer: 'এ' },
            { id: 'e5', type: 'bubble-pop', title: 'এ ধরো!', voiceText: 'এ লেখা বুদবুদটি ফাটাও।', content: 'এ', options: ['ঋ', 'এ', 'ঐ', 'ও'], correctAnswer: 'এ' },
            { id: 'e6', type: 'letter-puzzle', title: 'একতারা কোন বর্ণ?', voiceText: 'একতারা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'এ', options: ['ঋ', 'এ', 'ঐ', 'ও'], correctAnswer: 'এ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'একতারা শব্দটি সাজাও।', content: 'একতারা', options: ['এ', 'ক', 'ত', 'া', 'র', 'া'], correctAnswer: 'একতারা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'এ', options: ['ঋ-ঋষি', 'এ-একতারা', 'ঐ-ঐরাবত', 'ও-ওল'], correctAnswer: 'এ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে এ লেখো।', content: 'এ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'একতারা কোন বর্ণের সাথে জড়িত?', content: 'এ', options: ['ঋ', 'এ', 'ঐ', 'ও'], correctAnswer: 'এ' },
        ],
    },
    'swarabarna-oi': {
        id: 'swarabarna-oi', letter: 'ঐ', word: 'ঐরাবত', wordEn: 'Airavata', emoji: '🐘',
        color: 'from-sky-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঐ শিখি!', voiceText: 'ঐরাবত ইন্দ্রের সাদা হাতি। ঐরাবত শব্দটি ঐ দিয়ে শুরু হয়। আজ আমরা ঐ শিখব।', content: 'ঐ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঐ... ঐরাবত', content: 'ঐরাবত' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঐ', content: 'ঐ' },
            { id: 'e4', type: 'tap-correct', title: 'ঐ কোথায়?', voiceText: 'ঐ বর্ণটি খুঁজে বের করো।', content: 'ঐ', options: ['এ', 'ঐ', 'ও', 'ঔ'], correctAnswer: 'ঐ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঐ ধরো!', voiceText: 'ঐ লেখা বুদবুদটি ফাটাও।', content: 'ঐ', options: ['এ', 'ঐ', 'ও', 'ঔ'], correctAnswer: 'ঐ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঐরাবত কোন বর্ণ?', voiceText: 'ঐরাবত এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঐ', options: ['এ', 'ঐ', 'ও', 'ঔ'], correctAnswer: 'ঐ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঐরাবত শব্দটি সাজাও।', content: 'ঐরাবত', options: ['ঐ', 'র', 'া', 'ব', 'ত'], correctAnswer: 'ঐরাবত' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঐ', options: ['এ-একতারা', 'ঐ-ঐরাবত', 'ও-ওল', 'ঔ-ঔষধ'], correctAnswer: 'ঐ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঐ লেখো।', content: 'ঐ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঐরাবত কোন বর্ণের সাথে জড়িত?', content: 'ঐ', options: ['এ', 'ঐ', 'ও', 'ঔ'], correctAnswer: 'ঐ' },
        ],
    },
}
