import type { LessonConfig } from '@/components/kids/LessonEngine'

export const banglaLessonsP2a: Record<string, LessonConfig> = {

    'banjonborno-gha': {
        id: 'banjonborno-gha', letter: 'ঘ', word: 'ঘড়ি', wordEn: 'Clock', emoji: '🕐',
        color: 'from-indigo-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঘ শিখি!', voiceText: 'দেয়ালে ঝুলছে সুন্দর একটা ঘড়ি। ঘড়ি শব্দটি ঘ দিয়ে শুরু হয়। আজ আমরা ঘ শিখব।', content: 'ঘ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঘ... ঘড়ি', content: 'ঘড়ি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঘ', content: 'ঘ' },
            { id: 'e4', type: 'tap-correct', title: 'ঘ কোথায়?', voiceText: 'ঘ বর্ণটি খুঁজে বের করো।', content: 'ঘ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ঘ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঘ ধরো!', voiceText: 'ঘ লেখা বুদবুদটি ফাটাও।', content: 'ঘ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ঘ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঘড়ি কোন বর্ণ?', voiceText: 'ঘড়ি এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঘ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ঘ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঘড়ি শব্দটি সাজাও।', content: 'ঘড়ি', options: ['ঘ', 'ড', '়', 'ি'], correctAnswer: 'ঘড়ি' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঘ', options: ['ক-কাক', 'খ-খরগোশ', 'গ-গরু', 'ঘ-ঘড়ি'], correctAnswer: 'ঘ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঘ লেখো।', content: 'ঘ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঘড়ি কোন বর্ণের সাথে জড়িত?', content: 'ঘ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ঘ' },
        ],
    },
    'banjonborno-nga': {
        id: 'banjonborno-nga', letter: 'ঙ', word: 'বাংলা', wordEn: 'Bangla', emoji: '🇧🇩',
        color: 'from-green-400 to-emerald-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঙ শিখি!', voiceText: 'ঙ বর্ণটি একা শব্দের শুরুতে আসে না — বাংলা শব্দে আছে। আজ আমরা ঙ শিখব।', content: 'ঙ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঙ... বাংলা', content: 'বাংলা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঙ', content: 'ঙ' },
            { id: 'e4', type: 'tap-correct', title: 'ঙ কোথায়?', voiceText: 'ঙ বর্ণটি খুঁজে বের করো।', content: 'ঙ', options: ['ঘ', 'ঙ', 'চ', 'ছ'], correctAnswer: 'ঙ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঙ ধরো!', voiceText: 'ঙ লেখা বুদবুদটি ফাটাও।', content: 'ঙ', options: ['ঘ', 'ঙ', 'চ', 'ছ'], correctAnswer: 'ঙ' },
            { id: 'e6', type: 'letter-puzzle', title: 'বাংলা কোন বর্ণ?', voiceText: 'বাংলা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঙ', options: ['ঘ', 'ঙ', 'চ', 'ছ'], correctAnswer: 'ঙ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'বাংলা শব্দটি সাজাও।', content: 'বাংলা', options: ['ব', 'া', 'ং', 'ল'], correctAnswer: 'বাংলা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঙ', options: ['ঘ-ঘড়ি', 'ঙ-বাংলা', 'চ-চাঁদ', 'ছ-ছাগল'], correctAnswer: 'ঙ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঙ লেখো।', content: 'ঙ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'বাংলা কোন বর্ণের সাথে জড়িত?', content: 'ঙ', options: ['ঘ', 'ঙ', 'চ', 'ছ'], correctAnswer: 'ঙ' },
        ],
    },
    'banjanbarna-cha': {
        id: 'banjanbarna-cha', letter: 'চ', word: 'চাঁদ', wordEn: 'Moon', emoji: '🌙',
        color: 'from-indigo-400 to-violet-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ চ শিখি!', voiceText: 'রাতে আকাশে চাঁদ জ্বলে। চাঁদ শব্দটি চ দিয়ে শুরু হয়। আজ আমরা চ শিখব।', content: 'চ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'চ... চাঁদ', content: 'চাঁদ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'চ', content: 'চ' },
            { id: 'e4', type: 'tap-correct', title: 'চ কোথায়?', voiceText: 'চ বর্ণটি খুঁজে বের করো।', content: 'চ', options: ['ঘ', 'চ', 'ছ', 'জ'], correctAnswer: 'চ' },
            { id: 'e5', type: 'bubble-pop', title: 'চ ধরো!', voiceText: 'চ লেখা বুদবুদটি ফাটাও।', content: 'চ', options: ['ঘ', 'চ', 'ছ', 'জ'], correctAnswer: 'চ' },
            { id: 'e6', type: 'letter-puzzle', title: 'চাঁদ কোন বর্ণ?', voiceText: 'চাঁদ এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'চ', options: ['ঘ', 'চ', 'ছ', 'জ'], correctAnswer: 'চ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'চাঁদ শব্দটি সাজাও।', content: 'চাঁদ', options: ['চ', 'া', 'ঁ', 'দ'], correctAnswer: 'চাঁদ' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'চ', options: ['ঘ-ঘড়ি', 'চ-চাঁদ', 'ছ-ছাগল', 'জ-জাম'], correctAnswer: 'চ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে চ লেখো।', content: 'চ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'চাঁদ কোন বর্ণের সাথে জড়িত?', content: 'চ', options: ['ঘ', 'চ', 'ছ', 'জ'], correctAnswer: 'চ' },
        ],
    },
    'banjanbarna-chha': {
        id: 'banjanbarna-chha', letter: 'ছ', word: 'ছাগল', wordEn: 'Goat', emoji: '🐐',
        color: 'from-teal-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ছ শিখি!', voiceText: 'ছাগল ঘাসে চরে বেড়ায়। ছাগল শব্দটি ছ দিয়ে শুরু হয়। আজ আমরা ছ শিখব।', content: 'ছ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ছ... ছাগল', content: 'ছাগল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ছ', content: 'ছ' },
            { id: 'e4', type: 'tap-correct', title: 'ছ কোথায়?', voiceText: 'ছ বর্ণটি খুঁজে বের করো।', content: 'ছ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'ছ' },
            { id: 'e5', type: 'bubble-pop', title: 'ছ ধরো!', voiceText: 'ছ লেখা বুদবুদটি ফাটাও।', content: 'ছ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'ছ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ছাগল কোন বর্ণ?', voiceText: 'ছাগল এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ছ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'ছ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ছাগল শব্দটি সাজাও।', content: 'ছাগল', options: ['ছ', 'া', 'গ', 'ল'], correctAnswer: 'ছাগল' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ছ', options: ['চ-চাঁদ', 'ছ-ছাগল', 'জ-জাম', 'ঝ-ঝড়'], correctAnswer: 'ছ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ছ লেখো।', content: 'ছ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ছাগল কোন বর্ণের সাথে জড়িত?', content: 'ছ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'ছ' },
        ],
    },
    'banjanbarna-ja': {
        id: 'banjanbarna-ja', letter: 'জ', word: 'জাম', wordEn: 'Jamun', emoji: '🍇',
        color: 'from-purple-400 to-violet-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ জ শিখি!', voiceText: 'গাছে পাকা জাম ঝুলে আছে। জাম শব্দটি জ দিয়ে শুরু হয়। আজ আমরা জ শিখব।', content: 'জ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'জ... জাম', content: 'জাম' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'জ', content: 'জ' },
            { id: 'e4', type: 'tap-correct', title: 'জ কোথায়?', voiceText: 'জ বর্ণটি খুঁজে বের করো।', content: 'জ', options: ['ছ', 'জ', 'ঝ', 'ঞ'], correctAnswer: 'জ' },
            { id: 'e5', type: 'bubble-pop', title: 'জ ধরো!', voiceText: 'জ লেখা বুদবুদটি ফাটাও।', content: 'জ', options: ['ছ', 'জ', 'ঝ', 'ঞ'], correctAnswer: 'জ' },
            { id: 'e6', type: 'letter-puzzle', title: 'জাম কোন বর্ণ?', voiceText: 'জাম এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'জ', options: ['ছ', 'জ', 'ঝ', 'ঞ'], correctAnswer: 'জ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'জাম শব্দটি সাজাও।', content: 'জাম', options: ['জ', 'া', 'ম'], correctAnswer: 'জাম' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'জ', options: ['ছ-ছাগল', 'জ-জাম', 'ঝ-ঝড়', 'ঞ-মিঞা'], correctAnswer: 'জ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে জ লেখো।', content: 'জ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'জাম কোন বর্ণের সাথে জড়িত?', content: 'জ', options: ['ছ', 'জ', 'ঝ', 'ঞ'], correctAnswer: 'জ' },
        ],
    },
    'banjanbarna-jha': {
        id: 'banjanbarna-jha', letter: 'ঝ', word: 'ঝড়', wordEn: 'Storm', emoji: '🌪️',
        color: 'from-slate-400 to-gray-600', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঝ শিখি!', voiceText: 'আকাশে কালো মেঘ — ঝড় আসছে। ঝড় শব্দটি ঝ দিয়ে শুরু হয়। আজ আমরা ঝ শিখব।', content: 'ঝ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঝ... ঝড়', content: 'ঝড়' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঝ', content: 'ঝ' },
            { id: 'e4', type: 'tap-correct', title: 'ঝ কোথায়?', voiceText: 'ঝ বর্ণটি খুঁজে বের করো।', content: 'ঝ', options: ['জ', 'ঝ', 'ঞ', 'ট'], correctAnswer: 'ঝ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঝ ধরো!', voiceText: 'ঝ লেখা বুদবুদটি ফাটাও।', content: 'ঝ', options: ['জ', 'ঝ', 'ঞ', 'ট'], correctAnswer: 'ঝ' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঝড় কোন বর্ণ?', voiceText: 'ঝড় এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঝ', options: ['জ', 'ঝ', 'ঞ', 'ট'], correctAnswer: 'ঝ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঝড় শব্দটি সাজাও।', content: 'ঝড়', options: ['ঝ', 'ড', '়'], correctAnswer: 'ঝড়' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঝ', options: ['জ-জাম', 'ঝ-ঝড়', 'ঞ-মিঞা', 'ট-টমেটো'], correctAnswer: 'ঝ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঝ লেখো।', content: 'ঝ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঝড় কোন বর্ণের সাথে জড়িত?', content: 'ঝ', options: ['জ', 'ঝ', 'ঞ', 'ট'], correctAnswer: 'ঝ' },
        ],
    },
    'banjanbarna-nya': {
        id: 'banjanbarna-nya', letter: 'ঞ', word: 'মিঞা', wordEn: 'Mia', emoji: '👦',
        color: 'from-rose-300 to-pink-400', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঞ শিখি!', voiceText: 'ঞ বর্ণটি বিশেষ — মিঞা শব্দে পাওয়া যায়। আজ আমরা ঞ শিখব।', content: 'ঞ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঞ... মিঞা', content: 'মিঞা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঞ', content: 'ঞ' },
            { id: 'e4', type: 'tap-correct', title: 'ঞ কোথায়?', voiceText: 'ঞ বর্ণটি খুঁজে বের করো।', content: 'ঞ', options: ['ঝ', 'ঞ', 'ট', 'ঠ'], correctAnswer: 'ঞ' },
            { id: 'e5', type: 'bubble-pop', title: 'ঞ ধরো!', voiceText: 'ঞ লেখা বুদবুদটি ফাটাও।', content: 'ঞ', options: ['ঝ', 'ঞ', 'ট', 'ঠ'], correctAnswer: 'ঞ' },
            { id: 'e6', type: 'letter-puzzle', title: 'মিঞা কোন বর্ণ?', voiceText: 'মিঞা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঞ', options: ['ঝ', 'ঞ', 'ট', 'ঠ'], correctAnswer: 'ঞ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'মিঞা শব্দটি সাজাও।', content: 'মিঞা', options: ['ম', 'ি', 'ঞ', 'া'], correctAnswer: 'মিঞা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঞ', options: ['ঝ-ঝড়', 'ঞ-মিঞা', 'ট-টমেটো', 'ঠ-ঠোঁট'], correctAnswer: 'ঞ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঞ লেখো।', content: 'ঞ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'মিঞা কোন বর্ণের সাথে জড়িত?', content: 'ঞ', options: ['ঝ', 'ঞ', 'ট', 'ঠ'], correctAnswer: 'ঞ' },
        ],
    },
}
