import type { LessonConfig } from '@/components/kids/LessonEngine'

export const banglaLessonsP4a: Record<string, LessonConfig> = {

    'banjanbarna3-ha': {
        id: 'banjanbarna3-ha', letter: 'হ', word: 'হাতি', wordEn: 'Elephant', emoji: '🐘',
        color: 'from-gray-400 to-slate-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ হ শিখি!', voiceText: 'হাতি বড় ও শক্তিশালী। হাতি শব্দটি হ দিয়ে শুরু হয়। আজ আমরা হ শিখব।', content: 'হ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'হ... হাতি', content: 'হাতি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'হ', content: 'হ' },
            { id: 'e4', type: 'tap-correct', title: 'হ কোথায়?', voiceText: 'হ বর্ণটি খুঁজে বের করো।', content: 'হ', options: ['স', 'হ', 'ড়', 'ঢ়'], correctAnswer: 'হ' },
            { id: 'e5', type: 'bubble-pop', title: 'হ ধরো!', voiceText: 'হ লেখা বুদবুদটি ফাটাও।', content: 'হ', options: ['স', 'হ', 'ড়', 'ঢ়'], correctAnswer: 'হ' },
            { id: 'e6', type: 'letter-puzzle', title: 'হাতি কোন বর্ণ?', voiceText: 'হাতি এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'হ', options: ['স', 'হ', 'ড়', 'ঢ়'], correctAnswer: 'হ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'হাতি শব্দটি সাজাও।', content: 'হাতি', options: ['হ', 'া', 'ত', 'ি'], correctAnswer: 'হাতি' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'হ', options: ['স-সাপ', 'হ-হাতি', 'ড়-গাড়ি', 'ঢ়-ঢেঁড়স'], correctAnswer: 'হ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে হ লেখো।', content: 'হ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'হাতি কোন বর্ণের সাথে জড়িত?', content: 'হ', options: ['স', 'হ', 'ড়', 'ঢ়'], correctAnswer: 'হ' },
        ],
    },
    'banjanbarna3-rra': {
        id: 'banjanbarna3-rra', letter: 'ড়', word: 'গাড়ি', wordEn: 'Car', emoji: '🚗',
        color: 'from-blue-400 to-indigo-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ড় শিখি!', voiceText: 'রাস্তায় গাড়ি চলে। গাড়ি শব্দে ড় আছে। আজ আমরা ড় শিখব।', content: 'ড়' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ড়... গাড়ি', content: 'গাড়ি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ড়', content: 'ড়' },
            { id: 'e4', type: 'tap-correct', title: 'ড় কোথায়?', voiceText: 'ড় বর্ণটি খুঁজে বের করো।', content: 'ড়', options: ['হ', 'ড়', 'ঢ়', 'য়'], correctAnswer: 'ড়' },
            { id: 'e5', type: 'bubble-pop', title: 'ড় ধরো!', voiceText: 'ড় লেখা বুদবুদটি ফাটাও।', content: 'ড়', options: ['হ', 'ড়', 'ঢ়', 'য়'], correctAnswer: 'ড়' },
            { id: 'e6', type: 'letter-puzzle', title: 'গাড়ি কোন বর্ণ?', voiceText: 'গাড়ি এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ড়', options: ['হ', 'ড়', 'ঢ়', 'য়'], correctAnswer: 'ড়' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'গাড়ি শব্দটি সাজাও।', content: 'গাড়ি', options: ['গ', 'া', 'ড', '়', 'ি'], correctAnswer: 'গাড়ি' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ড়', options: ['হ-হাতি', 'ড়-গাড়ি', 'ঢ়-ঢেঁড়স', 'য়-যায়'], correctAnswer: 'ড়' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ড় লেখো।', content: 'ড়' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'গাড়ি কোন বর্ণের সাথে জড়িত?', content: 'ড়', options: ['হ', 'ড়', 'ঢ়', 'য়'], correctAnswer: 'ড়' },
        ],
    },
    'banjanbarna3-rha': {
        id: 'banjanbarna3-rha', letter: 'ঢ়', word: 'ঢেঁড়স', wordEn: 'Okra', emoji: '🥬',
        color: 'from-green-400 to-lime-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ঢ় শিখি!', voiceText: 'ঢেঁড়স সবুজ সবজি। ঢেঁড়স শব্দে ঢ় আছে। আজ আমরা ঢ় শিখব।', content: 'ঢ়' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ঢ়... ঢেঁড়স', content: 'ঢেঁড়স' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ঢ়', content: 'ঢ়' },
            { id: 'e4', type: 'tap-correct', title: 'ঢ় কোথায়?', voiceText: 'ঢ় বর্ণটি খুঁজে বের করো।', content: 'ঢ়', options: ['ড়', 'ঢ়', 'য়', 'ৎ'], correctAnswer: 'ঢ়' },
            { id: 'e5', type: 'bubble-pop', title: 'ঢ় ধরো!', voiceText: 'ঢ় লেখা বুদবুদটি ফাটাও।', content: 'ঢ়', options: ['ড়', 'ঢ়', 'য়', 'ৎ'], correctAnswer: 'ঢ়' },
            { id: 'e6', type: 'letter-puzzle', title: 'ঢেঁড়স কোন বর্ণ?', voiceText: 'ঢেঁড়স এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ঢ়', options: ['ড়', 'ঢ়', 'য়', 'ৎ'], correctAnswer: 'ঢ়' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'ঢেঁড়স শব্দটি সাজাও।', content: 'ঢেঁড়স', options: ['ঢ', 'ে', 'ঁ', 'ড', '়', 'স'], correctAnswer: 'ঢেঁড়স' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ঢ়', options: ['ড়-গাড়ি', 'ঢ়-ঢেঁড়স', 'য়-যায়', 'ৎ-উৎস'], correctAnswer: 'ঢ়' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ঢ় লেখো।', content: 'ঢ়' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'ঢেঁড়স কোন বর্ণের সাথে জড়িত?', content: 'ঢ়', options: ['ড়', 'ঢ়', 'য়', 'ৎ'], correctAnswer: 'ঢ়' },
        ],
    },
    'banjanbarna3-yya': {
        id: 'banjanbarna3-yya', letter: 'য়', word: 'যায়', wordEn: 'Goes', emoji: '🚶',
        color: 'from-sky-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ য় শিখি!', voiceText: 'সে স্কুলে যায়। যায় শব্দে য় আছে। আজ আমরা য় শিখব।', content: 'য়' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'য়... যায়', content: 'যায়' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'য়', content: 'য়' },
            { id: 'e4', type: 'tap-correct', title: 'য় কোথায়?', voiceText: 'য় বর্ণটি খুঁজে বের করো।', content: 'য়', options: ['ঢ়', 'য়', 'ৎ', 'ং'], correctAnswer: 'য়' },
            { id: 'e5', type: 'bubble-pop', title: 'য় ধরো!', voiceText: 'য় লেখা বুদবুদটি ফাটাও।', content: 'য়', options: ['ঢ়', 'য়', 'ৎ', 'ং'], correctAnswer: 'য়' },
            { id: 'e6', type: 'letter-puzzle', title: 'যায় কোন বর্ণ?', voiceText: 'যায় এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'য়', options: ['ঢ়', 'য়', 'ৎ', 'ং'], correctAnswer: 'য়' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'যায় শব্দটি সাজাও।', content: 'যায়', options: ['য', 'া', 'য়'], correctAnswer: 'যায়' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'য়', options: ['ঢ়-ঢেঁড়স', 'য়-যায়', 'ৎ-উৎস', 'ং-বাংলা'], correctAnswer: 'য়' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে য় লেখো।', content: 'য়' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'যায় কোন বর্ণের সাথে জড়িত?', content: 'য়', options: ['ঢ়', 'য়', 'ৎ', 'ং'], correctAnswer: 'য়' },
        ],
    },
    'banjanbarna3-kha': {
        id: 'banjanbarna3-kha', letter: 'ৎ', word: 'উৎস', wordEn: 'Source', emoji: '💧',
        color: 'from-cyan-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ৎ শিখি!', voiceText: 'উৎস মানে উৎপত্তি। উৎস শব্দে ৎ আছে। আজ আমরা ৎ শিখব।', content: 'ৎ' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ৎ... উৎস', content: 'উৎস' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ৎ', content: 'ৎ' },
            { id: 'e4', type: 'tap-correct', title: 'ৎ কোথায়?', voiceText: 'ৎ বর্ণটি খুঁজে বের করো।', content: 'ৎ', options: ['য়', 'ৎ', 'ং', 'ঃ'], correctAnswer: 'ৎ' },
            { id: 'e5', type: 'bubble-pop', title: 'ৎ ধরো!', voiceText: 'ৎ লেখা বুদবুদটি ফাটাও।', content: 'ৎ', options: ['য়', 'ৎ', 'ং', 'ঃ'], correctAnswer: 'ৎ' },
            { id: 'e6', type: 'letter-puzzle', title: 'উৎস কোন বর্ণ?', voiceText: 'উৎস এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ৎ', options: ['য়', 'ৎ', 'ং', 'ঃ'], correctAnswer: 'ৎ' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'উৎস শব্দটি সাজাও।', content: 'উৎস', options: ['উ', 'ৎ', 'স'], correctAnswer: 'উৎস' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ৎ', options: ['য়-যায়', 'ৎ-উৎস', 'ং-বাংলা', 'ঃ-দুঃখ'], correctAnswer: 'ৎ' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ৎ লেখো।', content: 'ৎ' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'উৎস কোন বর্ণের সাথে জড়িত?', content: 'ৎ', options: ['য়', 'ৎ', 'ং', 'ঃ'], correctAnswer: 'ৎ' },
        ],
    },
    'boss-banjanbarna-3': {
        id: 'boss-banjanbarna-3', letter: '★', word: 'ব্যঞ্জন Part 3 Boss', wordEn: 'Boss Quiz', emoji: '🏆',
        color: 'from-rose-400 to-pink-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'ব্যঞ্জন Part 3 Boss!', voiceText: 'প্রস্তুত? য থেকে ৎ সব মনে করে খেলি!', content: '★' },
            { id: 'e2', type: 'tap-correct', title: 'রকেট কোন বর্ণ?', voiceText: 'রকেট কোন বর্ণ?', content: 'র', options: ['র', 'ল', 'ষ', 'শ'], correctAnswer: 'র' },
            { id: 'e3', type: 'tap-correct', title: 'হাতি কোন বর্ণ?', voiceText: 'হাতি কোন বর্ণ?', content: 'হ', options: ['হ', 'স', 'শ', 'ষ'], correctAnswer: 'হ' },
            { id: 'e4', type: 'matching', title: 'সব মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও।', content: '★', options: ['য-যাত্রী', 'র-রকেট', 'ল-লাল', 'হ-হাতি'], correctAnswer: 'য' },
            { id: 'e5', type: 'quiz', title: 'চূড়ান্ত!', voiceText: 'সাপ কোন বর্ণ?', content: 'স', options: ['স', 'শ', 'ষ', 'হ'], correctAnswer: 'স' },
        ],
    },
    'bishesh-anuswara': {
        id: 'bishesh-anuswara', letter: 'ং', word: 'বাংলা', wordEn: 'Bangla', emoji: '🇧🇩',
        color: 'from-green-400 to-emerald-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'চলো আজ ং শিখি!', voiceText: 'ং কে বলে অনুস্বার। বাংলা শব্দে ং আছে। আজ আমরা ং শিখব।', content: 'ং' },
            { id: 'e2', type: 'listen-repeat', title: 'আমার সাথে বলো', voiceText: 'ং... বাংলা', content: 'বাংলা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো বন্ধু!', voiceText: 'ং', content: 'ং' },
            { id: 'e4', type: 'tap-correct', title: 'ং কোথায়?', voiceText: 'ং বর্ণটি খুঁজে বের করো।', content: 'ং', options: ['ৎ', 'ং', 'ঃ', 'ঁ'], correctAnswer: 'ং' },
            { id: 'e5', type: 'bubble-pop', title: 'ং ধরো!', voiceText: 'ং লেখা বুদবুদটি ফাটাও।', content: 'ং', options: ['ৎ', 'ং', 'ঃ', 'ঁ'], correctAnswer: 'ং' },
            { id: 'e6', type: 'letter-puzzle', title: 'বাংলা কোন বর্ণ?', voiceText: 'বাংলা এর সাথে সম্পর্কিত বর্ণটি বেছে নাও।', content: 'ং', options: ['ৎ', 'ং', 'ঃ', 'ঁ'], correctAnswer: 'ং' },
            { id: 'e7', type: 'word-builder', title: 'শব্দ সাজাও', voiceText: 'বাংলা শব্দটি সাজাও।', content: 'বাংলা', options: ['ব', 'া', 'ং', 'ল', 'া'], correctAnswer: 'বাংলা' },
            { id: 'e8', type: 'matching', title: 'জোড়া মেলাও', voiceText: 'বর্ণের সাথে শব্দ মিলিয়ে দাও।', content: 'ং', options: ['ৎ-উৎস', 'ং-বাংলা', 'ঃ-দুঃখ', 'ঁ-চাঁদ'], correctAnswer: 'ং' },
            { id: 'e9', type: 'trace', title: 'চলো লিখি', voiceText: 'এবার সুন্দর করে ং লেখো।', content: 'ং' },
            { id: 'e10', type: 'quiz', title: 'শেষ প্রশ্ন', voiceText: 'বাংলা কোন বর্ণের সাথে জড়িত?', content: 'ং', options: ['ৎ', 'ং', 'ঃ', 'ঁ'], correctAnswer: 'ং' },
        ],
    },
}
