'use client'

import { useParams } from 'next/navigation'
import LessonEngine, { LessonConfig } from '@/components/kids/LessonEngine'

const lessons: Record<string, LessonConfig> = {

    // ─── স্বরবর্ণ ───────────────────────────────────────────────
    'swarabarna-a': {
        id: 'swarabarna-a', letter: 'অ', word: 'অজগর', wordEn: 'Python', emoji: '🐍',
        color: 'from-red-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'অ দিয়ে অজগর', content: 'অ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — অজগর', voiceText: 'অজগর', content: 'অজগর' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'অ', content: 'অ' },
            { id: 'e4', type: 'tap-correct', title: 'অ কোথায়?', voiceText: 'অ খুঁজে বের করো', content: 'অ', options: ['অ', 'আ', 'ই', 'ক'], correctAnswer: 'অ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'অ বুদবুদ ফাটাও', content: 'অ', options: ['অ', 'আ', 'ই', 'ক'], correctAnswer: 'অ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'অ', options: ['অ', 'আ', 'ই', 'ক'], correctAnswer: 'অ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'অজগর বানাও', content: 'অজগর', options: ['অ', 'জ', 'গ', 'র'], correctAnswer: 'অজগর' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'অ', options: ['অ-অজগর', 'আ-আম', 'ই-ইলিশ', 'ঈ-ঈগল'], correctAnswer: 'অ' },
            { id: 'e10', type: 'trace', title: 'লিখি — অ', voiceText: 'অ লেখো', content: 'অ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'অজগর কোন বর্ণ দিয়ে শুরু?', content: 'অ', options: ['আ', 'অ', 'ই', 'উ'], correctAnswer: 'অ' },
        ],
    },
    'swarabarna-aa': {
        id: 'swarabarna-aa', letter: 'আ', word: 'আম', wordEn: 'Mango', emoji: '🥭',
        color: 'from-orange-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'আ দিয়ে আম', content: 'আ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — আম', voiceText: 'আম', content: 'আম' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'আ', content: 'আ' },
            { id: 'e4', type: 'tap-correct', title: 'আ কোথায়?', voiceText: 'আ খুঁজে বের করো', content: 'আ', options: ['অ', 'আ', 'ই', 'খ'], correctAnswer: 'আ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'আ বুদবুদ ফাটাও', content: 'আ', options: ['অ', 'আ', 'ই', 'খ'], correctAnswer: 'আ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'আ', options: ['অ', 'আ', 'ই', 'খ'], correctAnswer: 'আ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'আম বানাও', content: 'আম', options: ['আ', 'ম', 'অ', 'ন'], correctAnswer: 'আম' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'আ', options: ['অ-অজগর', 'আ-আম', 'ই-ইলিশ', 'ঈ-ঈগল'], correctAnswer: 'আ' },
            { id: 'e10', type: 'trace', title: 'লিখি — আ', voiceText: 'আ লেখো', content: 'আ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'আম কোন বর্ণ দিয়ে শুরু?', content: 'আ', options: ['অ', 'আ', 'ক', 'ঘ'], correctAnswer: 'আ' },
        ],
    },
    'swarabarna-i': {
        id: 'swarabarna-i', letter: 'ই', word: 'ইলিশ', wordEn: 'Hilsa Fish', emoji: '🐟',
        color: 'from-yellow-400 to-lime-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ই দিয়ে ইলিশ', content: 'ই' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ইলিশ', voiceText: 'ইলিশ', content: 'ইলিশ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ই', content: 'ই' },
            { id: 'e4', type: 'tap-correct', title: 'ই কোথায়?', voiceText: 'ই খুঁজে বের করো', content: 'ই', options: ['ঈ', 'উ', 'ই', 'চ'], correctAnswer: 'ই' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ই বুদবুদ ফাটাও', content: 'ই', options: ['ঈ', 'উ', 'ই', 'চ'], correctAnswer: 'ই' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ই', options: ['ঈ', 'উ', 'ই', 'চ'], correctAnswer: 'ই' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ইলিশ বানাও', content: 'ইলিশ', options: ['ই', 'ল', 'ি', 'শ'], correctAnswer: 'ইলিশ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ই', options: ['অ-অজগর', 'আ-আম', 'ই-ইলিশ', 'ঈ-ঈগল'], correctAnswer: 'ই' },
            { id: 'e10', type: 'trace', title: 'লিখি — ই', voiceText: 'ই লেখো', content: 'ই' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ইলিশ কোন বর্ণ দিয়ে শুরু?', content: 'ই', options: ['ঈ', 'উ', 'ই', 'অ'], correctAnswer: 'ই' },
        ],
    },
    'swarabarna-ii': {
        id: 'swarabarna-ii', letter: 'ঈ', word: 'ঈগল', wordEn: 'Eagle', emoji: '🦅',
        color: 'from-sky-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ঈ দিয়ে ঈগল', content: 'ঈ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ঈগল', voiceText: 'ঈগল', content: 'ঈগল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ঈ', content: 'ঈ' },
            { id: 'e4', type: 'tap-correct', title: 'ঈ কোথায়?', voiceText: 'ঈ খুঁজে বের করো', content: 'ঈ', options: ['ই', 'ঈ', 'উ', 'ঊ'], correctAnswer: 'ঈ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ঈ বুদবুদ ফাটাও', content: 'ঈ', options: ['ই', 'ঈ', 'উ', 'ঊ'], correctAnswer: 'ঈ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ঈ', options: ['ই', 'ঈ', 'উ', 'ঊ'], correctAnswer: 'ঈ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ঈগল বানাও', content: 'ঈগল', options: ['ঈ', 'গ', 'ল'], correctAnswer: 'ঈগল' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ঈ', options: ['ই-ইলিশ', 'ঈ-ঈগল', 'উ-উট', 'ঊ-ঊষা'], correctAnswer: 'ঈ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ঈ', voiceText: 'ঈ লেখো', content: 'ঈ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ঈগল কোন বর্ণ দিয়ে শুরু?', content: 'ঈ', options: ['ই', 'ঈ', 'উ', 'ঊ'], correctAnswer: 'ঈ' },
        ],
    },
    'swarabarna-u': {
        id: 'swarabarna-u', letter: 'উ', word: 'উট', wordEn: 'Camel', emoji: '🐪',
        color: 'from-amber-400 to-orange-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'উ দিয়ে উট', content: 'উ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — উট', voiceText: 'উট', content: 'উট' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'উ', content: 'উ' },
            { id: 'e4', type: 'tap-correct', title: 'উ কোথায়?', voiceText: 'উ খুঁজে বের করো', content: 'উ', options: ['ঈ', 'উ', 'ঊ', 'ঋ'], correctAnswer: 'উ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'উ বুদবুদ ফাটাও', content: 'উ', options: ['ঈ', 'উ', 'ঊ', 'ঋ'], correctAnswer: 'উ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'উ', options: ['ঈ', 'উ', 'ঊ', 'ঋ'], correctAnswer: 'উ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'উট বানাও', content: 'উট', options: ['উ', 'ট', 'আ', 'ম'], correctAnswer: 'উট' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'উ', options: ['ই-ইলিশ', 'ঈ-ঈগল', 'উ-উট', 'ঊ-ঊষা'], correctAnswer: 'উ' },
            { id: 'e10', type: 'trace', title: 'লিখি — উ', voiceText: 'উ লেখো', content: 'উ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'উট কোন বর্ণ দিয়ে শুরু?', content: 'উ', options: ['ই', 'উ', 'ঊ', 'ঋ'], correctAnswer: 'উ' },
        ],
    },
    'swarabarna-uu': {
        id: 'swarabarna-uu', letter: 'ঊ', word: 'ঊষা', wordEn: 'Dawn', emoji: '🌅',
        color: 'from-red-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ঊ দিয়ে ঊষা', content: 'ঊ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ঊষা', voiceText: 'ঊষা', content: 'ঊষা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ঊ', content: 'ঊ' },
            { id: 'e4', type: 'tap-correct', title: 'ঊ কোথায়?', voiceText: 'ঊ খুঁজে বের করো', content: 'ঊ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঊ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ঊ বুদবুদ ফাটাও', content: 'ঊ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঊ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ঊ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঊ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ঊষা বানাও', content: 'ঊষা', options: ['ঊ', 'ষ', 'া', 'ম'], correctAnswer: 'ঊষা' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ঊ', options: ['ঈ-ঈগল', 'উ-উট', 'ঊ-ঊষা', 'ঋ-ঋষি'], correctAnswer: 'ঊ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ঊ', voiceText: 'ঊ লেখো', content: 'ঊ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ঊষা কোন বর্ণ দিয়ে শুরু?', content: 'ঊ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঊ' },
        ],
    },
    'swarabarna-ri': {
        id: 'swarabarna-ri', letter: 'ঋ', word: 'ঋষি', wordEn: 'Sage', emoji: '📿',
        color: 'from-violet-400 to-purple-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ঋ দিয়ে ঋষি', content: 'ঋ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ঋষি', voiceText: 'ঋষি', content: 'ঋষি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ঋ', content: 'ঋ' },
            { id: 'e4', type: 'tap-correct', title: 'ঋ কোথায়?', voiceText: 'ঋ খুঁজে বের করো', content: 'ঋ', options: ['ঊ', 'ঋ', 'এ', 'ঐ'], correctAnswer: 'ঋ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ঋ বুদবুদ ফাটাও', content: 'ঋ', options: ['ঊ', 'ঋ', 'এ', 'ঐ'], correctAnswer: 'ঋ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ঋ', options: ['ঊ', 'ঋ', 'এ', 'ঐ'], correctAnswer: 'ঋ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ঋষি বানাও', content: 'ঋষি', options: ['ঋ', 'ষ', 'ি', 'ম'], correctAnswer: 'ঋষি' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ঋ', options: ['উ-উট', 'ঊ-ঊষা', 'ঋ-ঋষি', 'এ-একতারা'], correctAnswer: 'ঋ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ঋ', voiceText: 'ঋ লেখো', content: 'ঋ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ঋষি কোন বর্ণ দিয়ে শুরু?', content: 'ঋ', options: ['উ', 'ঊ', 'ঋ', 'এ'], correctAnswer: 'ঋ' },
        ],
    },
    'swarabarna-e': {
        id: 'swarabarna-e', letter: 'এ', word: 'একতারা', wordEn: 'Ektara', emoji: '🪕',
        color: 'from-lime-400 to-green-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'এ দিয়ে একতারা', content: 'এ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — একতারা', voiceText: 'একতারা', content: 'একতারা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'এ', content: 'এ' },
            { id: 'e4', type: 'tap-correct', title: 'এ কোথায়?', voiceText: 'এ খুঁজে বের করো', content: 'এ', options: ['ঋ', 'এ', 'ঐ', 'ও'], correctAnswer: 'এ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'এ বুদবুদ ফাটাও', content: 'এ', options: ['ঋ', 'এ', 'ঐ', 'ও'], correctAnswer: 'এ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'এ', options: ['ঋ', 'এ', 'ঐ', 'ও'], correctAnswer: 'এ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'একতারা বানাও', content: 'একতারা', options: ['এ', 'ক', 'তা', 'রা'], correctAnswer: 'একতারা' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'এ', options: ['ঊ-ঊষা', 'ঋ-ঋষি', 'এ-একতারা', 'ঐ-ঐরাবত'], correctAnswer: 'এ' },
            { id: 'e10', type: 'trace', title: 'লিখি — এ', voiceText: 'এ লেখো', content: 'এ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'একতারা কোন বর্ণ দিয়ে শুরু?', content: 'এ', options: ['ঋ', 'এ', 'ঐ', 'ও'], correctAnswer: 'এ' },
        ],
    },
    'swarabarna-oi': {
        id: 'swarabarna-oi', letter: 'ঐ', word: 'ঐরাবত', wordEn: 'Elephant', emoji: '🐘',
        color: 'from-cyan-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ঐ দিয়ে ঐরাবত', content: 'ঐ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ঐরাবত', voiceText: 'ঐরাবত', content: 'ঐরাবত' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ঐ', content: 'ঐ' },
            { id: 'e4', type: 'tap-correct', title: 'ঐ কোথায়?', voiceText: 'ঐ খুঁজে বের করো', content: 'ঐ', options: ['এ', 'ঐ', 'ও', 'ঔ'], correctAnswer: 'ঐ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ঐ বুদবুদ ফাটাও', content: 'ঐ', options: ['এ', 'ঐ', 'ও', 'ঔ'], correctAnswer: 'ঐ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ঐ', options: ['এ', 'ঐ', 'ও', 'ঔ'], correctAnswer: 'ঐ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ঐরাবত বানাও', content: 'ঐরাবত', options: ['ঐ', 'রা', 'ব', 'ত'], correctAnswer: 'ঐরাবত' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ঐ', options: ['ঋ-ঋষি', 'এ-একতারা', 'ঐ-ঐরাবত', 'ও-ওজন'], correctAnswer: 'ঐ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ঐ', voiceText: 'ঐ লেখো', content: 'ঐ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ঐরাবত কোন বর্ণ দিয়ে শুরু?', content: 'ঐ', options: ['এ', 'ঐ', 'ও', 'উ'], correctAnswer: 'ঐ' },
        ],
    },
    'swarabarna-o': {
        id: 'swarabarna-o', letter: 'ও', word: 'ওল', wordEn: 'Yam', emoji: '🌿',
        color: 'from-orange-400 to-red-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ও দিয়ে ওল', content: 'ও' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ওল', voiceText: 'ওল', content: 'ওল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ও', content: 'ও' },
            { id: 'e4', type: 'tap-correct', title: 'ও কোথায়?', voiceText: 'ও খুঁজে বের করো', content: 'ও', options: ['ঐ', 'ও', 'ঔ', 'ই'], correctAnswer: 'ও' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ও বুদবুদ ফাটাও', content: 'ও', options: ['ঐ', 'ও', 'ঔ', 'ই'], correctAnswer: 'ও' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ও', options: ['ঐ', 'ও', 'ঔ', 'ই'], correctAnswer: 'ও' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ওল বানাও', content: 'ওল', options: ['ও', 'ল', 'ম', 'ন'], correctAnswer: 'ওল' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ও', options: ['এ-একতারা', 'ঐ-ঐরাবত', 'ও-ওল', 'ঔ-ঔষধ'], correctAnswer: 'ও' },
            { id: 'e10', type: 'trace', title: 'লিখি — ও', voiceText: 'ও লেখো', content: 'ও' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ওল কোন বর্ণ দিয়ে শুরু?', content: 'ও', options: ['ঐ', 'ও', 'ঔ', 'আ'], correctAnswer: 'ও' },
        ],
    },
    'swarabarna-ou': {
        id: 'swarabarna-ou', letter: 'ঔ', word: 'ঔষধ', wordEn: 'Medicine', emoji: '💊',
        color: 'from-pink-400 to-rose-600', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ঔ দিয়ে ঔষধ', content: 'ঔ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ঔষধ', voiceText: 'ঔষধ', content: 'ঔষধ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ঔ', content: 'ঔ' },
            { id: 'e4', type: 'tap-correct', title: 'ঔ কোথায়?', voiceText: 'ঔ খুঁজে বের করো', content: 'ঔ', options: ['ঐ', 'ও', 'ঔ', 'উ'], correctAnswer: 'ঔ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ঔ বুদবুদ ফাটাও', content: 'ঔ', options: ['ঐ', 'ও', 'ঔ', 'উ'], correctAnswer: 'ঔ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ঔ', options: ['ঐ', 'ও', 'ঔ', 'উ'], correctAnswer: 'ঔ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ঔষধ বানাও', content: 'ঔষধ', options: ['ঔ', 'ষ', 'ধ', 'ম'], correctAnswer: 'ঔষধ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ঔ', options: ['ঐ-ঐরাবত', 'ও-ওল', 'ঔ-ঔষধ', 'ই-ইলিশ'], correctAnswer: 'ঔ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ঔ', voiceText: 'ঔ লেখো', content: 'ঔ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ঔষধ কোন বর্ণ দিয়ে শুরু?', content: 'ঔ', options: ['ঐ', 'ও', 'ঔ', 'এ'], correctAnswer: 'ঔ' },
        ],
    },

    // ─── ব্যঞ্জনবর্ণ ─────────────────────────────────────────────
    'banjanbarna-ka': {
        id: 'banjanbarna-ka', letter: 'ক', word: 'কলা', wordEn: 'Banana', emoji: '🍌',
        color: 'from-yellow-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ক দিয়ে কলা', content: 'ক' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — কলা', voiceText: 'কলা', content: 'কলা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ক', content: 'ক' },
            { id: 'e4', type: 'tap-correct', title: 'ক কোথায়?', voiceText: 'ক খুঁজে বের করো', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ক বুদবুদ ফাটাও', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ক', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'ক' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'কলা বানাও', content: 'কলা', options: ['ক', 'ল', 'া', 'ম'], correctAnswer: 'কলা' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ক', options: ['ক-কলা', 'খ-খরগোশ', 'গ-গরু', 'ঘ-ঘড়ি'], correctAnswer: 'ক' },
            { id: 'e10', type: 'trace', title: 'লিখি — ক', voiceText: 'ক লেখো', content: 'ক' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'কলা কোন বর্ণ দিয়ে শুরু?', content: 'ক', options: ['খ', 'ক', 'গ', 'চ'], correctAnswer: 'ক' },
        ],
    },
    'banjanbarna-kha': {
        id: 'banjanbarna-kha', letter: 'খ', word: 'খরগোশ', wordEn: 'Rabbit', emoji: '🐰',
        color: 'from-orange-400 to-red-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'খ দিয়ে খরগোশ', content: 'খ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — খরগোশ', voiceText: 'খরগোশ', content: 'খরগোশ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'খ', content: 'খ' },
            { id: 'e4', type: 'tap-correct', title: 'খ কোথায়?', voiceText: 'খ খুঁজে বের করো', content: 'খ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'খ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'খ বুদবুদ ফাটাও', content: 'খ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'খ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'খ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'খ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'খরগোশ বানাও', content: 'খরগোশ', options: ['খ', 'র', 'গো', 'শ'], correctAnswer: 'খরগোশ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'খ', options: ['ক-কলা', 'খ-খরগোশ', 'গ-গরু', 'ঘ-ঘড়ি'], correctAnswer: 'খ' },
            { id: 'e10', type: 'trace', title: 'লিখি — খ', voiceText: 'খ লেখো', content: 'খ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'খরগোশ কোন বর্ণ দিয়ে শুরু?', content: 'খ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'খ' },
        ],
    },
    'banjanbarna-ga': {
        id: 'banjanbarna-ga', letter: 'গ', word: 'গরু', wordEn: 'Cow', emoji: '🐄',
        color: 'from-green-400 to-emerald-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'গ দিয়ে গরু', content: 'গ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — গরু', voiceText: 'গরু', content: 'গরু' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'গ', content: 'গ' },
            { id: 'e4', type: 'tap-correct', title: 'গ কোথায়?', voiceText: 'গ খুঁজে বের করো', content: 'গ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'গ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'গ বুদবুদ ফাটাও', content: 'গ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'গ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'গ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'গ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'গরু বানাও', content: 'গরু', options: ['গ', 'র', 'ু', 'ম'], correctAnswer: 'গরু' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'গ', options: ['ক-কলা', 'খ-খরগোশ', 'গ-গরু', 'ঘ-ঘড়ি'], correctAnswer: 'গ' },
            { id: 'e10', type: 'trace', title: 'লিখি — গ', voiceText: 'গ লেখো', content: 'গ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'গরু কোন বর্ণ দিয়ে শুরু?', content: 'গ', options: ['ক', 'খ', 'গ', 'ঘ'], correctAnswer: 'গ' },
        ],
    },
    'banjanbarna-gha': {
        id: 'banjanbarna-gha', letter: 'ঘ', word: 'ঘড়ি', wordEn: 'Clock', emoji: '⏰',
        color: 'from-blue-400 to-indigo-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ঘ দিয়ে ঘড়ি', content: 'ঘ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ঘড়ি', voiceText: 'ঘড়ি', content: 'ঘড়ি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ঘ', content: 'ঘ' },
            { id: 'e4', type: 'tap-correct', title: 'ঘ কোথায়?', voiceText: 'ঘ খুঁজে বের করো', content: 'ঘ', options: ['গ', 'ঘ', 'ঙ', 'চ'], correctAnswer: 'ঘ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ঘ বুদবুদ ফাটাও', content: 'ঘ', options: ['গ', 'ঘ', 'ঙ', 'চ'], correctAnswer: 'ঘ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ঘ', options: ['গ', 'ঘ', 'ঙ', 'চ'], correctAnswer: 'ঘ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ঘড়ি বানাও', content: 'ঘড়ি', options: ['ঘ', 'ড়', 'ি', 'ম'], correctAnswer: 'ঘড়ি' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ঘ', options: ['গ-গরু', 'ঘ-ঘড়ি', 'চ-চাঁদ', 'ছ-ছাগল'], correctAnswer: 'ঘ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ঘ', voiceText: 'ঘ লেখো', content: 'ঘ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ঘড়ি কোন বর্ণ দিয়ে শুরু?', content: 'ঘ', options: ['গ', 'ঘ', 'চ', 'ছ'], correctAnswer: 'ঘ' },
        ],
    },
    'banjanbarna-cha': {
        id: 'banjanbarna-cha', letter: 'চ', word: 'চাঁদ', wordEn: 'Moon', emoji: '🌙',
        color: 'from-indigo-400 to-violet-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'চ দিয়ে চাঁদ', content: 'চ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — চাঁদ', voiceText: 'চাঁদ', content: 'চাঁদ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'চ', content: 'চ' },
            { id: 'e4', type: 'tap-correct', title: 'চ কোথায়?', voiceText: 'চ খুঁজে বের করো', content: 'চ', options: ['ঘ', 'চ', 'ছ', 'জ'], correctAnswer: 'চ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'চ বুদবুদ ফাটাও', content: 'চ', options: ['ঘ', 'চ', 'ছ', 'জ'], correctAnswer: 'চ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'চ', options: ['ঘ', 'চ', 'ছ', 'জ'], correctAnswer: 'চ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'চাঁদ বানাও', content: 'চাঁদ', options: ['চ', 'া', 'ঁ', 'দ'], correctAnswer: 'চাঁদ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'চ', options: ['ঘ-ঘড়ি', 'চ-চাঁদ', 'ছ-ছাগল', 'জ-জাহাজ'], correctAnswer: 'চ' },
            { id: 'e10', type: 'trace', title: 'লিখি — চ', voiceText: 'চ লেখো', content: 'চ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'চাঁদ কোন বর্ণ দিয়ে শুরু?', content: 'চ', options: ['ঘ', 'চ', 'ছ', 'জ'], correctAnswer: 'চ' },
        ],
    },
    'banjanbarna-chha': {
        id: 'banjanbarna-chha', letter: 'ছ', word: 'ছাগল', wordEn: 'Goat', emoji: '🐐',
        color: 'from-teal-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ছ দিয়ে ছাগল', content: 'ছ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ছাগল', voiceText: 'ছাগল', content: 'ছাগল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ছ', content: 'ছ' },
            { id: 'e4', type: 'tap-correct', title: 'ছ কোথায়?', voiceText: 'ছ খুঁজে বের করো', content: 'ছ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'ছ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ছ বুদবুদ ফাটাও', content: 'ছ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'ছ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ছ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'ছ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ছাগল বানাও', content: 'ছাগল', options: ['ছ', 'া', 'গ', 'ল'], correctAnswer: 'ছাগল' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ছ', options: ['চ-চাঁদ', 'ছ-ছাগল', 'জ-জাহাজ', 'ঝ-ঝড়'], correctAnswer: 'ছ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ছ', voiceText: 'ছ লেখো', content: 'ছ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ছাগল কোন বর্ণ দিয়ে শুরু?', content: 'ছ', options: ['চ', 'ছ', 'জ', 'ঝ'], correctAnswer: 'ছ' },
        ],
    },
    'banjanbarna-ja': {
        id: 'banjanbarna-ja', letter: 'জ', word: 'জাহাজ', wordEn: 'Ship', emoji: '🚢',
        color: 'from-blue-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'জ দিয়ে জাহাজ', content: 'জ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — জাহাজ', voiceText: 'জাহাজ', content: 'জাহাজ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'জ', content: 'জ' },
            { id: 'e4', type: 'tap-correct', title: 'জ কোথায়?', voiceText: 'জ খুঁজে বের করো', content: 'জ', options: ['ছ', 'জ', 'ঝ', 'ট'], correctAnswer: 'জ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'জ বুদবুদ ফাটাও', content: 'জ', options: ['ছ', 'জ', 'ঝ', 'ট'], correctAnswer: 'জ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'জ', options: ['ছ', 'জ', 'ঝ', 'ট'], correctAnswer: 'জ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'জাহাজ বানাও', content: 'জাহাজ', options: ['জ', 'া', 'হ', 'জ'], correctAnswer: 'জাহাজ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'জ', options: ['ছ-ছাগল', 'জ-জাহাজ', 'ঝ-ঝড়', 'ট-টমেটো'], correctAnswer: 'জ' },
            { id: 'e10', type: 'trace', title: 'লিখি — জ', voiceText: 'জ লেখো', content: 'জ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'জাহাজ কোন বর্ণ দিয়ে শুরু?', content: 'জ', options: ['ছ', 'জ', 'ঝ', 'ট'], correctAnswer: 'জ' },
        ],
    },
    'banjanbarna-jha': {
        id: 'banjanbarna-jha', letter: 'ঝ', word: 'ঝড়', wordEn: 'Storm', emoji: '⛈️',
        color: 'from-slate-400 to-gray-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ঝ দিয়ে ঝড়', content: 'ঝ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ঝড়', voiceText: 'ঝড়', content: 'ঝড়' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ঝ', content: 'ঝ' },
            { id: 'e4', type: 'tap-correct', title: 'ঝ কোথায়?', voiceText: 'ঝ খুঁজে বের করো', content: 'ঝ', options: ['জ', 'ঝ', 'ট', 'ঠ'], correctAnswer: 'ঝ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ঝ বুদবুদ ফাটাও', content: 'ঝ', options: ['জ', 'ঝ', 'ট', 'ঠ'], correctAnswer: 'ঝ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ঝ', options: ['জ', 'ঝ', 'ট', 'ঠ'], correctAnswer: 'ঝ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ঝড় বানাও', content: 'ঝড়', options: ['ঝ', 'ড়', 'ম', 'ন'], correctAnswer: 'ঝড়' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ঝ', options: ['জ-জাহাজ', 'ঝ-ঝড়', 'ট-টমেটো', 'ঠ-ঠাণ্ডা'], correctAnswer: 'ঝ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ঝ', voiceText: 'ঝ লেখো', content: 'ঝ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ঝড় কোন বর্ণ দিয়ে শুরু?', content: 'ঝ', options: ['জ', 'ঝ', 'ট', 'ঠ'], correctAnswer: 'ঝ' },
        ],
    },
    'banjanbarna-ta': {
        id: 'banjanbarna-ta', letter: 'ট', word: 'টমেটো', wordEn: 'Tomato', emoji: '🍅',
        color: 'from-red-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ট দিয়ে টমেটো', content: 'ট' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — টমেটো', voiceText: 'টমেটো', content: 'টমেটো' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ট', content: 'ট' },
            { id: 'e4', type: 'tap-correct', title: 'ট কোথায়?', voiceText: 'ট খুঁজে বের করো', content: 'ট', options: ['ঝ', 'ট', 'ঠ', 'ড'], correctAnswer: 'ট' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ট বুদবুদ ফাটাও', content: 'ট', options: ['ঝ', 'ট', 'ঠ', 'ড'], correctAnswer: 'ট' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ট', options: ['ঝ', 'ট', 'ঠ', 'ড'], correctAnswer: 'ট' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'টমেটো বানাও', content: 'টমেটো', options: ['ট', 'ম', 'টো', 'ন'], correctAnswer: 'টমেটো' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ট', options: ['ঝ-ঝড়', 'ট-টমেটো', 'ঠ-ঠাণ্ডা', 'ড-ডিম'], correctAnswer: 'ট' },
            { id: 'e10', type: 'trace', title: 'লিখি — ট', voiceText: 'ট লেখো', content: 'ট' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'টমেটো কোন বর্ণ দিয়ে শুরু?', content: 'ট', options: ['ঝ', 'ট', 'ঠ', 'ড'], correctAnswer: 'ট' },
        ],
    },
    'banjanbarna-da': {
        id: 'banjanbarna-da', letter: 'ড', word: 'ডিম', wordEn: 'Egg', emoji: '🥚',
        color: 'from-amber-400 to-yellow-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ড দিয়ে ডিম', content: 'ড' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ডিম', voiceText: 'ডিম', content: 'ডিম' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ড', content: 'ড' },
            { id: 'e4', type: 'tap-correct', title: 'ড কোথায়?', voiceText: 'ড খুঁজে বের করো', content: 'ড', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ড' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ড বুদবুদ ফাটাও', content: 'ড', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ড' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ড', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ড' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ডিম বানাও', content: 'ডিম', options: ['ড', 'ি', 'ম', 'ন'], correctAnswer: 'ডিম' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ড', options: ['ট-টমেটো', 'ড-ডিম', 'ঢ-ঢোল', 'ণ-নৌকা'], correctAnswer: 'ড' },
            { id: 'e10', type: 'trace', title: 'লিখি — ড', voiceText: 'ড লেখো', content: 'ড' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ডিম কোন বর্ণ দিয়ে শুরু?', content: 'ড', options: ['ট', 'ঠ', 'ড', 'ঢ'], correctAnswer: 'ড' },
        ],
    },
    'banjanbarna-na': {
        id: 'banjanbarna-na', letter: 'ন', word: 'নৌকা', wordEn: 'Boat', emoji: '⛵',
        color: 'from-cyan-400 to-blue-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ন দিয়ে নৌকা', content: 'ন' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — নৌকা', voiceText: 'নৌকা', content: 'নৌকা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ন', content: 'ন' },
            { id: 'e4', type: 'tap-correct', title: 'ন কোথায়?', voiceText: 'ন খুঁজে বের করো', content: 'ন', options: ['ড', 'ঢ', 'ণ', 'ন'], correctAnswer: 'ন' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ন বুদবুদ ফাটাও', content: 'ন', options: ['ড', 'ঢ', 'ণ', 'ন'], correctAnswer: 'ন' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ন', options: ['ড', 'ঢ', 'ণ', 'ন'], correctAnswer: 'ন' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'নৌকা বানাও', content: 'নৌকা', options: ['ন', 'ৌ', 'ক', 'া'], correctAnswer: 'নৌকা' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ন', options: ['ড-ডিম', 'ণ-মণি', 'ন-নৌকা', 'প-পাখি'], correctAnswer: 'ন' },
            { id: 'e10', type: 'trace', title: 'লিখি — ন', voiceText: 'ন লেখো', content: 'ন' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'নৌকা কোন বর্ণ দিয়ে শুরু?', content: 'ন', options: ['ড', 'ণ', 'ন', 'প'], correctAnswer: 'ন' },
        ],
    },

    // ─── ব্যঞ্জনবর্ণ ২ ──────────────────────────────────────────
    'banjanbarna2-pa': {
        id: 'banjanbarna2-pa', letter: 'প', word: 'পাখি', wordEn: 'Bird', emoji: '🐦',
        color: 'from-emerald-400 to-teal-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'প দিয়ে পাখি', content: 'প' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — পাখি', voiceText: 'পাখি', content: 'পাখি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'প', content: 'প' },
            { id: 'e4', type: 'tap-correct', title: 'প কোথায়?', voiceText: 'প খুঁজে বের করো', content: 'প', options: ['ন', 'প', 'ফ', 'ব'], correctAnswer: 'প' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'প বুদবুদ ফাটাও', content: 'প', options: ['ন', 'প', 'ফ', 'ব'], correctAnswer: 'প' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'প', options: ['ন', 'প', 'ফ', 'ব'], correctAnswer: 'প' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'পাখি বানাও', content: 'পাখি', options: ['প', 'া', 'খ', 'ি'], correctAnswer: 'পাখি' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'প', options: ['ন-নৌকা', 'প-পাখি', 'ফ-ফুল', 'ব-বাঘ'], correctAnswer: 'প' },
            { id: 'e10', type: 'trace', title: 'লিখি — প', voiceText: 'প লেখো', content: 'প' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'পাখি কোন বর্ণ দিয়ে শুরু?', content: 'প', options: ['ন', 'প', 'ফ', 'ব'], correctAnswer: 'প' },
        ],
    },
    'banjanbarna2-pha': {
        id: 'banjanbarna2-pha', letter: 'ফ', word: 'ফুল', wordEn: 'Flower', emoji: '🌸',
        color: 'from-pink-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ফ দিয়ে ফুল', content: 'ফ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ফুল', voiceText: 'ফুল', content: 'ফুল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ফ', content: 'ফ' },
            { id: 'e4', type: 'tap-correct', title: 'ফ কোথায়?', voiceText: 'ফ খুঁজে বের করো', content: 'ফ', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'ফ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ফ বুদবুদ ফাটাও', content: 'ফ', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'ফ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ফ', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'ফ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ফুল বানাও', content: 'ফুল', options: ['ফ', 'ু', 'ল', 'ম'], correctAnswer: 'ফুল' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ফ', options: ['প-পাখি', 'ফ-ফুল', 'ব-বাঘ', 'ভ-ভালুক'], correctAnswer: 'ফ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ফ', voiceText: 'ফ লেখো', content: 'ফ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ফুল কোন বর্ণ দিয়ে শুরু?', content: 'ফ', options: ['প', 'ফ', 'ব', 'ভ'], correctAnswer: 'ফ' },
        ],
    },
    'banjanbarna2-ba': {
        id: 'banjanbarna2-ba', letter: 'ব', word: 'বাঘ', wordEn: 'Tiger', emoji: '🐯',
        color: 'from-orange-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ব দিয়ে বাঘ', content: 'ব' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — বাঘ', voiceText: 'বাঘ', content: 'বাঘ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ব', content: 'ব' },
            { id: 'e4', type: 'tap-correct', title: 'ব কোথায়?', voiceText: 'ব খুঁজে বের করো', content: 'ব', options: ['ফ', 'ব', 'ভ', 'ম'], correctAnswer: 'ব' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ব বুদবুদ ফাটাও', content: 'ব', options: ['ফ', 'ব', 'ভ', 'ম'], correctAnswer: 'ব' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ব', options: ['ফ', 'ব', 'ভ', 'ম'], correctAnswer: 'ব' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'বাঘ বানাও', content: 'বাঘ', options: ['ব', 'া', 'ঘ', 'ম'], correctAnswer: 'বাঘ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ব', options: ['ফ-ফুল', 'ব-বাঘ', 'ভ-ভালুক', 'ম-মাছ'], correctAnswer: 'ব' },
            { id: 'e10', type: 'trace', title: 'লিখি — ব', voiceText: 'ব লেখো', content: 'ব' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'বাঘ কোন বর্ণ দিয়ে শুরু?', content: 'ব', options: ['ফ', 'ব', 'ভ', 'ম'], correctAnswer: 'ব' },
        ],
    },
    'banjanbarna2-bha': {
        id: 'banjanbarna2-bha', letter: 'ভ', word: 'ভালুক', wordEn: 'Bear', emoji: '🐻',
        color: 'from-brown-400 to-amber-700', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ভ দিয়ে ভালুক', content: 'ভ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ভালুক', voiceText: 'ভালুক', content: 'ভালুক' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ভ', content: 'ভ' },
            { id: 'e4', type: 'tap-correct', title: 'ভ কোথায়?', voiceText: 'ভ খুঁজে বের করো', content: 'ভ', options: ['ব', 'ভ', 'ম', 'য'], correctAnswer: 'ভ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ভ বুদবুদ ফাটাও', content: 'ভ', options: ['ব', 'ভ', 'ম', 'য'], correctAnswer: 'ভ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ভ', options: ['ব', 'ভ', 'ম', 'য'], correctAnswer: 'ভ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'ভালুক বানাও', content: 'ভালুক', options: ['ভ', 'া', 'লু', 'ক'], correctAnswer: 'ভালুক' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ভ', options: ['ব-বাঘ', 'ভ-ভালুক', 'ম-মাছ', 'য-যন্ত্র'], correctAnswer: 'ভ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ভ', voiceText: 'ভ লেখো', content: 'ভ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ভালুক কোন বর্ণ দিয়ে শুরু?', content: 'ভ', options: ['ব', 'ভ', 'ম', 'য'], correctAnswer: 'ভ' },
        ],
    },
    'banjanbarna2-ma': {
        id: 'banjanbarna2-ma', letter: 'ম', word: 'মাছ', wordEn: 'Fish', emoji: '🐟',
        color: 'from-blue-400 to-cyan-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ম দিয়ে মাছ', content: 'ম' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — মাছ', voiceText: 'মাছ', content: 'মাছ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ম', content: 'ম' },
            { id: 'e4', type: 'tap-correct', title: 'ম কোথায়?', voiceText: 'ম খুঁজে বের করো', content: 'ম', options: ['ভ', 'ম', 'য', 'র'], correctAnswer: 'ম' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ম বুদবুদ ফাটাও', content: 'ম', options: ['ভ', 'ম', 'য', 'র'], correctAnswer: 'ম' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ম', options: ['ভ', 'ম', 'য', 'র'], correctAnswer: 'ম' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'মাছ বানাও', content: 'মাছ', options: ['ম', 'া', 'ছ', 'ন'], correctAnswer: 'মাছ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ম', options: ['ভ-ভালুক', 'ম-মাছ', 'য-যন্ত্র', 'র-রকেট'], correctAnswer: 'ম' },
            { id: 'e10', type: 'trace', title: 'লিখি — ম', voiceText: 'ম লেখো', content: 'ম' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'মাছ কোন বর্ণ দিয়ে শুরু?', content: 'ম', options: ['ভ', 'ম', 'য', 'র'], correctAnswer: 'ম' },
        ],
    },
    'banjanbarna2-na': {
        id: 'banjanbarna2-na', letter: 'ণ', word: 'মণি', wordEn: 'Gem', emoji: '💎',
        color: 'from-purple-400 to-violet-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ণ দিয়ে মণি', content: 'ণ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — মণি', voiceText: 'মণি', content: 'মণি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ণ', content: 'ণ' },
            { id: 'e4', type: 'tap-correct', title: 'ণ কোথায়?', voiceText: 'ণ খুঁজে বের করো', content: 'ণ', options: ['ড', 'ঢ', 'ণ', 'ন'], correctAnswer: 'ণ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ণ বুদবুদ ফাটাও', content: 'ণ', options: ['ড', 'ঢ', 'ণ', 'ন'], correctAnswer: 'ণ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ণ', options: ['ড', 'ঢ', 'ণ', 'ন'], correctAnswer: 'ণ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'মণি বানাও', content: 'মণি', options: ['ম', 'ণ', 'ি', 'ন'], correctAnswer: 'মণি' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ণ', options: ['ড-ডিম', 'ণ-মণি', 'ন-নৌকা', 'প-পাখি'], correctAnswer: 'ণ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ণ', voiceText: 'ণ লেখো', content: 'ণ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'মণি শব্দে কোন বর্ণ আছে?', content: 'ণ', options: ['ড', 'ণ', 'ন', 'প'], correctAnswer: 'ণ' },
        ],
    },
    'banjanbarna2-da': {
        id: 'banjanbarna2-da', letter: 'ত', word: 'তরমুজ', wordEn: 'Watermelon', emoji: '🍉',
        color: 'from-green-400 to-red-400', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ত দিয়ে তরমুজ', content: 'ত' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — তরমুজ', voiceText: 'তরমুজ', content: 'তরমুজ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ত', content: 'ত' },
            { id: 'e4', type: 'tap-correct', title: 'ত কোথায়?', voiceText: 'ত খুঁজে বের করো', content: 'ত', options: ['ণ', 'ত', 'থ', 'দ'], correctAnswer: 'ত' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ত বুদবুদ ফাটাও', content: 'ত', options: ['ণ', 'ত', 'থ', 'দ'], correctAnswer: 'ত' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ত', options: ['ণ', 'ত', 'থ', 'দ'], correctAnswer: 'ত' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'তরমুজ বানাও', content: 'তরমুজ', options: ['ত', 'র', 'মু', 'জ'], correctAnswer: 'তরমুজ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ত', options: ['ণ-মণি', 'ত-তরমুজ', 'থ-থালা', 'দ-দরজা'], correctAnswer: 'ত' },
            { id: 'e10', type: 'trace', title: 'লিখি — ত', voiceText: 'ত লেখো', content: 'ত' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'তরমুজ কোন বর্ণ দিয়ে শুরু?', content: 'ত', options: ['ণ', 'ত', 'থ', 'দ'], correctAnswer: 'ত' },
        ],
    },
    'banjanbarna2-ta': {
        id: 'banjanbarna2-ta', letter: 'থ', word: 'থালা', wordEn: 'Plate', emoji: '🍽️',
        color: 'from-slate-400 to-gray-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'থ দিয়ে থালা', content: 'থ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — থালা', voiceText: 'থালা', content: 'থালা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'থ', content: 'থ' },
            { id: 'e4', type: 'tap-correct', title: 'থ কোথায়?', voiceText: 'থ খুঁজে বের করো', content: 'থ', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'থ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'থ বুদবুদ ফাটাও', content: 'থ', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'থ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'থ', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'থ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'থালা বানাও', content: 'থালা', options: ['থ', 'া', 'ল', 'া'], correctAnswer: 'থালা' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'থ', options: ['ত-তরমুজ', 'থ-থালা', 'দ-দরজা', 'ধ-ধান'], correctAnswer: 'থ' },
            { id: 'e10', type: 'trace', title: 'লিখি — থ', voiceText: 'থ লেখো', content: 'থ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'থালা কোন বর্ণ দিয়ে শুরু?', content: 'থ', options: ['ত', 'থ', 'দ', 'ধ'], correctAnswer: 'থ' },
        ],
    },

    // ─── ব্যঞ্জনবর্ণ ৩ ──────────────────────────────────────────
    'banjanbarna3-ya': {
        id: 'banjanbarna3-ya', letter: 'য', word: 'যন্ত্র', wordEn: 'Machine', emoji: '⚙️',
        color: 'from-gray-400 to-slate-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'য দিয়ে যন্ত্র', content: 'য' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — যন্ত্র', voiceText: 'যন্ত্র', content: 'যন্ত্র' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'য', content: 'য' },
            { id: 'e4', type: 'tap-correct', title: 'য কোথায়?', voiceText: 'য খুঁজে বের করো', content: 'য', options: ['ম', 'য', 'র', 'ল'], correctAnswer: 'য' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'য বুদবুদ ফাটাও', content: 'য', options: ['ম', 'য', 'র', 'ল'], correctAnswer: 'য' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'য', options: ['ম', 'য', 'র', 'ল'], correctAnswer: 'য' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'যন্ত্র বানাও', content: 'যন্ত্র', options: ['য', 'ন', 'ত', 'র'], correctAnswer: 'যন্ত্র' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'য', options: ['ম-মাছ', 'য-যন্ত্র', 'র-রকেট', 'ল-লাউ'], correctAnswer: 'য' },
            { id: 'e10', type: 'trace', title: 'লিখি — য', voiceText: 'য লেখো', content: 'য' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'যন্ত্র কোন বর্ণ দিয়ে শুরু?', content: 'য', options: ['ম', 'য', 'র', 'ল'], correctAnswer: 'য' },
        ],
    },
    'banjanbarna3-ra': {
        id: 'banjanbarna3-ra', letter: 'র', word: 'রকেট', wordEn: 'Rocket', emoji: '🚀',
        color: 'from-red-400 to-orange-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'র দিয়ে রকেট', content: 'র' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — রকেট', voiceText: 'রকেট', content: 'রকেট' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'র', content: 'র' },
            { id: 'e4', type: 'tap-correct', title: 'র কোথায়?', voiceText: 'র খুঁজে বের করো', content: 'র', options: ['য', 'র', 'ল', 'শ'], correctAnswer: 'র' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'র বুদবুদ ফাটাও', content: 'র', options: ['য', 'র', 'ল', 'শ'], correctAnswer: 'র' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'র', options: ['য', 'র', 'ল', 'শ'], correctAnswer: 'র' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'রকেট বানাও', content: 'রকেট', options: ['র', 'ক', 'ট', 'ম'], correctAnswer: 'রকেট' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'র', options: ['য-যন্ত্র', 'র-রকেট', 'ল-লাউ', 'শ-শিয়াল'], correctAnswer: 'র' },
            { id: 'e10', type: 'trace', title: 'লিখি — র', voiceText: 'র লেখো', content: 'র' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'রকেট কোন বর্ণ দিয়ে শুরু?', content: 'র', options: ['য', 'র', 'ল', 'শ'], correctAnswer: 'র' },
        ],
    },
    'banjanbarna3-rra': {
        id: 'banjanbarna3-rra', letter: 'ড়', word: 'ড়শি', wordEn: 'Rope', emoji: '🪢',
        color: 'from-amber-400 to-orange-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ড় এর উচ্চারণ শিখি', content: 'ড়' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — গড়', voiceText: 'গড়', content: 'গড়' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ড়', content: 'ড়' },
            { id: 'e4', type: 'tap-correct', title: 'ড় কোথায়?', voiceText: 'ড় খুঁজে বের করো', content: 'ড়', options: ['ড', 'ঢ', 'ড়', 'ঢ়'], correctAnswer: 'ড়' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ড় বুদবুদ ফাটাও', content: 'ড়', options: ['ড', 'ঢ', 'ড়', 'ঢ়'], correctAnswer: 'ড়' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ড়', options: ['ড', 'ঢ', 'ড়', 'ঢ়'], correctAnswer: 'ড়' },
            { id: 'e10', type: 'trace', title: 'লিখি — ড়', voiceText: 'ড় লেখো', content: 'ড়' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'গড় শব্দে কোন বর্ণ আছে?', content: 'ড়', options: ['ড', 'ঢ', 'ড়', 'র'], correctAnswer: 'ড়' },
        ],
    },
    'banjanbarna3-la': {
        id: 'banjanbarna3-la', letter: 'ল', word: 'লাউ', wordEn: 'Gourd', emoji: '🥬',
        color: 'from-green-400 to-lime-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ল দিয়ে লাউ', content: 'ল' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — লাউ', voiceText: 'লাউ', content: 'লাউ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ল', content: 'ল' },
            { id: 'e4', type: 'tap-correct', title: 'ল কোথায়?', voiceText: 'ল খুঁজে বের করো', content: 'ল', options: ['র', 'ল', 'শ', 'ষ'], correctAnswer: 'ল' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ল বুদবুদ ফাটাও', content: 'ল', options: ['র', 'ল', 'শ', 'ষ'], correctAnswer: 'ল' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'ল', options: ['র', 'ল', 'শ', 'ষ'], correctAnswer: 'ল' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'লাউ বানাও', content: 'লাউ', options: ['ল', 'া', 'উ', 'ম'], correctAnswer: 'লাউ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'ল', options: ['র-রকেট', 'ল-লাউ', 'শ-শিয়াল', 'ষ-ষাঁড়'], correctAnswer: 'ল' },
            { id: 'e10', type: 'trace', title: 'লিখি — ল', voiceText: 'ল লেখো', content: 'ল' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'লাউ কোন বর্ণ দিয়ে শুরু?', content: 'ল', options: ['র', 'ল', 'শ', 'ষ'], correctAnswer: 'ল' },
        ],
    },
    'banjanbarna3-sha': {
        id: 'banjanbarna3-sha', letter: 'শ', word: 'শিয়াল', wordEn: 'Fox', emoji: '🦊',
        color: 'from-orange-400 to-red-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'শ দিয়ে শিয়াল', content: 'শ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — শিয়াল', voiceText: 'শিয়াল', content: 'শিয়াল' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'শ', content: 'শ' },
            { id: 'e4', type: 'tap-correct', title: 'শ কোথায়?', voiceText: 'শ খুঁজে বের করো', content: 'শ', options: ['ল', 'শ', 'ষ', 'স'], correctAnswer: 'শ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'শ বুদবুদ ফাটাও', content: 'শ', options: ['ল', 'শ', 'ষ', 'স'], correctAnswer: 'শ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'শ', options: ['ল', 'শ', 'ষ', 'স'], correctAnswer: 'শ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'শিয়াল বানাও', content: 'শিয়াল', options: ['শ', 'ি', 'য়া', 'ল'], correctAnswer: 'শিয়াল' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'শ', options: ['ল-লাউ', 'শ-শিয়াল', 'ষ-ষাঁড়', 'স-সাপ'], correctAnswer: 'শ' },
            { id: 'e10', type: 'trace', title: 'লিখি — শ', voiceText: 'শ লেখো', content: 'শ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'শিয়াল কোন বর্ণ দিয়ে শুরু?', content: 'শ', options: ['ল', 'শ', 'ষ', 'স'], correctAnswer: 'শ' },
        ],
    },
    'banjanbarna3-sa': {
        id: 'banjanbarna3-sa', letter: 'স', word: 'সাপ', wordEn: 'Snake', emoji: '🐍',
        color: 'from-lime-400 to-green-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'স দিয়ে সাপ', content: 'স' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — সাপ', voiceText: 'সাপ', content: 'সাপ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'স', content: 'স' },
            { id: 'e4', type: 'tap-correct', title: 'স কোথায়?', voiceText: 'স খুঁজে বের করো', content: 'স', options: ['শ', 'ষ', 'স', 'হ'], correctAnswer: 'স' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'স বুদবুদ ফাটাও', content: 'স', options: ['শ', 'ষ', 'স', 'হ'], correctAnswer: 'স' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'স', options: ['শ', 'ষ', 'স', 'হ'], correctAnswer: 'স' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'সাপ বানাও', content: 'সাপ', options: ['স', 'া', 'প', 'ম'], correctAnswer: 'সাপ' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'স', options: ['শ-শিয়াল', 'ষ-ষাঁড়', 'স-সাপ', 'হ-হাতি'], correctAnswer: 'স' },
            { id: 'e10', type: 'trace', title: 'লিখি — স', voiceText: 'স লেখো', content: 'স' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'সাপ কোন বর্ণ দিয়ে শুরু?', content: 'স', options: ['শ', 'ষ', 'স', 'হ'], correctAnswer: 'স' },
        ],
    },
    'banjanbarna3-ha': {
        id: 'banjanbarna3-ha', letter: 'হ', word: 'হাতি', wordEn: 'Elephant', emoji: '🐘',
        color: 'from-gray-400 to-slate-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'হ দিয়ে হাতি', content: 'হ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — হাতি', voiceText: 'হাতি', content: 'হাতি' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'হ', content: 'হ' },
            { id: 'e4', type: 'tap-correct', title: 'হ কোথায়?', voiceText: 'হ খুঁজে বের করো', content: 'হ', options: ['স', 'হ', 'ড়', 'য়'], correctAnswer: 'হ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'হ বুদবুদ ফাটাও', content: 'হ', options: ['স', 'হ', 'ড়', 'য়'], correctAnswer: 'হ' },
            { id: 'e7', type: 'letter-puzzle', title: 'ধাঁধা মেলাও!', voiceText: 'সঠিক বর্ণ বেছে নাও', content: 'হ', options: ['স', 'হ', 'ড়', 'য়'], correctAnswer: 'হ' },
            { id: 'e8', type: 'word-builder', title: 'শব্দ বানাও!', voiceText: 'হাতি বানাও', content: 'হাতি', options: ['হ', 'া', 'ত', 'ি'], correctAnswer: 'হাতি' },
            { id: 'e9', type: 'matching', title: 'মেলাও!', voiceText: 'বর্ণ আর শব্দ মেলাও', content: 'হ', options: ['স-সাপ', 'হ-হাতি', 'ড়-গড়', 'য়-ময়ূর'], correctAnswer: 'হ' },
            { id: 'e10', type: 'trace', title: 'লিখি — হ', voiceText: 'হ লেখো', content: 'হ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'হাতি কোন বর্ণ দিয়ে শুরু?', content: 'হ', options: ['স', 'হ', 'ড়', 'য়'], correctAnswer: 'হ' },
        ],
    },

    // ─── যুক্তবর্ণ ───────────────────────────────────────────────
    'jukta-ksha': {
        id: 'jukta-ksha', letter: 'ক্ষ', word: 'ক্ষমা', wordEn: 'Forgiveness', emoji: '🤝',
        color: 'from-violet-400 to-purple-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ক্ষ দিয়ে ক্ষমা', content: 'ক্ষ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ক্ষমা', voiceText: 'ক্ষমা', content: 'ক্ষমা' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ক্ষ', content: 'ক্ষ' },
            { id: 'e4', type: 'tap-correct', title: 'ক্ষ কোথায়?', voiceText: 'ক্ষ খুঁজে বের করো', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ক্ষ বুদবুদ ফাটাও', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
            { id: 'e10', type: 'trace', title: 'লিখি — ক্ষ', voiceText: 'ক্ষ লেখো', content: 'ক্ষ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ক্ষমা কোন বর্ণ দিয়ে শুরু?', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
        ],
    },
    'jukta-gya': {
        id: 'jukta-gya', letter: 'জ্ঞ', word: 'জ্ঞান', wordEn: 'Knowledge', emoji: '📖',
        color: 'from-amber-400 to-yellow-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'জ্ঞ দিয়ে জ্ঞান', content: 'জ্ঞ' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — জ্ঞান', voiceText: 'জ্ঞান', content: 'জ্ঞান' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'জ্ঞান', content: 'জ্ঞ' },
            { id: 'e4', type: 'tap-correct', title: 'জ্ঞ কোথায়?', voiceText: 'জ্ঞ খুঁজে বের করো', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'জ্ঞ বুদবুদ ফাটাও', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
            { id: 'e10', type: 'trace', title: 'লিখি — জ্ঞ', voiceText: 'জ্ঞ লেখো', content: 'জ্ঞ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'জ্ঞান কোন বর্ণ দিয়ে শুরু?', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
        ],
    },
    'jukta-tra': {
        id: 'jukta-tra', letter: 'ত্র', word: 'ত্রিভুজ', wordEn: 'Triangle', emoji: '🔺',
        color: 'from-red-400 to-rose-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'ত্র দিয়ে ত্রিভুজ', content: 'ত্র' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — ত্রিভুজ', voiceText: 'ত্রিভুজ', content: 'ত্রিভুজ' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'ত্র', content: 'ত্র' },
            { id: 'e4', type: 'tap-correct', title: 'ত্র কোথায়?', voiceText: 'ত্র খুঁজে বের করো', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'ত্র বুদবুদ ফাটাও', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
            { id: 'e10', type: 'trace', title: 'লিখি — ত্র', voiceText: 'ত্র লেখো', content: 'ত্র' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'ত্রিভুজ কোন বর্ণ দিয়ে শুরু?', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
        ],
    },
    'jukta-shra': {
        id: 'jukta-shra', letter: 'শ্র', word: 'শ্রম', wordEn: 'Labour', emoji: '💪',
        color: 'from-blue-400 to-indigo-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'এটি কী?', voiceText: 'শ্র দিয়ে শ্রম', content: 'শ্র' },
            { id: 'e2', type: 'listen-repeat', title: 'বলো — শ্রম', voiceText: 'শ্রম', content: 'শ্রম' },
            { id: 'e3', type: 'pronounce', title: 'জোরে বলো!', voiceText: 'শ্র', content: 'শ্র' },
            { id: 'e4', type: 'tap-correct', title: 'শ্র কোথায়?', voiceText: 'শ্র খুঁজে বের করো', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
            { id: 'e5', type: 'bubble-pop', title: 'বুদবুদ ফাটাও!', voiceText: 'শ্র বুদবুদ ফাটাও', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
            { id: 'e10', type: 'trace', title: 'লিখি — শ্র', voiceText: 'শ্র লেখো', content: 'শ্র' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'শ্রম কোন বর্ণ দিয়ে শুরু?', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
        ],
    },
    'jukta-review': {
        id: 'jukta-review', letter: '★', word: 'রিভিশন', wordEn: 'Review', emoji: '🌟',
        color: 'from-yellow-400 to-amber-500', lang: 'bn-BD',
        backHref: '/dashboard/student/kids-zone/nursery/bangla',
        exercises: [
            { id: 'e1', type: 'intro', title: 'সব যুক্তবর্ণ', voiceText: 'সব যুক্তবর্ণ রিভিশন করি', content: '★' },
            { id: 'e4', type: 'tap-correct', title: 'ক্ষমা কোন বর্ণ?', voiceText: 'ক্ষমা কোন বর্ণ দিয়ে শুরু?', content: 'ক্ষ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ক্ষ' },
            { id: 'e5', type: 'tap-correct', title: 'জ্ঞান কোন বর্ণ?', voiceText: 'জ্ঞান কোন বর্ণ দিয়ে শুরু?', content: 'জ্ঞ', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'জ্ঞ' },
            { id: 'e6', type: 'tap-correct', title: 'ত্রিভুজ কোন বর্ণ?', voiceText: 'ত্রিভুজ কোন বর্ণ দিয়ে শুরু?', content: 'ত্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'ত্র' },
            { id: 'e7', type: 'matching', title: 'সব মেলাও!', voiceText: 'যুক্তবর্ণ আর শব্দ মেলাও', content: '★', options: ['ক্ষ-ক্ষমা', 'জ্ঞ-জ্ঞান', 'ত্র-ত্রিভুজ', 'শ্র-শ্রম'], correctAnswer: 'ক্ষ' },
            { id: 'e11', type: 'quiz', title: 'শেষ প্রশ্ন!', voiceText: 'শ্রম কোন বর্ণ দিয়ে শুরু?', content: 'শ্র', options: ['ক্ষ', 'জ্ঞ', 'ত্র', 'শ্র'], correctAnswer: 'শ্র' },
        ],
    },
}

export default function BanglaLessonPage() {
    const params = useParams()
    const lessonId = params.lessonId as string
    const lesson = lessons[lessonId]

    if (!lesson) return (
        <div className="min-h-screen bg-[#0a0a1a] flex items-center justify-center text-white">
            <div className="text-center">
                <div className="text-6xl mb-4">😕</div>
                <p className="text-gray-400 mb-2">Lesson পাওয়া যায়নি</p>
                <p className="text-gray-600 text-sm">ID: {lessonId}</p>
            </div>
        </div>
    )

    return <LessonEngine lesson={lesson} />
}