import { NextRequest, NextResponse } from "next/server";
import { requireRole } from "@/lib/api-auth";
import { audit } from "@/lib/audit";
import { CreateCurriculumVersionSchema, UpdateCurriculumVersionSchema, validateBody } from "@/lib/validation";

export async function GET() { const auth = await requireRole(["admin"]); if ("error" in auth) return auth.error; const { data, error } = await auth.supabase.from("curriculum_versions").select("*").order("year", { ascending: false }); return error ? NextResponse.json({ error: "Curriculum version আনা যায়নি।" }, { status: 500 }) : NextResponse.json(data ?? []); }
export async function POST(req: NextRequest) { const auth = await requireRole(["admin"]); if ("error" in auth) return auth.error; const body = await validateBody(CreateCurriculumVersionSchema, req); if (body instanceof NextResponse) return body; if (body.isActive) await auth.supabase.from("curriculum_versions").update({ is_active: false }).neq("id", ""); const { data, error } = await auth.supabase.from("curriculum_versions").insert({ slug: body.slug, name: body.name, year: body.year, description: body.description ?? null, status: body.status ?? "draft", is_active: body.isActive ?? false }).select().single(); if (error) return NextResponse.json({ error: "Curriculum version তৈরি করা যায়নি।" }, { status: 500 }); await audit("CREATE_CURRICULUM_VERSION", auth.user.id, { versionId: data.id, name: data.name }); return NextResponse.json(data, { status: 201 }); }
export async function PATCH(req: NextRequest) { const auth = await requireRole(["admin"]); if ("error" in auth) return auth.error; const id = new URL(req.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Version ID আবশ্যক।" }, { status: 400 }); const body = await validateBody(UpdateCurriculumVersionSchema, req); if (body instanceof NextResponse) return body; if (body.isActive) await auth.supabase.from("curriculum_versions").update({ is_active: false }).neq("id", id); const update = { ...(body.name !== undefined && { name: body.name }), ...(body.slug !== undefined && { slug: body.slug }), ...(body.year !== undefined && { year: body.year }), ...(body.description !== undefined && { description: body.description }), ...(body.status !== undefined && { status: body.status }), ...(body.isActive !== undefined && { is_active: body.isActive }) }; const { data, error } = await auth.supabase.from("curriculum_versions").update(update).eq("id", id).select().single(); if (error) return NextResponse.json({ error: "Curriculum version আপডেট করা যায়নি।" }, { status: 500 }); await audit("UPDATE_CURRICULUM_VERSION", auth.user.id, { versionId: id, ...update }); return NextResponse.json(data); }
export async function DELETE(req: NextRequest) { const auth = await requireRole(["admin"]); if ("error" in auth) return auth.error; const id = new URL(req.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Version ID আবশ্যক।" }, { status: 400 }); const { data: version } = await auth.supabase.from("curriculum_versions").select("name, is_active").eq("id", id).maybeSingle(); if (!version) return NextResponse.json({ error: "Version পাওয়া যায়নি।" }, { status: 404 }); if (version.is_active) return NextResponse.json({ error: "Active version মুছে ফেলা যাবে না।" }, { status: 409 }); const { error } = await auth.supabase.from("curriculum_versions").delete().eq("id", id); if (error) return NextResponse.json({ error: "Curriculum version মুছে ফেলা যায়নি।" }, { status: 500 }); await audit("DELETE_CURRICULUM_VERSION", auth.user.id, { versionId: id, name: version.name }); return NextResponse.json({ message: "Version deleted" }); }
